{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl"]]},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl\/accept(completion:)","interfaceLanguage":"swift"},"metadata":{"role":"symbol","modules":[{"name":"AtomicXCore"}],"symbolKind":"method","title":"accept(completion:)","externalID":"s:11AtomicXCore17CallListStoreImplC6accept10completionyys6ResultOyytAA9ErrorInfoVGcSg_tF","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"accept"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","kind":"typeIdentifier","text":"CompletionClosure"},{"kind":"text","text":"?)"}],"roleHeading":"Instance Method"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accept","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CompletionClosure","text":"CompletionClosure","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/atomicxcore\/callliststoreimpl\/accept(completion:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CompletionClosure":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"CompletionClosure"}],"abstract":[{"type":"text","text":"完成回调闭包类型"},{"type":"text","text":" "},{"type":"text","text":"用于异步操作的结果回调，成功返回 Void，失败返回 ErrorInfo"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CompletionClosure"}],"title":"CompletionClosure","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CompletionClosure","url":"\/documentation\/atomicxcore\/completionclosure"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallListStoreImpl/accept(completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accept","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CompletionClosure","kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl\/accept(completion:)","type":"topic","title":"accept(completion:)","kind":"symbol","role":"symbol","url":"\/documentation\/atomicxcore\/callliststoreimpl\/accept(completion:)","abstract":[]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallListStoreImpl":{"kind":"symbol","type":"topic","title":"CallListStoreImpl","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallListStoreImpl","kind":"identifier"}],"role":"symbol","url":"\/documentation\/atomicxcore\/callliststoreimpl","navigatorTitle":[{"text":"CallListStoreImpl","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"url":"\/documentation\/atomicxcore","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","type":"topic","kind":"symbol","abstract":[],"role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStoreImpl\/title","value":"CallListStoreImpl","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStoreImpl\/fragments","value":[{"text":"CallListStoreImpl","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStoreImpl\/navigatorTitle","value":[{"text":"CallListStoreImpl","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}