{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/callliststoreimpl\/hangup(completion:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl\/hangup(completion:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hangup","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CompletionClosure","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CompletionClosure"},{"text":"?)","kind":"text"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"modules":[{"name":"AtomicXCore"}],"externalID":"s:11AtomicXCore17CallListStoreImplC6hangup10completionyys6ResultOyytAA9ErrorInfoVGcSg_tF","title":"hangup(completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hangup","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CompletionClosure","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method"},"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CompletionClosure":{"url":"\/documentation\/atomicxcore\/completionclosure","abstract":[{"type":"text","text":"完成回调闭包类型"},{"type":"text","text":" "},{"type":"text","text":"用于异步操作的结果回调，成功返回 Void，失败返回 ErrorInfo"}],"type":"topic","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CompletionClosure","kind":"identifier"}],"title":"CompletionClosure","role":"symbol","navigatorTitle":[{"text":"CompletionClosure","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CompletionClosure"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallListStoreImpl/hangup(completion:)":{"role":"symbol","title":"hangup(completion:)","url":"\/documentation\/atomicxcore\/callliststoreimpl\/hangup(completion:)","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hangup","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CompletionClosure","kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea"},{"text":"?)","kind":"text"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl\/hangup(completion:)"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"kind":"symbol","abstract":[],"type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallListStoreImpl":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallListStoreImpl","kind":"identifier"}],"navigatorTitle":[{"text":"CallListStoreImpl","kind":"identifier"}],"title":"CallListStoreImpl","abstract":[],"role":"symbol","type":"topic","url":"\/documentation\/atomicxcore\/callliststoreimpl"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStoreImpl\/title","value":"CallListStoreImpl","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStoreImpl\/fragments","value":[{"text":"CallListStoreImpl","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStoreImpl\/navigatorTitle","value":[{"text":"CallListStoreImpl","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}