{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl"]]},"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"code":"TUICallObserver.onCallNotConnected(callId:mediaType:reason:userId:info:)","type":"codeVoice"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/callliststoreimpl\/oncallnotconnected(callid:mediatype:reason:userid:info:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/atomicxcore\/callliststoreimpl\/oncallnotconnected(callid:mediatype:reason:userid:info:)"]}],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onCallNotConnected"},{"kind":"text","text":"("},{"kind":"externalParam","text":"callId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mediaType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@TUICallMediaType","text":"TUICallMediaType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@TUICallEndReason","text":"TUICallEndReason"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUICallObserverExtraInfo","text":"TUICallObserverExtraInfo"},{"kind":"text","text":")"}],"externalID":"c:@CM@AtomicXCore@objc(cs)CallListStoreImpl(im)onCallNotConnected:mediaType:reason:userId:info:","navigatorTitle":[{"kind":"identifier","text":"onCallNotConnected:mediaType:reason:userId:info:"}],"extendedModule":"AtomicXCore","symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"AtomicXCore"}],"title":"onCallNotConnected(callId:mediaType:reason:userId:info:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onCallNotConnected","kind":"identifier"},{"text":"(","kind":"text"},{"text":"callId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"mediaType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@TUICallMediaType","text":"TUICallMediaType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"reason","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@TUICallEndReason","text":"TUICallEndReason","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"userId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"info","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)TUICallObserverExtraInfo","text":"TUICallObserverExtraInfo","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl\/onCallNotConnected(callId:mediaType:reason:userId:info:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"url":"\/documentation\/atomicxcore","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","type":"topic","kind":"symbol","abstract":[],"role":"collection"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallListStoreImpl/onCallNotConnected(callId:mediaType:reason:userId:info:)":{"kind":"symbol","title":"onCallNotConnected(callId:mediaType:reason:userId:info:)","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl\/onCallNotConnected(callId:mediaType:reason:userId:info:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onCallNotConnected","kind":"identifier"},{"text":"(","kind":"text"},{"text":"callId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"mediaType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@TUICallMediaType","text":"TUICallMediaType","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@TUICallEndReason","kind":"typeIdentifier","text":"TUICallEndReason"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)TUICallObserverExtraInfo","kind":"typeIdentifier","text":"TUICallObserverExtraInfo"},{"kind":"text","text":")"}],"url":"\/documentation\/atomicxcore\/callliststoreimpl\/oncallnotconnected(callid:mediatype:reason:userid:info:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"onCallNotConnected:mediaType:reason:userId:info:"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallListStoreImpl":{"kind":"symbol","type":"topic","title":"CallListStoreImpl","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallListStoreImpl","kind":"identifier"}],"role":"symbol","url":"\/documentation\/atomicxcore\/callliststoreimpl","navigatorTitle":[{"text":"CallListStoreImpl","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"onCallNotConnected:mediaType:reason:userId:info:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onCallNotConnected:mediaType:reason:userId:info:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"onCallNotConnected:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"callId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"mediaType:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@TUICallMediaType","kind":"typeIdentifier","text":"TUICallMediaType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"mediaType"},{"kind":"text","text":" "},{"kind":"identifier","text":"reason:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@TUICallEndReason","kind":"typeIdentifier","text":"TUICallEndReason"},{"kind":"text","text":") "},{"kind":"internalParam","text":"reason"},{"kind":"text","text":" "},{"kind":"identifier","text":"userId:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"userId"},{"kind":"text","text":" "},{"kind":"identifier","text":"info:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)TUICallObserverExtraInfo","kind":"typeIdentifier","text":"TUICallObserverExtraInfo"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"info"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"onCallNotConnected:mediaType:reason:userId:info:","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStoreImpl~1onCallNotConnected(callId:mediaType:reason:userId:info:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onCallNotConnected:mediaType:reason:userId:info:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStoreImpl~1onCallNotConnected(callId:mediaType:reason:userId:info:)\/fragments"},{"op":"replace","value":"CallListStoreImpl","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStoreImpl\/title"},{"op":"replace","value":[{"kind":"identifier","text":"CallListStoreImpl"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStoreImpl\/fragments"},{"op":"replace","value":[{"text":"CallListStoreImpl","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStoreImpl\/navigatorTitle"}]}]}