{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl\/onCallReceived(_:callerId:calleeIdList:mediaType:info:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl"]]},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/atomicxcore\/callliststoreimpl\/oncallreceived(_:callerid:calleeidlist:mediatype:info:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/atomicxcore\/callliststoreimpl\/oncallreceived(_:callerid:calleeidlist:mediatype:info:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"TUICallObserver.onCallReceived(_:callerId:calleeIdList:mediaType:info:)"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onCallReceived"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"callId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"callerId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"calleeIdList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"mediaType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TUICallMediaType","preciseIdentifier":"c:@E@TUICallMediaType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TUICallObserverExtraInfo","preciseIdentifier":"c:objc(cs)TUICallObserverExtraInfo"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onCallReceived"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"callerId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"calleeIdList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"mediaType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TUICallMediaType","preciseIdentifier":"c:@E@TUICallMediaType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TUICallObserverExtraInfo","preciseIdentifier":"c:objc(cs)TUICallObserverExtraInfo"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"onCallReceived:callerId:calleeIdList:mediaType:info:"}],"extendedModule":"AtomicXCore","modules":[{"name":"AtomicXCore"}],"externalID":"c:@CM@AtomicXCore@objc(cs)CallListStoreImpl(im)onCallReceived:callerId:calleeIdList:mediaType:info:","title":"onCallReceived(_:callerId:calleeIdList:mediaType:info:)","roleHeading":"Instance Method","symbolKind":"method"},"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallListStoreImpl":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallListStoreImpl","kind":"identifier"}],"navigatorTitle":[{"text":"CallListStoreImpl","kind":"identifier"}],"title":"CallListStoreImpl","abstract":[],"role":"symbol","type":"topic","url":"\/documentation\/atomicxcore\/callliststoreimpl"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"kind":"symbol","abstract":[],"type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallListStoreImpl/onCallReceived(_:callerId:calleeIdList:mediaType:info:)":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onCallReceived"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"callerId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"calleeIdList"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"], ","kind":"text"},{"text":"mediaType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUICallMediaType","kind":"typeIdentifier","preciseIdentifier":"c:@E@TUICallMediaType"},{"text":", ","kind":"text"},{"text":"info","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUICallObserverExtraInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUICallObserverExtraInfo"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"onCallReceived:callerId:calleeIdList:mediaType:info:"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl\/onCallReceived(_:callerId:calleeIdList:mediaType:info:)","url":"\/documentation\/atomicxcore\/callliststoreimpl\/oncallreceived(_:callerid:calleeidlist:mediatype:info:)","abstract":[],"title":"onCallReceived(_:callerId:calleeIdList:mediaType:info:)"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"onCallReceived:callerId:calleeIdList:mediaType:info:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onCallReceived:callerId:calleeIdList:mediaType:info:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onCallReceived:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"callId"},{"kind":"text","text":" "},{"kind":"identifier","text":"callerId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"callerId"},{"kind":"text","text":" "},{"kind":"identifier","text":"calleeIdList:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"calleeIdList"},{"kind":"text","text":" "},{"kind":"identifier","text":"mediaType:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TUICallMediaType","preciseIdentifier":"c:@E@TUICallMediaType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"mediaType"},{"kind":"text","text":" "},{"kind":"identifier","text":"info:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TUICallObserverExtraInfo","preciseIdentifier":"c:objc(cs)TUICallObserverExtraInfo"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"info"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"CallListStoreImpl","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStoreImpl\/title"},{"op":"replace","value":[{"kind":"identifier","text":"CallListStoreImpl"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStoreImpl\/fragments"},{"op":"replace","value":[{"text":"CallListStoreImpl","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStoreImpl\/navigatorTitle"},{"op":"replace","value":"onCallReceived:callerId:calleeIdList:mediaType:info:","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStoreImpl~1onCallReceived(_:callerId:calleeIdList:mediaType:info:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onCallReceived:callerId:calleeIdList:mediaType:info:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStoreImpl~1onCallReceived(_:callerId:calleeIdList:mediaType:info:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}