{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl"]]},"metadata":{"modules":[{"name":"AtomicXCore"}],"title":"onCallBegin(callId:mediaType:info:)","externalID":"c:@CM@AtomicXCore@objc(cs)CallListStoreImpl(im)onCallBegin:mediaType:info:","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onCallBegin","kind":"identifier"},{"text":"(","kind":"text"},{"text":"callId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"mediaType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUICallMediaType","kind":"typeIdentifier","preciseIdentifier":"c:@E@TUICallMediaType"},{"text":", ","kind":"text"},{"text":"info","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUICallObserverExtraInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUICallObserverExtraInfo"},{"text":")","kind":"text"}],"symbolKind":"method","navigatorTitle":[{"text":"onCallBegin:mediaType:info:","kind":"identifier"}],"extendedModule":"AtomicXCore","roleHeading":"Instance Method"},"kind":"symbol","sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"TUICallObserver.onCallBegin(callId:mediaType:info:)"},{"text":".","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/callliststoreimpl\/oncallbegin(callid:mediatype:info:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/atomicxcore\/callliststoreimpl\/oncallbegin(callid:mediatype:info:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onCallBegin","kind":"identifier"},{"text":"(","kind":"text"},{"text":"callId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"mediaType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@TUICallMediaType","text":"TUICallMediaType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"info","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)TUICallObserverExtraInfo","text":"TUICallObserverExtraInfo","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl\/onCallBegin(callId:mediaType:info:)"},"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallListStoreImpl/onCallBegin(callId:mediaType:info:)":{"url":"\/documentation\/atomicxcore\/callliststoreimpl\/oncallbegin(callid:mediatype:info:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onCallBegin"},{"kind":"text","text":"("},{"kind":"externalParam","text":"callId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mediaType"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@TUICallMediaType","kind":"typeIdentifier","text":"TUICallMediaType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)TUICallObserverExtraInfo","kind":"typeIdentifier","text":"TUICallObserverExtraInfo"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"onCallBegin:mediaType:info:"}],"title":"onCallBegin(callId:mediaType:info:)","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl\/onCallBegin(callId:mediaType:info:)","abstract":[]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"url":"\/documentation\/atomicxcore","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","type":"topic","kind":"symbol","abstract":[],"role":"collection"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallListStoreImpl":{"kind":"symbol","type":"topic","title":"CallListStoreImpl","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallListStoreImpl","kind":"identifier"}],"role":"symbol","url":"\/documentation\/atomicxcore\/callliststoreimpl","navigatorTitle":[{"text":"CallListStoreImpl","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onCallBegin:mediaType:info:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onCallBegin:mediaType:info:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"onCallBegin:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"callId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"mediaType:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"TUICallMediaType","kind":"typeIdentifier","preciseIdentifier":"c:@E@TUICallMediaType"},{"text":") ","kind":"text"},{"text":"mediaType","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"info:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"TUICallObserverExtraInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUICallObserverExtraInfo"},{"text":" *) ","kind":"text"},{"text":"info","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStoreImpl~1onCallBegin(callId:mediaType:info:)\/title","value":"onCallBegin:mediaType:info:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStoreImpl~1onCallBegin(callId:mediaType:info:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onCallBegin:mediaType:info:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStoreImpl\/title","value":"CallListStoreImpl"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStoreImpl\/fragments","value":[{"text":"CallListStoreImpl","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStoreImpl\/navigatorTitle","value":[{"text":"CallListStoreImpl","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}