{"topicSections":[{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl\/onCallBegin(callId:mediaType:info:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl\/onCallCancelled(callerId:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl\/onCallEnd(callId:mediaType:reason:userId:totalTime:info:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl\/onCallNotConnected(callId:mediaType:reason:userId:info:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl\/onCallReceived(_:callerId:calleeIdList:mediaType:info:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/atomicxcore\/callliststoreimpl\/tuicallobserver-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/atomicxcore\/callliststoreimpl\/tuicallobserver-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"AtomicXCore"}],"role":"collectionGroup","roleHeading":"API Collection","title":"TUICallObserver Implementations"},"sections":[],"kind":"article","hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl"]]},"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl\/TUICallObserver-Implementations","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallListStoreImpl/onCallEnd(callId:mediaType:reason:userId:totalTime:info:)":{"url":"\/documentation\/atomicxcore\/callliststoreimpl\/oncallend(callid:mediatype:reason:userid:totaltime:info:)","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl\/onCallEnd(callId:mediaType:reason:userId:totalTime:info:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onCallEnd","kind":"identifier"},{"text":"(","kind":"text"},{"text":"callId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"mediaType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@TUICallMediaType","text":"TUICallMediaType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"reason","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@TUICallEndReason","text":"TUICallEndReason","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"userId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"totalTime","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"info","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)TUICallObserverExtraInfo","text":"TUICallObserverExtraInfo","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","title":"onCallEnd(callId:mediaType:reason:userId:totalTime:info:)","type":"topic","kind":"symbol","navigatorTitle":[{"text":"onCallEnd:mediaType:reason:userId:totalTime:info:","kind":"identifier"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallListStoreImpl/onCallReceived(_:callerId:calleeIdList:mediaType:info:)":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onCallReceived"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"callerId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"calleeIdList"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"], ","kind":"text"},{"text":"mediaType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUICallMediaType","kind":"typeIdentifier","preciseIdentifier":"c:@E@TUICallMediaType"},{"text":", ","kind":"text"},{"text":"info","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUICallObserverExtraInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUICallObserverExtraInfo"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"onCallReceived:callerId:calleeIdList:mediaType:info:"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl\/onCallReceived(_:callerId:calleeIdList:mediaType:info:)","url":"\/documentation\/atomicxcore\/callliststoreimpl\/oncallreceived(_:callerid:calleeidlist:mediatype:info:)","abstract":[],"title":"onCallReceived(_:callerId:calleeIdList:mediaType:info:)"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallListStoreImpl/onCallNotConnected(callId:mediaType:reason:userId:info:)":{"title":"onCallNotConnected(callId:mediaType:reason:userId:info:)","role":"symbol","abstract":[],"url":"\/documentation\/atomicxcore\/callliststoreimpl\/oncallnotconnected(callid:mediatype:reason:userid:info:)","navigatorTitle":[{"text":"onCallNotConnected:mediaType:reason:userId:info:","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl\/onCallNotConnected(callId:mediaType:reason:userId:info:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onCallNotConnected","kind":"identifier"},{"text":"(","kind":"text"},{"text":"callId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"mediaType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUICallMediaType","preciseIdentifier":"c:@E@TUICallMediaType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"reason","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUICallEndReason","preciseIdentifier":"c:@E@TUICallEndReason","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"userId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"info","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUICallObserverExtraInfo","preciseIdentifier":"c:objc(cs)TUICallObserverExtraInfo","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallListStoreImpl/onCallBegin(callId:mediaType:info:)":{"title":"onCallBegin(callId:mediaType:info:)","role":"symbol","abstract":[],"url":"\/documentation\/atomicxcore\/callliststoreimpl\/oncallbegin(callid:mediatype:info:)","navigatorTitle":[{"kind":"identifier","text":"onCallBegin:mediaType:info:"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl\/onCallBegin(callId:mediaType:info:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onCallBegin"},{"kind":"text","text":"("},{"kind":"externalParam","text":"callId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mediaType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@TUICallMediaType","text":"TUICallMediaType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUICallObserverExtraInfo","text":"TUICallObserverExtraInfo"},{"kind":"text","text":")"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallListStoreImpl":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallListStoreImpl","kind":"identifier"}],"navigatorTitle":[{"text":"CallListStoreImpl","kind":"identifier"}],"title":"CallListStoreImpl","abstract":[],"role":"symbol","type":"topic","url":"\/documentation\/atomicxcore\/callliststoreimpl"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"kind":"symbol","abstract":[],"type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallListStoreImpl/onCallCancelled(callerId:)":{"type":"topic","url":"\/documentation\/atomicxcore\/callliststoreimpl\/oncallcancelled(callerid:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onCallCancelled"},{"kind":"text","text":"("},{"kind":"externalParam","text":"callerId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"onCallCancelled:"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl\/onCallCancelled(callerId:)","role":"symbol","abstract":[],"title":"onCallCancelled(callerId:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl\/onCallBegin(callId:mediaType:info:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl\/onCallCancelled(callerId:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl\/onCallEnd(callId:mediaType:reason:userId:totalTime:info:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl\/onCallNotConnected(callId:mediaType:reason:userId:info:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl\/onCallReceived(_:callerId:calleeIdList:mediaType:info:)"],"generated":true,"anchor":"Instance-Methods"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStoreImpl~1onCallEnd(callId:mediaType:reason:userId:totalTime:info:)\/title","op":"replace","value":"onCallEnd:mediaType:reason:userId:totalTime:info:"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStoreImpl~1onCallEnd(callId:mediaType:reason:userId:totalTime:info:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onCallEnd:mediaType:reason:userId:totalTime:info:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStoreImpl~1onCallReceived(_:callerId:calleeIdList:mediaType:info:)\/title","op":"replace","value":"onCallReceived:callerId:calleeIdList:mediaType:info:"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStoreImpl~1onCallReceived(_:callerId:calleeIdList:mediaType:info:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onCallReceived:callerId:calleeIdList:mediaType:info:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStoreImpl~1onCallNotConnected(callId:mediaType:reason:userId:info:)\/title","op":"replace","value":"onCallNotConnected:mediaType:reason:userId:info:"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStoreImpl~1onCallNotConnected(callId:mediaType:reason:userId:info:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onCallNotConnected:mediaType:reason:userId:info:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStoreImpl~1onCallBegin(callId:mediaType:info:)\/title","op":"replace","value":"onCallBegin:mediaType:info:"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStoreImpl~1onCallBegin(callId:mediaType:info:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onCallBegin:mediaType:info:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStoreImpl\/title","op":"replace","value":"CallListStoreImpl"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStoreImpl\/fragments","op":"replace","value":[{"text":"CallListStoreImpl","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStoreImpl\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"CallListStoreImpl"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStoreImpl~1onCallCancelled(callerId:)\/title","op":"replace","value":"onCallCancelled:"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStoreImpl~1onCallCancelled(callerId:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onCallCancelled:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}