{"metadata":{"modules":[{"name":"AtomicXCore"}],"role":"symbol","symbolKind":"method","externalID":"s:11AtomicXCore15ParticipantViewC15setRenderParams6paramsySo08TUIVideofG0C_tF","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setRenderParams","kind":"identifier"},{"text":"(","kind":"text"},{"text":"params","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUIVideoRenderParams","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIVideoRenderParams"},{"text":")","kind":"text"}],"title":"setRenderParams(params:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/participantview\/setrenderparams(params:)"]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ParticipantView"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ParticipantView\/setRenderParams(params:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setRenderParams","kind":"identifier"},{"text":"(","kind":"text"},{"text":"params","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUIVideoRenderParams","preciseIdentifier":"c:objc(cs)TUIVideoRenderParams","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"abstract":[],"title":"AtomicXCore","type":"topic","kind":"symbol","url":"\/documentation\/atomicxcore","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","role":"collection"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ParticipantView":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ParticipantView","kind":"symbol","title":"ParticipantView","type":"topic","abstract":[],"url":"\/documentation\/atomicxcore\/participantview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ParticipantView"}],"navigatorTitle":[{"kind":"identifier","text":"ParticipantView"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ParticipantView/setRenderParams(params:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ParticipantView\/setRenderParams(params:)","abstract":[],"kind":"symbol","type":"topic","title":"setRenderParams(params:)","url":"\/documentation\/atomicxcore\/participantview\/setrenderparams(params:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setRenderParams","kind":"identifier"},{"text":"(","kind":"text"},{"text":"params","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUIVideoRenderParams","preciseIdentifier":"c:objc(cs)TUIVideoRenderParams","kind":"typeIdentifier"},{"text":")","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ParticipantView\/title","value":"ParticipantView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ParticipantView\/fragments","value":[{"kind":"identifier","text":"ParticipantView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ParticipantView\/navigatorTitle","value":[{"text":"ParticipantView","kind":"identifier"}]}]}]}