{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CoHostUser"]]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connectionUser","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)TUIConnectionUser","text":"TUIConnectionUser","kind":"typeIdentifier"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CoHostUser\/connectionUser"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/cohostuser\/connectionuser"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/atomicxcore\/cohostuser\/connectionuser"]}],"metadata":{"externalID":"c:@M@AtomicXCore@objc(cs)CoHostUser(py)connectionUser","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connectionUser","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)TUIConnectionUser","text":"TUIConnectionUser","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"connectionUser","kind":"identifier"}],"symbolKind":"property","platforms":[{"unavailable":false,"deprecated":true,"beta":false}],"modules":[{"name":"AtomicXCore"}],"title":"connectionUser","role":"symbol","roleHeading":"Instance Property"},"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"kind":"symbol","abstract":[],"type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CoHostUser/connectionUser":{"role":"symbol","deprecated":true,"title":"connectionUser","navigatorTitle":[{"text":"connectionUser","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connectionUser","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)TUIConnectionUser","text":"TUIConnectionUser","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CoHostUser\/connectionUser","abstract":[],"kind":"symbol","url":"\/documentation\/atomicxcore\/cohostuser\/connectionuser"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CoHostUser":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoHostUser","kind":"identifier"}],"title":"CoHostUser","type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CoHostUser","abstract":[],"navigatorTitle":[{"text":"CoHostUser","kind":"identifier"}],"deprecated":true,"role":"symbol","kind":"symbol","url":"\/documentation\/atomicxcore\/cohostuser"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[{"unavailable":false,"deprecated":true,"beta":false}]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"connectionUser"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"connectionUser"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)TUIConnectionUser","text":"TUIConnectionUser","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"connectionUser","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CoHostUser~1connectionUser\/title","value":"connectionUser"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CoHostUser~1connectionUser\/fragments","value":[{"kind":"identifier","text":"connectionUser"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CoHostUser\/title","value":"CoHostUser"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CoHostUser\/fragments","value":[{"text":"CoHostUser","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CoHostUser\/navigatorTitle","value":[{"kind":"identifier","text":"CoHostUser"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}