{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CoHostUser"]]},"sections":[],"variants":[{"paths":["\/documentation\/atomicxcore\/cohostuser\/hasaudiostream"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/atomicxcore\/cohostuser\/hasaudiostream"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"platforms":[{"unavailable":false,"deprecated":true,"beta":false}],"title":"hasAudioStream","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasAudioStream"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"hasAudioStream"}],"modules":[{"name":"AtomicXCore"}],"externalID":"c:@M@AtomicXCore@objc(cs)CoHostUser(py)hasAudioStream","symbolKind":"property","role":"symbol"},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CoHostUser\/hasAudioStream","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hasAudioStream","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"url":"\/documentation\/atomicxcore","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","type":"topic","kind":"symbol","abstract":[],"role":"collection"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CoHostUser":{"type":"topic","title":"CoHostUser","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoHostUser"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CoHostUser"}],"deprecated":true,"abstract":[],"url":"\/documentation\/atomicxcore\/cohostuser","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CoHostUser","kind":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CoHostUser/hasAudioStream":{"kind":"symbol","type":"topic","abstract":[],"role":"symbol","navigatorTitle":[{"text":"hasAudioStream","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CoHostUser\/hasAudioStream","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hasAudioStream","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"deprecated":true,"url":"\/documentation\/atomicxcore\/cohostuser\/hasaudiostream","title":"hasAudioStream"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":[{"deprecated":true,"unavailable":false,"beta":false}],"path":"\/metadata\/platforms","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"hasAudioStream","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"hasAudioStream"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasAudioStream"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"CoHostUser","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CoHostUser\/title","op":"replace"},{"value":[{"kind":"identifier","text":"CoHostUser"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CoHostUser\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"CoHostUser"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CoHostUser\/navigatorTitle","op":"replace"},{"value":"hasAudioStream","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CoHostUser~1hasAudioStream\/title","op":"replace"},{"value":[{"text":"hasAudioStream","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CoHostUser~1hasAudioStream\/fragments","op":"replace"}]}]}