{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/cohostuser\/hasvideostream"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/atomicxcore\/cohostuser\/hasvideostream"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CoHostUser"]]},"metadata":{"roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"AtomicXCore"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasVideoStream"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"role":"symbol","platforms":[{"unavailable":false,"deprecated":true,"beta":false}],"navigatorTitle":[{"kind":"identifier","text":"hasVideoStream"}],"title":"hasVideoStream","externalID":"c:@M@AtomicXCore@objc(cs)CoHostUser(py)hasVideoStream"},"kind":"symbol","sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CoHostUser\/hasVideoStream","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hasVideoStream","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"kind":"symbol","abstract":[],"type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CoHostUser/hasVideoStream":{"abstract":[],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CoHostUser\/hasVideoStream","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hasVideoStream","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"deprecated":true,"navigatorTitle":[{"text":"hasVideoStream","kind":"identifier"}],"title":"hasVideoStream","url":"\/documentation\/atomicxcore\/cohostuser\/hasvideostream","type":"topic"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CoHostUser":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoHostUser","kind":"identifier"}],"title":"CoHostUser","type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CoHostUser","abstract":[],"navigatorTitle":[{"text":"CoHostUser","kind":"identifier"}],"deprecated":true,"role":"symbol","kind":"symbol","url":"\/documentation\/atomicxcore\/cohostuser"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"replace","value":[{"deprecated":true,"unavailable":false,"beta":false}]},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"hasVideoStream"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"hasVideoStream","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasVideoStream"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CoHostUser~1hasVideoStream\/title","op":"replace","value":"hasVideoStream"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CoHostUser~1hasVideoStream\/fragments","op":"replace","value":[{"text":"hasVideoStream","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CoHostUser\/title","op":"replace","value":"CoHostUser"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CoHostUser\/fragments","op":"replace","value":[{"kind":"identifier","text":"CoHostUser"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CoHostUser\/navigatorTitle","op":"replace","value":[{"text":"CoHostUser","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}