{"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CoHostUser\/init","interfaceLanguage":"occ"},"metadata":{"externalID":"c:@M@AtomicXCore@objc(cs)CoHostUser(im)init","navigatorTitle":[{"text":"init","kind":"identifier"}],"symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"platforms":[{"unavailable":false,"beta":false,"deprecated":true}],"title":"init","modules":[{"name":"AtomicXCore"}],"role":"symbol"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CoHostUser"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/atomicxcore\/cohostuser\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CoHostUser":{"url":"\/documentation\/atomicxcore\/cohostuser","deprecated":true,"kind":"symbol","title":"CoHostUser","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoHostUser","kind":"identifier"}],"navigatorTitle":[{"text":"CoHostUser","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CoHostUser","abstract":[]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CoHostUser/init":{"kind":"symbol","url":"\/documentation\/atomicxcore\/cohostuser\/init","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CoHostUser\/init","type":"topic","title":"init","role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"abstract":[],"title":"AtomicXCore","type":"topic","kind":"symbol","url":"\/documentation\/atomicxcore","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CoHostUser\/title","value":"CoHostUser"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CoHostUser\/fragments","value":[{"kind":"identifier","text":"CoHostUser"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CoHostUser\/navigatorTitle","value":[{"kind":"identifier","text":"CoHostUser"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}