{"variants":[{"paths":["\/documentation\/atomicxcore\/groupsettingstore\/addgroupmember(useridlist:completion:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"addGroupMember","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userIDList","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","text":"CompletionClosure","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CompletionClosure"},{"kind":"text","text":"?)"}]}]}],"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore\/addGroupMember(userIDList:completion:)","interfaceLanguage":"swift"},"metadata":{"title":"addGroupMember(userIDList:completion:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addGroupMember","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userIDList","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CompletionClosure","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"symbolKind":"method","modules":[{"name":"AtomicXCore"}],"roleHeading":"Instance Method","externalID":"s:11AtomicXCore17GroupSettingStoreC03addC6Member10userIDList10completionySaySSG_ys6ResultOyytAA9ErrorInfoVGcSgtF"},"kind":"symbol","references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CompletionClosure":{"url":"\/documentation\/atomicxcore\/completionclosure","type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CompletionClosure","kind":"symbol","navigatorTitle":[{"text":"CompletionClosure","kind":"identifier"}],"abstract":[{"text":"完成回调闭包类型","type":"text"},{"text":" ","type":"text"},{"text":"用于异步操作的结果回调，成功返回 Void，失败返回 ErrorInfo","type":"text"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CompletionClosure","kind":"identifier"}],"role":"symbol","title":"CompletionClosure"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/GroupSettingStore/addGroupMember(userIDList:completion:)":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore\/addGroupMember(userIDList:completion:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addGroupMember"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userIDList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","text":"CompletionClosure"},{"kind":"text","text":"?)"}],"title":"addGroupMember(userIDList:completion:)","abstract":[],"role":"symbol","url":"\/documentation\/atomicxcore\/groupsettingstore\/addgroupmember(useridlist:completion:)"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"abstract":[],"title":"AtomicXCore","type":"topic","kind":"symbol","url":"\/documentation\/atomicxcore","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","role":"collection"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/GroupSettingStore":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupSettingStore"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupSettingStore"}],"title":"GroupSettingStore","abstract":[],"role":"symbol","url":"\/documentation\/atomicxcore\/groupsettingstore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"GroupSettingStore","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1GroupSettingStore\/title"},{"value":[{"text":"GroupSettingStore","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1GroupSettingStore\/fragments"},{"value":[{"text":"GroupSettingStore","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1GroupSettingStore\/navigatorTitle"}]}]}