{"metadata":{"symbolKind":"method","title":"fetchMoreGroupMemberList(completion:)","modules":[{"name":"AtomicXCore"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"fetchMoreGroupMemberList","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","text":"CompletionClosure"},{"text":"?)","kind":"text"}],"externalID":"s:11AtomicXCore17GroupSettingStoreC09fetchMoreC10MemberList10completionyys6ResultOyytAA9ErrorInfoVGcSg_tF","role":"symbol","roleHeading":"Instance Method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore\/fetchMoreGroupMemberList(completion:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"fetchMoreGroupMemberList","kind":"identifier"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CompletionClosure","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","kind":"typeIdentifier","text":"CompletionClosure"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/groupsettingstore\/fetchmoregroupmemberlist(completion:)"]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","title":"AtomicXCore","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","abstract":[],"url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/GroupSettingStore/fetchMoreGroupMemberList(completion:)":{"title":"fetchMoreGroupMemberList(completion:)","url":"\/documentation\/atomicxcore\/groupsettingstore\/fetchmoregroupmemberlist(completion:)","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore\/fetchMoreGroupMemberList(completion:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fetchMoreGroupMemberList"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"text":"CompletionClosure","kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea"},{"kind":"text","text":"?)"}],"kind":"symbol","abstract":[],"type":"topic","role":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CompletionClosure":{"url":"\/documentation\/atomicxcore\/completionclosure","kind":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"CompletionClosure"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CompletionClosure","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CompletionClosure","title":"CompletionClosure","role":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/GroupSettingStore":{"kind":"symbol","abstract":[],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GroupSettingStore","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore","navigatorTitle":[{"text":"GroupSettingStore","kind":"identifier"}],"role":"symbol","url":"\/documentation\/atomicxcore\/groupsettingstore","title":"GroupSettingStore"}},"variantOverrides":[{"patch":[{"op":"replace","value":"GroupSettingStore","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1GroupSettingStore\/title"},{"value":[{"text":"GroupSettingStore","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1GroupSettingStore\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1GroupSettingStore\/navigatorTitle","value":[{"kind":"identifier","text":"GroupSettingStore"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}