{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"modules":[{"name":"AtomicXCore"}],"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setGroupMemberRole"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"role"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore15GroupMemberRoleO","text":"GroupMemberRole"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","text":"CompletionClosure"},{"kind":"text","text":"?)"}],"role":"symbol","roleHeading":"Instance Method","title":"setGroupMemberRole(userID:role:completion:)","externalID":"s:11AtomicXCore17GroupSettingStoreC03setC10MemberRole6userID4role10completionySS_AA0cgH0Oys6ResultOyytAA9ErrorInfoVGcSgtF"},"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore\/setGroupMemberRole(userID:role:completion:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setGroupMemberRole","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userID","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"role","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GroupMemberRole","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupMemberRole","preciseIdentifier":"s:11AtomicXCore15GroupMemberRoleO","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CompletionClosure","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CompletionClosure","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/groupsettingstore\/setgroupmemberrole(userid:role:completion:)"]}],"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/GroupSettingStore/setGroupMemberRole(userID:role:completion:)":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore\/setGroupMemberRole(userID:role:completion:)","type":"topic","role":"symbol","title":"setGroupMemberRole(userID:role:completion:)","url":"\/documentation\/atomicxcore\/groupsettingstore\/setgroupmemberrole(userid:role:completion:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setGroupMemberRole"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userID"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"role"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11AtomicXCore15GroupMemberRoleO","kind":"typeIdentifier","text":"GroupMemberRole"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","kind":"typeIdentifier","text":"CompletionClosure"},{"kind":"text","text":"?)"}],"kind":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/GroupSettingStore":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupSettingStore"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore","title":"GroupSettingStore","type":"topic","kind":"symbol","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GroupSettingStore"}],"url":"\/documentation\/atomicxcore\/groupsettingstore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"kind":"symbol","abstract":[],"type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/GroupMemberRole":{"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupMemberRole"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupMemberRole","type":"topic","url":"\/documentation\/atomicxcore\/groupmemberrole","title":"GroupMemberRole","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GroupMemberRole"}],"abstract":[]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CompletionClosure":{"url":"\/documentation\/atomicxcore\/completionclosure","abstract":[{"type":"text","text":"完成回调闭包类型"},{"type":"text","text":" "},{"type":"text","text":"用于异步操作的结果回调，成功返回 Void，失败返回 ErrorInfo"}],"type":"topic","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CompletionClosure","kind":"identifier"}],"title":"CompletionClosure","role":"symbol","navigatorTitle":[{"text":"CompletionClosure","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CompletionClosure"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1GroupSettingStore\/title","op":"replace","value":"GroupSettingStore"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1GroupSettingStore\/fragments","op":"replace","value":[{"kind":"identifier","text":"GroupSettingStore"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1GroupSettingStore\/navigatorTitle","op":"replace","value":[{"text":"GroupSettingStore","kind":"identifier"}]}]}]}