{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/groupsettingstore\/setselfgroupnamecard(namecard:completion:)"]}],"sections":[],"metadata":{"role":"symbol","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setSelfGroupNameCard"},{"kind":"text","text":"("},{"kind":"externalParam","text":"nameCard"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","text":"CompletionClosure"},{"kind":"text","text":"?)"}],"roleHeading":"Instance Method","modules":[{"name":"AtomicXCore"}],"title":"setSelfGroupNameCard(nameCard:completion:)","externalID":"s:11AtomicXCore17GroupSettingStoreC07setSelfC8NameCard04nameI010completionySSSg_ys6ResultOyytAA9ErrorInfoVGcSgtF"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setSelfGroupNameCard","kind":"identifier"},{"text":"(","kind":"text"},{"text":"nameCard","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CompletionClosure","text":"CompletionClosure","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore\/setSelfGroupNameCard(nameCard:completion:)"},"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"url":"\/documentation\/atomicxcore","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","type":"topic","kind":"symbol","abstract":[],"role":"collection"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/GroupSettingStore/setSelfGroupNameCard(nameCard:completion:)":{"title":"setSelfGroupNameCard(nameCard:completion:)","url":"\/documentation\/atomicxcore\/groupsettingstore\/setselfgroupnamecard(namecard:completion:)","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore\/setSelfGroupNameCard(nameCard:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setSelfGroupNameCard"},{"kind":"text","text":"("},{"kind":"externalParam","text":"nameCard"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CompletionClosure","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea"},{"kind":"text","text":"?)"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/GroupSettingStore":{"type":"topic","title":"GroupSettingStore","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupSettingStore"}],"url":"\/documentation\/atomicxcore\/groupsettingstore","navigatorTitle":[{"text":"GroupSettingStore","kind":"identifier"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CompletionClosure":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"CompletionClosure"}],"abstract":[{"type":"text","text":"完成回调闭包类型"},{"type":"text","text":" "},{"type":"text","text":"用于异步操作的结果回调，成功返回 Void，失败返回 ErrorInfo"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CompletionClosure"}],"title":"CompletionClosure","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CompletionClosure","url":"\/documentation\/atomicxcore\/completionclosure"}},"variantOverrides":[{"patch":[{"op":"replace","value":"GroupSettingStore","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1GroupSettingStore\/title"},{"op":"replace","value":[{"kind":"identifier","text":"GroupSettingStore"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1GroupSettingStore\/fragments"},{"op":"replace","value":[{"text":"GroupSettingStore","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1GroupSettingStore\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}