{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"state"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/StatePublisher","preciseIdentifier":"s:11AtomicXCore14StatePublisherC","kind":"typeIdentifier","text":"StatePublisher"},{"kind":"text","text":"<"},{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingState","preciseIdentifier":"s:11AtomicXCore17GroupSettingStateV","kind":"typeIdentifier","text":"GroupSettingState"},{"kind":"text","text":">"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"title":"state","symbolKind":"property","modules":[{"name":"AtomicXCore"}],"externalID":"s:11AtomicXCore17GroupSettingStoreC5stateAA14StatePublisherCyAA0cdG0VGvp","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"state","kind":"identifier"},{"text":": ","kind":"text"},{"text":"StatePublisher","preciseIdentifier":"s:11AtomicXCore14StatePublisherC","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"GroupSettingState","preciseIdentifier":"s:11AtomicXCore17GroupSettingStateV","kind":"typeIdentifier"},{"text":">","kind":"text"}],"roleHeading":"Instance Property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/groupsettingstore\/state"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore\/state"},"kind":"symbol","references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/GroupSettingState":{"type":"topic","navigatorTitle":[{"text":"GroupSettingState","kind":"identifier"}],"abstract":[],"title":"GroupSettingState","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingState","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GroupSettingState","kind":"identifier"}],"url":"\/documentation\/atomicxcore\/groupsettingstate","role":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"url":"\/documentation\/atomicxcore","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","type":"topic","kind":"symbol","abstract":[],"role":"collection"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/GroupSettingStore/state":{"url":"\/documentation\/atomicxcore\/groupsettingstore\/state","abstract":[],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore\/state","kind":"symbol","type":"topic","title":"state","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"state","kind":"identifier"},{"text":": ","kind":"text"},{"text":"StatePublisher","kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore14StatePublisherC"},{"text":"<","kind":"text"},{"text":"GroupSettingState","kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore17GroupSettingStateV"},{"text":">","kind":"text"}],"role":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/GroupSettingStore":{"type":"topic","title":"GroupSettingStore","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupSettingStore"}],"url":"\/documentation\/atomicxcore\/groupsettingstore","navigatorTitle":[{"text":"GroupSettingStore","kind":"identifier"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/StatePublisher":{"navigatorTitle":[{"text":"StatePublisher","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/StatePublisher","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StatePublisher","kind":"identifier"}],"title":"StatePublisher","role":"symbol","abstract":[{"type":"text","text":"状态发布器"},{"type":"text","text":" "},{"type":"text","text":"基于 Combine 框架的响应式状态管理容器，支持状态订阅和更新"}],"url":"\/documentation\/atomicxcore\/statepublisher","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1GroupSettingStore\/title","value":"GroupSettingStore","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1GroupSettingStore\/fragments","value":[{"kind":"identifier","text":"GroupSettingStore"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1GroupSettingStore\/navigatorTitle","value":[{"kind":"identifier","text":"GroupSettingStore"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}