{"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","metadata":{"externalID":"c:@CM@AtomicXCore@objc(cs)CallParticipantStoreImpl(im)onCallEnd:mediaType:reason:userId:totalTime:info:","title":"onCallEnd(callId:mediaType:reason:userId:totalTime:info:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onCallEnd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"callId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mediaType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TUICallMediaType","preciseIdentifier":"c:@E@TUICallMediaType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TUICallEndReason","preciseIdentifier":"c:@E@TUICallEndReason"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"totalTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TUICallObserverExtraInfo","preciseIdentifier":"c:objc(cs)TUICallObserverExtraInfo"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"onCallEnd:mediaType:reason:userId:totalTime:info:","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Method","extendedModule":"AtomicXCore","symbolKind":"method","modules":[{"name":"AtomicXCore"}]},"variants":[{"paths":["\/documentation\/atomicxcore\/callparticipantstoreimpl\/oncallend(callid:mediatype:reason:userid:totaltime:info:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/atomicxcore\/callparticipantstoreimpl\/oncallend(callid:mediatype:reason:userid:totaltime:info:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"TUICallObserver.onCallEnd(callId:mediaType:reason:userId:totalTime:info:)","type":"codeVoice"},{"type":"text","text":"."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallParticipantStoreImpl\/onCallEnd(callId:mediaType:reason:userId:totalTime:info:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onCallEnd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"callId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mediaType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TUICallMediaType","preciseIdentifier":"c:@E@TUICallMediaType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@TUICallEndReason","kind":"typeIdentifier","text":"TUICallEndReason"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"totalTime"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"text":"info","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUICallObserverExtraInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUICallObserverExtraInfo"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallParticipantStoreImpl"]]},"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallParticipantStoreImpl":{"kind":"symbol","url":"\/documentation\/atomicxcore\/callparticipantstoreimpl","navigatorTitle":[{"text":"CallParticipantStoreImpl","kind":"identifier"}],"abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallParticipantStoreImpl","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallParticipantStoreImpl","type":"topic","title":"CallParticipantStoreImpl"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallParticipantStoreImpl/onCallEnd(callId:mediaType:reason:userId:totalTime:info:)":{"kind":"symbol","url":"\/documentation\/atomicxcore\/callparticipantstoreimpl\/oncallend(callid:mediatype:reason:userid:totaltime:info:)","navigatorTitle":[{"text":"onCallEnd:mediaType:reason:userId:totalTime:info:","kind":"identifier"}],"abstract":[],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onCallEnd","kind":"identifier"},{"text":"(","kind":"text"},{"text":"callId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"mediaType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUICallMediaType","kind":"typeIdentifier","preciseIdentifier":"c:@E@TUICallMediaType"},{"text":", ","kind":"text"},{"text":"reason","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUICallEndReason","kind":"typeIdentifier","preciseIdentifier":"c:@E@TUICallEndReason"},{"text":", ","kind":"text"},{"text":"userId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"totalTime","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"text":"info","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUICallObserverExtraInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUICallObserverExtraInfo"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallParticipantStoreImpl\/onCallEnd(callId:mediaType:reason:userId:totalTime:info:)","type":"topic","title":"onCallEnd(callId:mediaType:reason:userId:totalTime:info:)"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"kind":"symbol","abstract":[],"type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","url":"\/documentation\/atomicxcore"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onCallEnd:mediaType:reason:userId:totalTime:info:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onCallEnd:mediaType:reason:userId:totalTime:info:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"onCallEnd:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"callId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"mediaType:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"TUICallMediaType","kind":"typeIdentifier","preciseIdentifier":"c:@E@TUICallMediaType"},{"text":") ","kind":"text"},{"text":"mediaType","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"reason:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"TUICallEndReason","kind":"typeIdentifier","preciseIdentifier":"c:@E@TUICallEndReason"},{"text":") ","kind":"text"},{"text":"reason","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"userId:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"userId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"totalTime:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"float","kind":"typeIdentifier","preciseIdentifier":"c:f"},{"text":") ","kind":"text"},{"text":"totalTime","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"info:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"TUICallObserverExtraInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUICallObserverExtraInfo"},{"text":" *) ","kind":"text"},{"text":"info","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallParticipantStoreImpl\/title","value":"CallParticipantStoreImpl"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallParticipantStoreImpl\/fragments","op":"replace","value":[{"kind":"identifier","text":"CallParticipantStoreImpl"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallParticipantStoreImpl\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"CallParticipantStoreImpl"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallParticipantStoreImpl~1onCallEnd(callId:mediaType:reason:userId:totalTime:info:)\/title","op":"replace","value":"onCallEnd:mediaType:reason:userId:totalTime:info:"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallParticipantStoreImpl~1onCallEnd(callId:mediaType:reason:userId:totalTime:info:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onCallEnd:mediaType:reason:userId:totalTime:info:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}