{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onCallReceived"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"callId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"callerId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"calleeIdList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"mediaType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@TUICallMediaType","text":"TUICallMediaType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUICallObserverExtraInfo","text":"TUICallObserverExtraInfo"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"metadata":{"role":"symbol","symbolKind":"method","title":"onCallReceived(_:callerId:calleeIdList:mediaType:info:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onCallReceived","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"callerId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"calleeIdList","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"mediaType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUICallMediaType","preciseIdentifier":"c:@E@TUICallMediaType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"info","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUICallObserverExtraInfo","preciseIdentifier":"c:objc(cs)TUICallObserverExtraInfo","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","extendedModule":"AtomicXCore","modules":[{"name":"AtomicXCore"}],"navigatorTitle":[{"text":"onCallReceived:callerId:calleeIdList:mediaType:info:","kind":"identifier"}],"externalID":"c:@CM@AtomicXCore@objc(cs)CallParticipantStoreImpl(im)onCallReceived:callerId:calleeIdList:mediaType:info:"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/callparticipantstoreimpl\/oncallreceived(_:callerid:calleeidlist:mediatype:info:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/atomicxcore\/callparticipantstoreimpl\/oncallreceived(_:callerid:calleeidlist:mediatype:info:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallParticipantStoreImpl"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallParticipantStoreImpl\/onCallReceived(_:callerId:calleeIdList:mediaType:info:)","interfaceLanguage":"swift"},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"TUICallObserver.onCallReceived(_:callerId:calleeIdList:mediaType:info:)"},{"text":".","type":"text"}],"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallParticipantStoreImpl":{"kind":"symbol","url":"\/documentation\/atomicxcore\/callparticipantstoreimpl","navigatorTitle":[{"text":"CallParticipantStoreImpl","kind":"identifier"}],"abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallParticipantStoreImpl","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallParticipantStoreImpl","type":"topic","title":"CallParticipantStoreImpl"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"kind":"symbol","abstract":[],"type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallParticipantStoreImpl/onCallReceived(_:callerId:calleeIdList:mediaType:info:)":{"abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"onCallReceived:callerId:calleeIdList:mediaType:info:"}],"title":"onCallReceived(_:callerId:calleeIdList:mediaType:info:)","url":"\/documentation\/atomicxcore\/callparticipantstoreimpl\/oncallreceived(_:callerid:calleeidlist:mediatype:info:)","type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallParticipantStoreImpl\/onCallReceived(_:callerId:calleeIdList:mediaType:info:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onCallReceived"},{"kind":"text","text":"("},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"callerId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"calleeIdList","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"mediaType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUICallMediaType","preciseIdentifier":"c:@E@TUICallMediaType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TUICallObserverExtraInfo","preciseIdentifier":"c:objc(cs)TUICallObserverExtraInfo"},{"kind":"text","text":")"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"onCallReceived:callerId:calleeIdList:mediaType:info:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onCallReceived:callerId:calleeIdList:mediaType:info:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"onCallReceived:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"callId"},{"kind":"text","text":" "},{"kind":"identifier","text":"callerId:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"callerId"},{"kind":"text","text":" "},{"kind":"identifier","text":"calleeIdList:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<NSString *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"calleeIdList"},{"kind":"text","text":" "},{"kind":"identifier","text":"mediaType:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@TUICallMediaType","kind":"typeIdentifier","text":"TUICallMediaType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"mediaType"},{"kind":"text","text":" "},{"kind":"identifier","text":"info:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)TUICallObserverExtraInfo","kind":"typeIdentifier","text":"TUICallObserverExtraInfo"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"info"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"CallParticipantStoreImpl","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallParticipantStoreImpl\/title"},{"value":[{"text":"CallParticipantStoreImpl","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallParticipantStoreImpl\/fragments"},{"value":[{"kind":"identifier","text":"CallParticipantStoreImpl"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallParticipantStoreImpl\/navigatorTitle"},{"value":"onCallReceived:callerId:calleeIdList:mediaType:info:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallParticipantStoreImpl~1onCallReceived(_:callerId:calleeIdList:mediaType:info:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"onCallReceived:callerId:calleeIdList:mediaType:info:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallParticipantStoreImpl~1onCallReceived(_:callerId:calleeIdList:mediaType:info:)\/fragments"}]}]}