{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallParticipantStoreImpl"]]},"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallParticipantStoreImpl\/onCallCancelled(callerId:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onCallCancelled","kind":"identifier"},{"text":"(","kind":"text"},{"text":"callerId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/callparticipantstoreimpl\/oncallcancelled(callerid:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/atomicxcore\/callparticipantstoreimpl\/oncallcancelled(callerid:)"]}],"sections":[],"metadata":{"symbolKind":"method","externalID":"c:@CM@AtomicXCore@objc(cs)CallParticipantStoreImpl(im)onCallCancelled:","modules":[{"name":"AtomicXCore"}],"navigatorTitle":[{"text":"onCallCancelled:","kind":"identifier"}],"role":"symbol","title":"onCallCancelled(callerId:)","extendedModule":"AtomicXCore","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onCallCancelled","kind":"identifier"},{"text":"(","kind":"text"},{"text":"callerId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"TUICallObserver.onCallCancelled(callerId:)"},{"type":"text","text":"."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallParticipantStoreImpl/onCallCancelled(callerId:)":{"type":"topic","role":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onCallCancelled","kind":"identifier"},{"text":"(","kind":"text"},{"text":"callerId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"onCallCancelled:","kind":"identifier"}],"url":"\/documentation\/atomicxcore\/callparticipantstoreimpl\/oncallcancelled(callerid:)","title":"onCallCancelled(callerId:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallParticipantStoreImpl\/onCallCancelled(callerId:)"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"url":"\/documentation\/atomicxcore","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","type":"topic","kind":"symbol","abstract":[],"role":"collection"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallParticipantStoreImpl":{"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallParticipantStoreImpl","kind":"identifier"}],"type":"topic","title":"CallParticipantStoreImpl","kind":"symbol","url":"\/documentation\/atomicxcore\/callparticipantstoreimpl","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallParticipantStoreImpl","role":"symbol","navigatorTitle":[{"text":"CallParticipantStoreImpl","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"onCallCancelled:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"onCallCancelled:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"onCallCancelled:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"callerId"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"onCallCancelled:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallParticipantStoreImpl~1onCallCancelled(callerId:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onCallCancelled:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallParticipantStoreImpl~1onCallCancelled(callerId:)\/fragments"},{"value":"CallParticipantStoreImpl","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallParticipantStoreImpl\/title"},{"value":[{"kind":"identifier","text":"CallParticipantStoreImpl"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallParticipantStoreImpl\/fragments"},{"value":[{"text":"CallParticipantStoreImpl","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallParticipantStoreImpl\/navigatorTitle"}]}]}