{"variants":[{"paths":["\/documentation\/atomicxcore\/callparticipantstoreimpl\/onusernetworkqualitychanged(networkqualitylist:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/atomicxcore\/callparticipantstoreimpl\/onusernetworkqualitychanged(networkqualitylist:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallParticipantStoreImpl"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallParticipantStoreImpl\/onUserNetworkQualityChanged(networkQualityList:)"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserNetworkQualityChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"networkQualityList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"TUINetworkQualityInfo","preciseIdentifier":"c:objc(cs)TUINetworkQualityInfo"},{"kind":"text","text":"])"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"roleHeading":"Instance Method","externalID":"c:@CM@AtomicXCore@objc(cs)CallParticipantStoreImpl(im)onUserNetworkQualityChanged:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"onUserNetworkQualityChanged:"}],"title":"onUserNetworkQualityChanged(networkQualityList:)","modules":[{"name":"AtomicXCore"}],"extendedModule":"AtomicXCore","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserNetworkQualityChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"networkQualityList"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)TUINetworkQualityInfo","kind":"typeIdentifier","text":"TUINetworkQualityInfo"},{"kind":"text","text":"])"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"TUICallObserver.onUserNetworkQualityChanged(networkQualityList:)","type":"codeVoice"},{"text":".","type":"text"}],"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"abstract":[],"title":"AtomicXCore","type":"topic","kind":"symbol","url":"\/documentation\/atomicxcore","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","role":"collection"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallParticipantStoreImpl/onUserNetworkQualityChanged(networkQualityList:)":{"abstract":[],"kind":"symbol","url":"\/documentation\/atomicxcore\/callparticipantstoreimpl\/onusernetworkqualitychanged(networkqualitylist:)","type":"topic","role":"symbol","title":"onUserNetworkQualityChanged(networkQualityList:)","navigatorTitle":[{"text":"onUserNetworkQualityChanged:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallParticipantStoreImpl\/onUserNetworkQualityChanged(networkQualityList:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserNetworkQualityChanged"},{"text":"(","kind":"text"},{"text":"networkQualityList","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"TUINetworkQualityInfo","preciseIdentifier":"c:objc(cs)TUINetworkQualityInfo","kind":"typeIdentifier"},{"text":"])","kind":"text"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallParticipantStoreImpl":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallParticipantStoreImpl"}],"navigatorTitle":[{"kind":"identifier","text":"CallParticipantStoreImpl"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallParticipantStoreImpl","url":"\/documentation\/atomicxcore\/callparticipantstoreimpl","title":"CallParticipantStoreImpl","role":"symbol","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"onUserNetworkQualityChanged:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onUserNetworkQualityChanged:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"onUserNetworkQualityChanged:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<TUINetworkQualityInfo *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"networkQualityList"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallParticipantStoreImpl~1onUserNetworkQualityChanged(networkQualityList:)\/title","op":"replace","value":"onUserNetworkQualityChanged:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onUserNetworkQualityChanged:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallParticipantStoreImpl~1onUserNetworkQualityChanged(networkQualityList:)\/fragments"},{"op":"replace","value":"CallParticipantStoreImpl","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallParticipantStoreImpl\/title"},{"op":"replace","value":[{"text":"CallParticipantStoreImpl","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallParticipantStoreImpl\/fragments"},{"op":"replace","value":[{"text":"CallParticipantStoreImpl","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallParticipantStoreImpl\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}