{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onUserAudioAvailable","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"isAudioAvailable","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/atomicxcore\/callparticipantstoreimpl\/onuseraudioavailable(userid:isaudioavailable:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/atomicxcore\/callparticipantstoreimpl\/onuseraudioavailable(userid:isaudioavailable:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"extendedModule":"AtomicXCore","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onUserAudioAvailable","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"isAudioAvailable","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"symbolKind":"method","title":"onUserAudioAvailable(userId:isAudioAvailable:)","navigatorTitle":[{"text":"onUserAudioAvailable:isAudioAvailable:","kind":"identifier"}],"modules":[{"name":"AtomicXCore"}],"externalID":"c:@CM@AtomicXCore@objc(cs)CallParticipantStoreImpl(im)onUserAudioAvailable:isAudioAvailable:","roleHeading":"Instance Method"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"TUICallObserver.onUserAudioAvailable(userId:isAudioAvailable:)","type":"codeVoice"},{"text":".","type":"text"}],"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallParticipantStoreImpl\/onUserAudioAvailable(userId:isAudioAvailable:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallParticipantStoreImpl"]]},"kind":"symbol","references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallParticipantStoreImpl/onUserAudioAvailable(userId:isAudioAvailable:)":{"navigatorTitle":[{"kind":"identifier","text":"onUserAudioAvailable:isAudioAvailable:"}],"kind":"symbol","url":"\/documentation\/atomicxcore\/callparticipantstoreimpl\/onuseraudioavailable(userid:isaudioavailable:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserAudioAvailable"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isAudioAvailable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"role":"symbol","title":"onUserAudioAvailable(userId:isAudioAvailable:)","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallParticipantStoreImpl\/onUserAudioAvailable(userId:isAudioAvailable:)","type":"topic","abstract":[]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"url":"\/documentation\/atomicxcore","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","type":"topic","kind":"symbol","abstract":[],"role":"collection"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallParticipantStoreImpl":{"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallParticipantStoreImpl","kind":"identifier"}],"type":"topic","title":"CallParticipantStoreImpl","kind":"symbol","url":"\/documentation\/atomicxcore\/callparticipantstoreimpl","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallParticipantStoreImpl","role":"symbol","navigatorTitle":[{"text":"CallParticipantStoreImpl","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"onUserAudioAvailable:isAudioAvailable:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onUserAudioAvailable:isAudioAvailable:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"onUserAudioAvailable:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"userId"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAudioAvailable:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"isAudioAvailable","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"onUserAudioAvailable:isAudioAvailable:","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallParticipantStoreImpl~1onUserAudioAvailable(userId:isAudioAvailable:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onUserAudioAvailable:isAudioAvailable:"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallParticipantStoreImpl~1onUserAudioAvailable(userId:isAudioAvailable:)\/fragments"},{"op":"replace","value":"CallParticipantStoreImpl","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallParticipantStoreImpl\/title"},{"op":"replace","value":[{"text":"CallParticipantStoreImpl","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallParticipantStoreImpl\/fragments"},{"op":"replace","value":[{"text":"CallParticipantStoreImpl","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallParticipantStoreImpl\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}