{"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LoginStore\/sdkAppID","interfaceLanguage":"swift"},"metadata":{"symbolKind":"property","title":"sdkAppID","externalID":"s:11AtomicXCore10LoginStoreC8sdkAppIDs5Int32Vvp","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sdkAppID","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"}],"role":"symbol","modules":[{"name":"AtomicXCore"}]},"abstract":[{"type":"text","text":"SDK application ID"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sdkAppID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/loginstore\/sdkappid"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LoginStore"]]},"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"kind":"symbol","abstract":[],"type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LoginStore/sdkAppID":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LoginStore\/sdkAppID","kind":"symbol","role":"symbol","abstract":[{"text":"SDK application ID","type":"text"}],"url":"\/documentation\/atomicxcore\/loginstore\/sdkappid","type":"topic","title":"sdkAppID","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sdkAppID","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LoginStore":{"navigatorTitle":[{"text":"LoginStore","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LoginStore","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LoginStore","abstract":[{"type":"text","text":"Login management class."}],"title":"LoginStore","type":"topic","url":"\/documentation\/atomicxcore\/loginstore","kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"LoginStore","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LoginStore\/title","op":"replace"},{"value":[{"text":"LoginStore","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LoginStore\/fragments","op":"replace"},{"value":[{"text":"LoginStore","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LoginStore\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}