{"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LoginStore\/setSelfInfo(userProfile:completion:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LoginStore"]]},"sections":[],"variants":[{"paths":["\/documentation\/atomicxcore\/loginstore\/setselfinfo(userprofile:completion:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setSelfInfo","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"userProfile"},{"text":": ","kind":"text"},{"text":"UserProfile","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserProfile","preciseIdentifier":"s:11AtomicXCore11UserProfileV"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CompletionClosure","kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","text":"CompletionClosure"},{"text":"?)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"title":"setSelfInfo(userProfile:completion:)","modules":[{"name":"AtomicXCore"}],"externalID":"s:11AtomicXCore10LoginStoreC11setSelfInfo11userProfile10completionyAA04UserI0V_ys6ResultOyytAA05ErrorG0VGcSgtF","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setSelfInfo","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userProfile","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore11UserProfileV","text":"UserProfile"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","text":"CompletionClosure"},{"text":"?)","kind":"text"}],"roleHeading":"Instance Method","symbolKind":"method"},"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LoginStore/setSelfInfo(userProfile:completion:)":{"role":"symbol","title":"setSelfInfo(userProfile:completion:)","url":"\/documentation\/atomicxcore\/loginstore\/setselfinfo(userprofile:completion:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setSelfInfo","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userProfile"},{"kind":"text","text":": "},{"text":"UserProfile","preciseIdentifier":"s:11AtomicXCore11UserProfileV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","text":"CompletionClosure"},{"kind":"text","text":"?)"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LoginStore\/setSelfInfo(userProfile:completion:)","kind":"symbol","type":"topic"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CompletionClosure":{"url":"\/documentation\/atomicxcore\/completionclosure","kind":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"CompletionClosure"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CompletionClosure","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CompletionClosure","title":"CompletionClosure","role":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/UserProfile":{"type":"topic","abstract":[],"role":"symbol","url":"\/documentation\/atomicxcore\/userprofile","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"UserProfile","kind":"identifier"}],"navigatorTitle":[{"text":"UserProfile","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserProfile","kind":"symbol","title":"UserProfile"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","title":"AtomicXCore","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","abstract":[],"url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LoginStore":{"title":"LoginStore","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"LoginStore","kind":"identifier"}],"kind":"symbol","abstract":[],"url":"\/documentation\/atomicxcore\/loginstore","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LoginStore","navigatorTitle":[{"kind":"identifier","text":"LoginStore"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LoginStore\/title","value":"LoginStore"},{"value":[{"text":"LoginStore","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LoginStore\/fragments"},{"op":"replace","value":[{"text":"LoginStore","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LoginStore\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}