{"abstract":[{"type":"text","text":"Login state{@link LoginState}"}],"kind":"symbol","variants":[{"paths":["\/documentation\/atomicxcore\/loginstore\/state"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LoginStore"]]},"metadata":{"role":"symbol","title":"state","symbolKind":"property","externalID":"s:11AtomicXCore10LoginStoreC5stateAA14StatePublisherCyAA0cF0VGvp","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"state"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11AtomicXCore14StatePublisherC","kind":"typeIdentifier","text":"StatePublisher"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:11AtomicXCore10LoginStateV","kind":"typeIdentifier","text":"LoginState"},{"kind":"text","text":">"}],"modules":[{"name":"AtomicXCore"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"state","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/StatePublisher","preciseIdentifier":"s:11AtomicXCore14StatePublisherC","text":"StatePublisher","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LoginState","preciseIdentifier":"s:11AtomicXCore10LoginStateV","text":"LoginState","kind":"typeIdentifier"},{"text":">","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LoginStore\/state","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LoginStore":{"abstract":[{"text":"Login management class.","type":"text"}],"url":"\/documentation\/atomicxcore\/loginstore","type":"topic","role":"symbol","navigatorTitle":[{"text":"LoginStore","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LoginStore","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LoginStore","kind":"symbol","title":"LoginStore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LoginState":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LoginState","kind":"identifier"}],"url":"\/documentation\/atomicxcore\/loginstate","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LoginState","title":"LoginState","kind":"symbol","navigatorTitle":[{"text":"LoginState","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Login state","type":"text"}],"type":"topic"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LoginStore/state":{"type":"topic","kind":"symbol","abstract":[{"text":"Login state{@link LoginState}","type":"text"}],"url":"\/documentation\/atomicxcore\/loginstore\/state","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LoginStore\/state","title":"state","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"state","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11AtomicXCore14StatePublisherC","text":"StatePublisher","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:11AtomicXCore10LoginStateV","text":"LoginState","kind":"typeIdentifier"},{"text":">","kind":"text"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/StatePublisher":{"navigatorTitle":[{"text":"StatePublisher","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/StatePublisher","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StatePublisher","kind":"identifier"}],"title":"StatePublisher","role":"symbol","abstract":[{"type":"text","text":"状态发布器"},{"type":"text","text":" "},{"type":"text","text":"基于 Combine 框架的响应式状态管理容器，支持状态订阅和更新"}],"url":"\/documentation\/atomicxcore\/statepublisher","kind":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"url":"\/documentation\/atomicxcore","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","type":"topic","kind":"symbol","abstract":[],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LoginStore\/title","value":"LoginStore"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LoginStore\/fragments","value":[{"text":"LoginStore","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LoginStore\/navigatorTitle","value":[{"text":"LoginStore","kind":"identifier"}]}]}]}