{"metadata":{"roleHeading":"Instance Method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"title":"init","externalID":"c:@M@AtomicXCore@objc(cs)CallListStore(im)init","role":"symbol","modules":[{"name":"AtomicXCore"}],"symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStore"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/atomicxcore\/callliststore\/init"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStore\/init","interfaceLanguage":"occ"},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}]}]}],"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallListStore":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallListStore"}],"title":"CallListStore","type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStore","role":"symbol","url":"\/documentation\/atomicxcore\/callliststore","navigatorTitle":[{"kind":"identifier","text":"CallListStore"}],"abstract":[]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"kind":"symbol","abstract":[],"type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallListStore/init":{"abstract":[],"url":"\/documentation\/atomicxcore\/callliststore\/init","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStore\/init","type":"topic","title":"init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStore\/title","value":"CallListStore"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStore\/fragments","value":[{"text":"CallListStore","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStore\/navigatorTitle","value":[{"text":"CallListStore","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}