{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"queryRecentCalls","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cursor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"count","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CompletionClosure","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CompletionClosure","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/callliststore\/queryrecentcalls(cursor:count:completion:)"]}],"metadata":{"externalID":"s:11AtomicXCore13CallListStoreC16queryRecentCalls6cursor5count10completionySS_Suys6ResultOyytAA9ErrorInfoVGcSgtF","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"queryRecentCalls","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cursor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"count","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","text":"CompletionClosure","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"roleHeading":"Instance Method","role":"symbol","symbolKind":"method","modules":[{"name":"AtomicXCore"}],"title":"queryRecentCalls(cursor:count:completion:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStore"]]},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStore\/queryRecentCalls(cursor:count:completion:)","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallListStore/queryRecentCalls(cursor:count:completion:)":{"title":"queryRecentCalls(cursor:count:completion:)","url":"\/documentation\/atomicxcore\/callliststore\/queryrecentcalls(cursor:count:completion:)","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStore\/queryRecentCalls(cursor:count:completion:)","type":"topic","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"queryRecentCalls"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cursor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"count"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"text":"CompletionClosure","kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea"},{"text":"?)","kind":"text"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"kind":"symbol","abstract":[],"type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallListStore":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallListStore"}],"title":"CallListStore","type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStore","role":"symbol","url":"\/documentation\/atomicxcore\/callliststore","navigatorTitle":[{"kind":"identifier","text":"CallListStore"}],"abstract":[]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CompletionClosure":{"url":"\/documentation\/atomicxcore\/completionclosure","abstract":[{"type":"text","text":"完成回调闭包类型"},{"type":"text","text":" "},{"type":"text","text":"用于异步操作的结果回调，成功返回 Void，失败返回 ErrorInfo"}],"type":"topic","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CompletionClosure","kind":"identifier"}],"title":"CompletionClosure","role":"symbol","navigatorTitle":[{"text":"CompletionClosure","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CompletionClosure"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"CallListStore","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStore\/title"},{"op":"replace","value":[{"text":"CallListStore","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStore\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"CallListStore"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStore\/navigatorTitle"}]}]}