{"variants":[{"paths":["\/documentation\/atomicxcore\/callliststore\/shared"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"s:11AtomicXCore13CallListStoreC6sharedAA0cdE4ImplCvpZ","roleHeading":"Type Property","title":"shared","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@AtomicXCore@objc(cs)CallListStoreImpl","text":"CallListStoreImpl","kind":"typeIdentifier"}],"modules":[{"name":"AtomicXCore"}],"symbolKind":"property","role":"symbol"},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl","text":"CallListStoreImpl","kind":"typeIdentifier","preciseIdentifier":"c:@M@AtomicXCore@objc(cs)CallListStoreImpl"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStore\/shared"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStore"]]},"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"abstract":[],"title":"AtomicXCore","type":"topic","kind":"symbol","url":"\/documentation\/atomicxcore","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","role":"collection"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallListStoreImpl":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallListStoreImpl"}],"type":"topic","url":"\/documentation\/atomicxcore\/callliststoreimpl","title":"CallListStoreImpl","navigatorTitle":[{"text":"CallListStoreImpl","kind":"identifier"}],"kind":"symbol","abstract":[],"role":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallListStore":{"kind":"symbol","url":"\/documentation\/atomicxcore\/callliststore","title":"CallListStore","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallListStore","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"CallListStore","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallListStore/shared":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStore\/shared","role":"symbol","url":"\/documentation\/atomicxcore\/callliststore\/shared","type":"topic","title":"shared","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@AtomicXCore@objc(cs)CallListStoreImpl","text":"CallListStoreImpl"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"CallListStoreImpl","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStoreImpl\/title"},{"op":"replace","value":[{"text":"CallListStoreImpl","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStoreImpl\/fragments"},{"op":"replace","value":[{"text":"CallListStoreImpl","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStoreImpl\/navigatorTitle"},{"op":"replace","value":"CallListStore","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStore\/title"},{"op":"replace","value":[{"kind":"identifier","text":"CallListStore"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStore\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"CallListStore"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStore\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}