{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStore"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStore\/deleteConversation(_:completion:)"},"metadata":{"role":"symbol","symbolKind":"method","title":"deleteConversation(_:completion:)","modules":[{"name":"AtomicXCore"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deleteConversation","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"text":"CompletionClosure","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"externalID":"s:11AtomicXCore21ConversationListStoreC06deleteC0_10completionySS_ys6ResultOyytAA9ErrorInfoVGcSgtF","roleHeading":"Instance Method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deleteConversation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"conversationID","kind":"internalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CompletionClosure","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CompletionClosure"},{"text":"?)","kind":"text"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/atomicxcore\/conversationliststore\/deleteconversation(_:completion:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","sections":[],"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConversationListStore":{"abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ConversationListStore","kind":"identifier"}],"navigatorTitle":[{"text":"ConversationListStore","kind":"identifier"}],"type":"topic","url":"\/documentation\/atomicxcore\/conversationliststore","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStore","title":"ConversationListStore","role":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","title":"AtomicXCore","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","abstract":[],"url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConversationListStore/deleteConversation(_:completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteConversation"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CompletionClosure","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea"},{"text":"?)","kind":"text"}],"url":"\/documentation\/atomicxcore\/conversationliststore\/deleteconversation(_:completion:)","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStore\/deleteConversation(_:completion:)","title":"deleteConversation(_:completion:)","role":"symbol","abstract":[],"kind":"symbol","type":"topic"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CompletionClosure":{"url":"\/documentation\/atomicxcore\/completionclosure","kind":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"CompletionClosure"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CompletionClosure","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CompletionClosure","title":"CompletionClosure","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConversationListStore\/title","value":"ConversationListStore"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConversationListStore\/fragments","value":[{"text":"ConversationListStore","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConversationListStore\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ConversationListStore"}]}]}]}