{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStore"]]},"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStore\/getConversationTotalUnreadCount(completion:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/conversationliststore\/getconversationtotalunreadcount(completion:)"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"title":"getConversationTotalUnreadCount(completion:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getConversationTotalUnreadCount"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CompletionClosure","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea"},{"kind":"text","text":"?)"}],"symbolKind":"method","modules":[{"name":"AtomicXCore"}],"externalID":"s:11AtomicXCore21ConversationListStoreC03getC16TotalUnreadCount10completionyys6ResultOyytAA9ErrorInfoVGcSg_tF","role":"symbol"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getConversationTotalUnreadCount"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CompletionClosure","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","text":"CompletionClosure"},{"kind":"text","text":"?)"}],"platforms":["iOS"]}]}],"kind":"symbol","references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CompletionClosure":{"url":"\/documentation\/atomicxcore\/completionclosure","type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CompletionClosure","kind":"symbol","navigatorTitle":[{"text":"CompletionClosure","kind":"identifier"}],"abstract":[{"text":"完成回调闭包类型","type":"text"},{"text":" ","type":"text"},{"text":"用于异步操作的结果回调，成功返回 Void，失败返回 ErrorInfo","type":"text"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CompletionClosure","kind":"identifier"}],"role":"symbol","title":"CompletionClosure"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConversationListStore":{"navigatorTitle":[{"kind":"identifier","text":"ConversationListStore"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationListStore"}],"abstract":[],"url":"\/documentation\/atomicxcore\/conversationliststore","role":"symbol","type":"topic","title":"ConversationListStore","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"abstract":[],"title":"AtomicXCore","type":"topic","kind":"symbol","url":"\/documentation\/atomicxcore","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","role":"collection"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConversationListStore/getConversationTotalUnreadCount(completion:)":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStore\/getConversationTotalUnreadCount(completion:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getConversationTotalUnreadCount"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CompletionClosure","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea"},{"kind":"text","text":"?)"}],"url":"\/documentation\/atomicxcore\/conversationliststore\/getconversationtotalunreadcount(completion:)","role":"symbol","title":"getConversationTotalUnreadCount(completion:)","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConversationListStore\/title","op":"replace","value":"ConversationListStore"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConversationListStore\/fragments","op":"replace","value":[{"kind":"identifier","text":"ConversationListStore"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConversationListStore\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ConversationListStore"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}