{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/layoutmode\/floatlayout"]},{"paths":["\/documentation\/atomicxcore\/layoutmode\/floatlayout"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"role":"symbol","title":"LayoutMode.floatLayout","platforms":[],"symbolKind":"case","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"floatLayout"}],"externalID":"c:@M@AtomicXCore@E@LayoutMode@LayoutModeFloatLayout","modules":[{"name":"AtomicXCore"}],"navigatorTitle":[{"kind":"identifier","text":"LayoutModeFloatLayout"}]},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LayoutMode\/floatLayout"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LayoutMode"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"floatLayout"}]}]}],"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LayoutMode/floatLayout":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"floatLayout"}],"deprecated":true,"kind":"symbol","url":"\/documentation\/atomicxcore\/layoutmode\/floatlayout","role":"symbol","abstract":[],"navigatorTitle":[{"text":"LayoutModeFloatLayout","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LayoutMode\/floatLayout","type":"topic","title":"LayoutMode.floatLayout"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LayoutMode":{"kind":"symbol","abstract":[],"url":"\/documentation\/atomicxcore\/layoutmode","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"LayoutMode","kind":"identifier"}],"deprecated":true,"type":"topic","title":"LayoutMode","navigatorTitle":[{"text":"LayoutMode","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LayoutMode"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","title":"AtomicXCore","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","abstract":[],"url":"\/documentation\/atomicxcore"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"LayoutModeFloatLayout"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"LayoutModeFloatLayout"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"LayoutModeFloatLayout","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"value":"LayoutModeFloatLayout","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LayoutMode~1floatLayout\/title"},{"value":[{"text":"LayoutModeFloatLayout","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LayoutMode~1floatLayout\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LayoutMode\/title","value":"LayoutMode","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LayoutMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"LayoutMode"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LayoutMode\/navigatorTitle","value":[{"text":"LayoutMode","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}