{"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoLayoutMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"LayoutMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@AtomicXCore@E@LayoutMode"}],"role":"symbol","roleHeading":"Instance Property","title":"videoLayoutMode","symbolKind":"property","platforms":[{"beta":false,"deprecated":true,"unavailable":false}],"externalID":"s:11AtomicXCore11LayoutStateV05videoC4ModeAA0cF0Ovp","modules":[{"name":"AtomicXCore"}]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/layoutstate\/videolayoutmode"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LayoutState"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoLayoutMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"LayoutMode","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LayoutMode","preciseIdentifier":"c:@M@AtomicXCore@E@LayoutMode"}],"platforms":["iOS"]}]}],"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LayoutState\/videoLayoutMode","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LayoutState/videoLayoutMode":{"kind":"symbol","title":"videoLayoutMode","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LayoutState\/videoLayoutMode","deprecated":true,"abstract":[],"type":"topic","url":"\/documentation\/atomicxcore\/layoutstate\/videolayoutmode","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoLayoutMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"LayoutMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@AtomicXCore@E@LayoutMode"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"kind":"symbol","abstract":[],"type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LayoutState":{"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LayoutState","kind":"identifier"}],"navigatorTitle":[{"text":"LayoutState","kind":"identifier"}],"type":"topic","url":"\/documentation\/atomicxcore\/layoutstate","title":"LayoutState","abstract":[],"deprecated":true,"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LayoutState","role":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LayoutMode":{"abstract":[],"kind":"symbol","url":"\/documentation\/atomicxcore\/layoutmode","title":"LayoutMode","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LayoutMode","kind":"identifier"}],"navigatorTitle":[{"text":"LayoutMode","kind":"identifier"}],"deprecated":true,"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LayoutMode"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LayoutMode\/title","value":"LayoutMode","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LayoutMode\/fragments","value":[{"text":"LayoutMode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LayoutMode\/navigatorTitle","value":[{"text":"LayoutMode","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}