{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStore"]]},"metadata":{"modules":[{"name":"AtomicXCore"}],"roleHeading":"Instance Property","symbolKind":"property","title":"conversationID","role":"symbol","externalID":"s:11AtomicXCore16MessageListStoreC14conversationIDSSvp","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"kind":"symbol","variants":[{"paths":["\/documentation\/atomicxcore\/messageliststore\/conversationid"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStore\/conversationID","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationID","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/MessageListStore":{"title":"MessageListStore","url":"\/documentation\/atomicxcore\/messageliststore","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStore","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageListStore"}],"navigatorTitle":[{"kind":"identifier","text":"MessageListStore"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/MessageListStore/conversationID":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationID","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","url":"\/documentation\/atomicxcore\/messageliststore\/conversationid","role":"symbol","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStore\/conversationID","title":"conversationID"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"url":"\/documentation\/atomicxcore","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","type":"topic","kind":"symbol","abstract":[],"role":"collection"}},"variantOverrides":[{"patch":[{"value":"MessageListStore","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStore\/title","op":"replace"},{"value":[{"text":"MessageListStore","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStore\/fragments","op":"replace"},{"value":[{"text":"MessageListStore","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStore\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}