{"metadata":{"roleHeading":"Instance Method","externalID":"s:11AtomicXCore16MessageListStoreC09fetchMorecD09direction10completionyAA0C14FetchDirectionV_ys6ResultOyytAA9ErrorInfoVGcSgtF","title":"fetchMoreMessageList(direction:completion:)","symbolKind":"method","modules":[{"name":"AtomicXCore"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchMoreMessageList"},{"kind":"text","text":"("},{"kind":"externalParam","text":"direction"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11AtomicXCore21MessageFetchDirectionV","kind":"typeIdentifier","text":"MessageFetchDirection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","kind":"typeIdentifier","text":"CompletionClosure"},{"kind":"text","text":"?)"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStore"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fetchMoreMessageList"},{"kind":"text","text":"("},{"kind":"externalParam","text":"direction"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageFetchDirection","kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore21MessageFetchDirectionV","text":"MessageFetchDirection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CompletionClosure","kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","text":"CompletionClosure"},{"text":"?)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStore\/fetchMoreMessageList(direction:completion:)"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/messageliststore\/fetchmoremessagelist(direction:completion:)"]}],"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"url":"\/documentation\/atomicxcore","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","type":"topic","kind":"symbol","abstract":[],"role":"collection"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/MessageListStore":{"title":"MessageListStore","url":"\/documentation\/atomicxcore\/messageliststore","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStore","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageListStore"}],"navigatorTitle":[{"kind":"identifier","text":"MessageListStore"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/MessageFetchDirection":{"title":"MessageFetchDirection","type":"topic","kind":"symbol","navigatorTitle":[{"text":"MessageFetchDirection","kind":"identifier"}],"url":"\/documentation\/atomicxcore\/messagefetchdirection","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageFetchDirection","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageFetchDirection","kind":"identifier"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CompletionClosure":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"CompletionClosure"}],"abstract":[{"type":"text","text":"完成回调闭包类型"},{"type":"text","text":" "},{"type":"text","text":"用于异步操作的结果回调，成功返回 Void，失败返回 ErrorInfo"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CompletionClosure"}],"title":"CompletionClosure","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CompletionClosure","url":"\/documentation\/atomicxcore\/completionclosure"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/MessageListStore/fetchMoreMessageList(direction:completion:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fetchMoreMessageList","kind":"identifier"},{"text":"(","kind":"text"},{"text":"direction","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MessageFetchDirection","kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore21MessageFetchDirectionV"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CompletionClosure","kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea"},{"text":"?)","kind":"text"}],"title":"fetchMoreMessageList(direction:completion:)","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStore\/fetchMoreMessageList(direction:completion:)","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/atomicxcore\/messageliststore\/fetchmoremessagelist(direction:completion:)"}},"variantOverrides":[{"patch":[{"value":"MessageListStore","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStore\/title","op":"replace"},{"value":[{"text":"MessageListStore","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStore\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MessageListStore"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStore\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}