{"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"fetchMessageList","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"text":" ","kind":"text"},{"text":"option","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageFetchOption","text":"MessageFetchOption","preciseIdentifier":"s:11AtomicXCore18MessageFetchOptionV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CompletionClosure","kind":"typeIdentifier","text":"CompletionClosure"},{"text":"?)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStore"]]},"metadata":{"role":"symbol","title":"fetchMessageList(with:completion:)","modules":[{"name":"AtomicXCore"}],"symbolKind":"method","roleHeading":"Instance Method","externalID":"s:11AtomicXCore16MessageListStoreC05fetchcD04with10completionyAA0C11FetchOptionV_ys6ResultOyytAA9ErrorInfoVGcSgtF","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"fetchMessageList","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MessageFetchOption","preciseIdentifier":"s:11AtomicXCore18MessageFetchOptionV","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","text":"CompletionClosure","kind":"typeIdentifier"},{"kind":"text","text":"?)"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStore\/fetchMessageList(with:completion:)"},"variants":[{"paths":["\/documentation\/atomicxcore\/messageliststore\/fetchmessagelist(with:completion:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/MessageListStore":{"url":"\/documentation\/atomicxcore\/messageliststore","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStore","role":"symbol","abstract":[],"type":"topic","title":"MessageListStore","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListStore"}],"navigatorTitle":[{"text":"MessageListStore","kind":"identifier"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/MessageFetchOption":{"role":"symbol","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"MessageFetchOption","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageFetchOption","abstract":[],"title":"MessageFetchOption","url":"\/documentation\/atomicxcore\/messagefetchoption","navigatorTitle":[{"text":"MessageFetchOption","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","title":"AtomicXCore","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","abstract":[],"url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/MessageListStore/fetchMessageList(with:completion:)":{"kind":"symbol","title":"fetchMessageList(with:completion:)","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStore\/fetchMessageList(with:completion:)","url":"\/documentation\/atomicxcore\/messageliststore\/fetchmessagelist(with:completion:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"fetchMessageList","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11AtomicXCore18MessageFetchOptionV","kind":"typeIdentifier","text":"MessageFetchOption"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CompletionClosure","kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea"},{"text":"?)","kind":"text"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CompletionClosure":{"url":"\/documentation\/atomicxcore\/completionclosure","kind":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"CompletionClosure"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CompletionClosure","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CompletionClosure","title":"CompletionClosure","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStore\/title","op":"replace","value":"MessageListStore"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStore\/fragments","value":[{"text":"MessageListStore","kind":"identifier"}]},{"op":"replace","value":[{"text":"MessageListStore","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStore\/navigatorTitle"}]}]}