{"metadata":{"symbolKind":"method","title":"onConnectedUsersUpdated(userList:joinList:leaveList:)","navigatorTitle":[{"text":"onConnectedUsersUpdatedWithUserList:joinList:leaveList:","kind":"identifier"}],"platforms":[{"deprecated":true,"unavailable":false,"beta":false}],"required":true,"modules":[{"name":"AtomicXCore"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onConnectedUsersUpdated","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userList","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"TUIUserInfo","preciseIdentifier":"c:objc(cs)TUIUserInfo","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"joinList","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"TUIUserInfo","preciseIdentifier":"c:objc(cs)TUIUserInfo","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"leaveList","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"TUIUserInfo","preciseIdentifier":"c:objc(cs)TUIUserInfo","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"externalID":"c:@M@AtomicXCore@objc(pl)ConnectionObserver(im)onConnectedUsersUpdatedWithUserList:joinList:leaveList:","role":"symbol","roleHeading":"Instance Method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onConnectedUsersUpdated(userList:joinList:leaveList:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onConnectedUsersUpdated"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIUserInfo","text":"TUIUserInfo"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"joinList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIUserInfo","text":"TUIUserInfo"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"leaveList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIUserInfo","text":"TUIUserInfo"},{"kind":"text","text":"])"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver"]]},"sections":[],"variants":[{"paths":["\/documentation\/atomicxcore\/connectionobserver\/onconnectedusersupdated(userlist:joinlist:leavelist:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/atomicxcore\/connectionobserver\/onconnectedusersupdated(userlist:joinlist:leavelist:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConnectionObserver":{"title":"ConnectionObserver","navigatorTitle":[{"text":"ConnectionObserver","kind":"identifier"}],"role":"symbol","deprecated":true,"type":"topic","kind":"symbol","url":"\/documentation\/atomicxcore\/connectionobserver","abstract":[{"type":"text","text":"************************************** observer ***************************************"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConnectionObserver","kind":"identifier"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConnectionObserver/onConnectedUsersUpdated(userList:joinList:leaveList:)":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onConnectedUsersUpdated(userList:joinList:leaveList:)","deprecated":true,"title":"onConnectedUsersUpdated(userList:joinList:leaveList:)","abstract":[],"kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onConnectedUsersUpdated","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userList","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"TUIUserInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIUserInfo"},{"text":"], ","kind":"text"},{"text":"joinList","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"TUIUserInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIUserInfo"},{"text":"], ","kind":"text"},{"text":"leaveList","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"TUIUserInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIUserInfo"},{"text":"])","kind":"text"}],"role":"symbol","url":"\/documentation\/atomicxcore\/connectionobserver\/onconnectedusersupdated(userlist:joinlist:leavelist:)","required":true,"navigatorTitle":[{"text":"onConnectedUsersUpdatedWithUserList:joinList:leaveList:","kind":"identifier"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"kind":"symbol","abstract":[],"type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","url":"\/documentation\/atomicxcore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[{"deprecated":true,"beta":false,"unavailable":false}],"op":"replace","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"onConnectedUsersUpdatedWithUserList:joinList:leaveList:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"onConnectedUsersUpdatedWithUserList:joinList:leaveList:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"onConnectedUsersUpdatedWithUserList:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<TUIUserInfo *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"userList","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"joinList:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<TUIUserInfo *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"joinList","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"leaveList:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<TUIUserInfo *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"leaveList","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ConnectionObserver","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver\/title"},{"value":[{"text":"ConnectionObserver","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver\/fragments"},{"value":[{"kind":"identifier","text":"ConnectionObserver"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver\/navigatorTitle"},{"value":"onConnectedUsersUpdatedWithUserList:joinList:leaveList:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onConnectedUsersUpdated(userList:joinList:leaveList:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"onConnectedUsersUpdatedWithUserList:joinList:leaveList:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onConnectedUsersUpdated(userList:joinList:leaveList:)\/fragments"}]}]}