{"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onCrossRoomConnectionAccepted","kind":"identifier"},{"text":"(","kind":"text"},{"text":"hostUser","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)TUIConnectionUser","text":"TUIConnectionUser","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/atomicxcore\/connectionobserver\/oncrossroomconnectionaccepted(hostuser:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/atomicxcore\/connectionobserver\/oncrossroomconnectionaccepted(hostuser:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onCrossRoomConnectionAccepted(hostUser:)"},"metadata":{"title":"onCrossRoomConnectionAccepted(hostUser:)","role":"symbol","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onCrossRoomConnectionAccepted"},{"kind":"text","text":"("},{"kind":"externalParam","text":"hostUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIConnectionUser","text":"TUIConnectionUser"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"onCrossRoomConnectionAcceptedWithHostUser:"}],"externalID":"c:@M@AtomicXCore@objc(pl)ConnectionObserver(im)onCrossRoomConnectionAcceptedWithHostUser:","platforms":[{"unavailable":false,"beta":false,"deprecated":true}],"symbolKind":"method","modules":[{"name":"AtomicXCore"}],"required":true},"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"abstract":[],"title":"AtomicXCore","type":"topic","kind":"symbol","url":"\/documentation\/atomicxcore","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","role":"collection"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConnectionObserver/onCrossRoomConnectionAccepted(hostUser:)":{"url":"\/documentation\/atomicxcore\/connectionobserver\/oncrossroomconnectionaccepted(hostuser:)","deprecated":true,"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"onCrossRoomConnectionAcceptedWithHostUser:"}],"title":"onCrossRoomConnectionAccepted(hostUser:)","required":true,"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onCrossRoomConnectionAccepted"},{"kind":"text","text":"("},{"kind":"externalParam","text":"hostUser"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)TUIConnectionUser","kind":"typeIdentifier","text":"TUIConnectionUser"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onCrossRoomConnectionAccepted(hostUser:)"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConnectionObserver":{"deprecated":true,"title":"ConnectionObserver","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver","navigatorTitle":[{"kind":"identifier","text":"ConnectionObserver"}],"abstract":[{"type":"text","text":"************************************** observer ***************************************"}],"url":"\/documentation\/atomicxcore\/connectionobserver","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConnectionObserver"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[{"deprecated":true,"unavailable":false,"beta":false}]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onCrossRoomConnectionAcceptedWithHostUser:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onCrossRoomConnectionAcceptedWithHostUser:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"onCrossRoomConnectionAcceptedWithHostUser:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)TUIConnectionUser","kind":"typeIdentifier","text":"TUIConnectionUser"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"hostUser"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onCrossRoomConnectionAccepted(hostUser:)\/title","value":"onCrossRoomConnectionAcceptedWithHostUser:"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onCrossRoomConnectionAccepted(hostUser:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onCrossRoomConnectionAcceptedWithHostUser:"}]},{"value":"ConnectionObserver","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver\/title"},{"value":[{"kind":"identifier","text":"ConnectionObserver"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver\/fragments"},{"value":[{"kind":"identifier","text":"ConnectionObserver"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver\/navigatorTitle"}]}]}