{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onCrossRoomConnectionRejected","kind":"identifier"},{"text":"(","kind":"text"},{"text":"hostUser","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)TUIConnectionUser","text":"TUIConnectionUser","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver"]]},"variants":[{"paths":["\/documentation\/atomicxcore\/connectionobserver\/oncrossroomconnectionrejected(hostuser:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/atomicxcore\/connectionobserver\/oncrossroomconnectionrejected(hostuser:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onCrossRoomConnectionRejected(hostUser:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"required":true,"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"onCrossRoomConnectionRejectedWithHostUser:"}],"symbolKind":"method","title":"onCrossRoomConnectionRejected(hostUser:)","modules":[{"name":"AtomicXCore"}],"externalID":"c:@M@AtomicXCore@objc(pl)ConnectionObserver(im)onCrossRoomConnectionRejectedWithHostUser:","role":"symbol","platforms":[{"beta":false,"deprecated":true,"unavailable":false}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onCrossRoomConnectionRejected","kind":"identifier"},{"text":"(","kind":"text"},{"text":"hostUser","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUIConnectionUser","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIConnectionUser"},{"text":")","kind":"text"}]},"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConnectionObserver/onCrossRoomConnectionRejected(hostUser:)":{"deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"onCrossRoomConnectionRejectedWithHostUser:"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onCrossRoomConnectionRejected(hostUser:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onCrossRoomConnectionRejected"},{"kind":"text","text":"("},{"kind":"externalParam","text":"hostUser"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)TUIConnectionUser","kind":"typeIdentifier","text":"TUIConnectionUser"},{"kind":"text","text":")"}],"title":"onCrossRoomConnectionRejected(hostUser:)","required":true,"url":"\/documentation\/atomicxcore\/connectionobserver\/oncrossroomconnectionrejected(hostuser:)","type":"topic","kind":"symbol","role":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"kind":"symbol","abstract":[],"type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConnectionObserver":{"title":"ConnectionObserver","navigatorTitle":[{"text":"ConnectionObserver","kind":"identifier"}],"role":"symbol","deprecated":true,"type":"topic","kind":"symbol","url":"\/documentation\/atomicxcore\/connectionobserver","abstract":[{"type":"text","text":"************************************** observer ***************************************"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConnectionObserver","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"replace","value":[{"beta":false,"unavailable":false,"deprecated":true}]},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"onCrossRoomConnectionRejectedWithHostUser:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onCrossRoomConnectionRejectedWithHostUser:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"onCrossRoomConnectionRejectedWithHostUser:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)TUIConnectionUser","kind":"typeIdentifier","text":"TUIConnectionUser"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"hostUser"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onCrossRoomConnectionRejected(hostUser:)\/title","op":"replace","value":"onCrossRoomConnectionRejectedWithHostUser:"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onCrossRoomConnectionRejected(hostUser:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onCrossRoomConnectionRejectedWithHostUser:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver\/title","op":"replace","value":"ConnectionObserver"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver\/fragments","op":"replace","value":[{"text":"ConnectionObserver","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ConnectionObserver"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}