{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onCrossRoomConnectionTimeout(inviter:invitee:)"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/connectionobserver\/oncrossroomconnectiontimeout(inviter:invitee:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/atomicxcore\/connectionobserver\/oncrossroomconnectiontimeout(inviter:invitee:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onCrossRoomConnectionTimeout","kind":"identifier"},{"text":"(","kind":"text"},{"text":"inviter","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)TUIConnectionUser","kind":"typeIdentifier","text":"TUIConnectionUser"},{"text":", ","kind":"text"},{"text":"invitee","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUIConnectionUser","preciseIdentifier":"c:objc(cs)TUIConnectionUser","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]}],"metadata":{"required":true,"externalID":"c:@M@AtomicXCore@objc(pl)ConnectionObserver(im)onCrossRoomConnectionTimeoutWithInviter:invitee:","title":"onCrossRoomConnectionTimeout(inviter:invitee:)","platforms":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onCrossRoomConnectionTimeout"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inviter"},{"text":": ","kind":"text"},{"text":"TUIConnectionUser","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIConnectionUser"},{"kind":"text","text":", "},{"kind":"externalParam","text":"invitee"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TUIConnectionUser","preciseIdentifier":"c:objc(cs)TUIConnectionUser"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","modules":[{"name":"AtomicXCore"}],"navigatorTitle":[{"text":"onCrossRoomConnectionTimeoutWithInviter:invitee:","kind":"identifier"}],"symbolKind":"method","role":"symbol"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConnectionObserver/onCrossRoomConnectionTimeout(inviter:invitee:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onCrossRoomConnectionTimeout"},{"text":"(","kind":"text"},{"text":"inviter","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIConnectionUser","text":"TUIConnectionUser"},{"kind":"text","text":", "},{"kind":"externalParam","text":"invitee"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIConnectionUser","text":"TUIConnectionUser"},{"text":")","kind":"text"}],"deprecated":true,"required":true,"abstract":[],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onCrossRoomConnectionTimeout(inviter:invitee:)","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onCrossRoomConnectionTimeoutWithInviter:invitee:"}],"url":"\/documentation\/atomicxcore\/connectionobserver\/oncrossroomconnectiontimeout(inviter:invitee:)","kind":"symbol","title":"onCrossRoomConnectionTimeout(inviter:invitee:)"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","title":"AtomicXCore","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","abstract":[],"url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConnectionObserver":{"type":"topic","kind":"symbol","title":"ConnectionObserver","abstract":[{"text":"************************************** observer ***************************************","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConnectionObserver"}],"deprecated":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConnectionObserver"}],"url":"\/documentation\/atomicxcore\/connectionobserver","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onCrossRoomConnectionTimeoutWithInviter:invitee:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onCrossRoomConnectionTimeoutWithInviter:invitee:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"onCrossRoomConnectionTimeoutWithInviter:"},{"kind":"text","text":"("},{"text":"TUIConnectionUser","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIConnectionUser"},{"text":" *) ","kind":"text"},{"text":"inviter","kind":"internalParam"},{"kind":"text","text":" "},{"text":"invitee:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)TUIConnectionUser","text":"TUIConnectionUser","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"invitee","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","value":"onCrossRoomConnectionTimeoutWithInviter:invitee:","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onCrossRoomConnectionTimeout(inviter:invitee:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onCrossRoomConnectionTimeout(inviter:invitee:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onCrossRoomConnectionTimeoutWithInviter:invitee:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver\/title","value":"ConnectionObserver"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver\/fragments","value":[{"kind":"identifier","text":"ConnectionObserver"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver\/navigatorTitle","value":[{"text":"ConnectionObserver","kind":"identifier"}]}]}]}