{"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onRoomDismissed(roomId:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onRoomDismissed","kind":"identifier"},{"text":"(","kind":"text"},{"text":"roomId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/atomicxcore\/connectionobserver\/onroomdismissed(roomid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/atomicxcore\/connectionobserver\/onroomdismissed(roomid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver"]]},"sections":[],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onRoomDismissed","kind":"identifier"},{"text":"(","kind":"text"},{"text":"roomId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"onRoomDismissed(roomId:)","required":true,"navigatorTitle":[{"kind":"identifier","text":"onRoomDismissedWithRoomId:"}],"role":"symbol","roleHeading":"Instance Method","platforms":[{"deprecated":true,"unavailable":false,"beta":false}],"symbolKind":"method","externalID":"c:@M@AtomicXCore@objc(pl)ConnectionObserver(im)onRoomDismissedWithRoomId:","modules":[{"name":"AtomicXCore"}]},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConnectionObserver/onRoomDismissed(roomId:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onRoomDismissed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"roomId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"kind":"symbol","deprecated":true,"abstract":[],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onRoomDismissed(roomId:)","title":"onRoomDismissed(roomId:)","navigatorTitle":[{"kind":"identifier","text":"onRoomDismissedWithRoomId:"}],"role":"symbol","required":true,"type":"topic","url":"\/documentation\/atomicxcore\/connectionobserver\/onroomdismissed(roomid:)"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConnectionObserver":{"title":"ConnectionObserver","navigatorTitle":[{"text":"ConnectionObserver","kind":"identifier"}],"role":"symbol","deprecated":true,"type":"topic","kind":"symbol","url":"\/documentation\/atomicxcore\/connectionobserver","abstract":[{"type":"text","text":"************************************** observer ***************************************"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConnectionObserver","kind":"identifier"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"kind":"symbol","abstract":[],"type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","url":"\/documentation\/atomicxcore"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"replace","value":[{"beta":false,"unavailable":false,"deprecated":true}]},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"onRoomDismissedWithRoomId:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onRoomDismissedWithRoomId:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onRoomDismissedWithRoomId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"roomId"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onRoomDismissed(roomId:)\/title","op":"replace","value":"onRoomDismissedWithRoomId:"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onRoomDismissed(roomId:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onRoomDismissedWithRoomId:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver\/title","op":"replace","value":"ConnectionObserver"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver\/fragments","op":"replace","value":[{"kind":"identifier","text":"ConnectionObserver"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ConnectionObserver"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}