{"variants":[{"paths":["\/documentation\/atomicxcore\/connectionobserver\/onuserconnectionrejected(userinfo:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/atomicxcore\/connectionobserver\/onuserconnectionrejected(userinfo:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onUserConnectionRejected","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUIUserInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIUserInfo"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onUserConnectionRejected(userInfo:)"},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onUserConnectionRejected","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)TUIUserInfo","text":"TUIUserInfo","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":[{"unavailable":false,"beta":false,"deprecated":true}],"externalID":"c:@M@AtomicXCore@objc(pl)ConnectionObserver(im)onUserConnectionRejectedWithUserInfo:","symbolKind":"method","roleHeading":"Instance Method","title":"onUserConnectionRejected(userInfo:)","modules":[{"name":"AtomicXCore"}],"required":true,"navigatorTitle":[{"text":"onUserConnectionRejectedWithUserInfo:","kind":"identifier"}],"role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConnectionObserver/onUserConnectionRejected(userInfo:)":{"navigatorTitle":[{"kind":"identifier","text":"onUserConnectionRejectedWithUserInfo:"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserConnectionRejected"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TUIUserInfo","preciseIdentifier":"c:objc(cs)TUIUserInfo"},{"kind":"text","text":")"}],"url":"\/documentation\/atomicxcore\/connectionobserver\/onuserconnectionrejected(userinfo:)","required":true,"role":"symbol","deprecated":true,"title":"onUserConnectionRejected(userInfo:)","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onUserConnectionRejected(userInfo:)"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConnectionObserver":{"kind":"symbol","title":"ConnectionObserver","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConnectionObserver","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver","navigatorTitle":[{"kind":"identifier","text":"ConnectionObserver"}],"deprecated":true,"url":"\/documentation\/atomicxcore\/connectionobserver","abstract":[{"text":"************************************** observer ***************************************","type":"text"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"url":"\/documentation\/atomicxcore","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","type":"topic","kind":"symbol","abstract":[],"role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"replace","value":[{"beta":false,"deprecated":true,"unavailable":false}]},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"onUserConnectionRejectedWithUserInfo:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onUserConnectionRejectedWithUserInfo:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onUserConnectionRejectedWithUserInfo:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TUIUserInfo","preciseIdentifier":"c:objc(cs)TUIUserInfo"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"userInfo"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onUserConnectionRejected(userInfo:)\/title","op":"replace","value":"onUserConnectionRejectedWithUserInfo:"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onUserConnectionRejected(userInfo:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onUserConnectionRejectedWithUserInfo:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver\/title","op":"replace","value":"ConnectionObserver"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver\/fragments","op":"replace","value":[{"kind":"identifier","text":"ConnectionObserver"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver\/navigatorTitle","op":"replace","value":[{"text":"ConnectionObserver","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}