{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onUserConnectionExited(userInfo:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/connectionobserver\/onuserconnectionexited(userinfo:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/atomicxcore\/connectionobserver\/onuserconnectionexited(userinfo:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onUserConnectionExited","kind":"identifier"},{"kind":"text","text":"("},{"text":"userInfo","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TUIUserInfo","preciseIdentifier":"c:objc(cs)TUIUserInfo"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"kind":"symbol","metadata":{"platforms":[],"modules":[{"name":"AtomicXCore"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserConnectionExited"},{"kind":"text","text":"("},{"text":"userInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)TUIUserInfo","kind":"typeIdentifier","text":"TUIUserInfo"},{"text":")","kind":"text"}],"title":"onUserConnectionExited(userInfo:)","required":true,"externalID":"c:@M@AtomicXCore@objc(pl)ConnectionObserver(im)onUserConnectionExitedWithUserInfo:","navigatorTitle":[{"kind":"identifier","text":"onUserConnectionExitedWithUserInfo:"}],"role":"symbol","symbolKind":"method"},"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","title":"AtomicXCore","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","abstract":[],"url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConnectionObserver/onUserConnectionExited(userInfo:)":{"required":true,"role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onUserConnectionExited","kind":"identifier"},{"kind":"text","text":"("},{"text":"userInfo","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIUserInfo","text":"TUIUserInfo"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"onUserConnectionExitedWithUserInfo:","kind":"identifier"}],"deprecated":true,"title":"onUserConnectionExited(userInfo:)","url":"\/documentation\/atomicxcore\/connectionobserver\/onuserconnectionexited(userinfo:)","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onUserConnectionExited(userInfo:)"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConnectionObserver":{"type":"topic","kind":"symbol","title":"ConnectionObserver","abstract":[{"text":"************************************** observer ***************************************","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConnectionObserver"}],"deprecated":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConnectionObserver"}],"url":"\/documentation\/atomicxcore\/connectionobserver","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"onUserConnectionExitedWithUserInfo:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onUserConnectionExitedWithUserInfo:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"onUserConnectionExitedWithUserInfo:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)TUIUserInfo","text":"TUIUserInfo","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"userInfo"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onUserConnectionExited(userInfo:)\/title","value":"onUserConnectionExitedWithUserInfo:"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onUserConnectionExited(userInfo:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onUserConnectionExitedWithUserInfo:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver\/title","value":"ConnectionObserver","op":"replace"},{"value":[{"text":"ConnectionObserver","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver\/navigatorTitle","op":"replace","value":[{"text":"ConnectionObserver","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}