{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onUserConnectionCancelled","kind":"identifier"},{"text":"(","kind":"text"},{"text":"inviterUser","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUIUserInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIUserInfo"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver"]]},"variants":[{"paths":["\/documentation\/atomicxcore\/connectionobserver\/onuserconnectioncancelled(inviteruser:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/atomicxcore\/connectionobserver\/onuserconnectioncancelled(inviteruser:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onUserConnectionCancelled(inviterUser:)"},"kind":"symbol","metadata":{"required":true,"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"onUserConnectionCancelledWithInviterUser:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserConnectionCancelled"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inviterUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIUserInfo","text":"TUIUserInfo"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","externalID":"c:@M@AtomicXCore@objc(pl)ConnectionObserver(im)onUserConnectionCancelledWithInviterUser:","role":"symbol","title":"onUserConnectionCancelled(inviterUser:)","modules":[{"name":"AtomicXCore"}],"platforms":[{"beta":false,"deprecated":true,"unavailable":false}]},"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"kind":"symbol","abstract":[],"type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConnectionObserver":{"title":"ConnectionObserver","navigatorTitle":[{"text":"ConnectionObserver","kind":"identifier"}],"role":"symbol","deprecated":true,"type":"topic","kind":"symbol","url":"\/documentation\/atomicxcore\/connectionobserver","abstract":[{"type":"text","text":"************************************** observer ***************************************"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConnectionObserver","kind":"identifier"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConnectionObserver/onUserConnectionCancelled(inviterUser:)":{"url":"\/documentation\/atomicxcore\/connectionobserver\/onuserconnectioncancelled(inviteruser:)","abstract":[],"type":"topic","kind":"symbol","required":true,"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onUserConnectionCancelled(inviterUser:)","title":"onUserConnectionCancelled(inviterUser:)","navigatorTitle":[{"kind":"identifier","text":"onUserConnectionCancelledWithInviterUser:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserConnectionCancelled"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inviterUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TUIUserInfo","preciseIdentifier":"c:objc(cs)TUIUserInfo"},{"kind":"text","text":")"}],"role":"symbol","deprecated":true}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":[{"beta":false,"unavailable":false,"deprecated":true}],"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"onUserConnectionCancelledWithInviterUser:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onUserConnectionCancelledWithInviterUser:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"onUserConnectionCancelledWithInviterUser:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)TUIUserInfo","text":"TUIUserInfo","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"inviterUser","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"ConnectionObserver","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver\/title"},{"op":"replace","value":[{"text":"ConnectionObserver","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ConnectionObserver"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver\/navigatorTitle"},{"op":"replace","value":"onUserConnectionCancelledWithInviterUser:","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onUserConnectionCancelled(inviterUser:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onUserConnectionCancelledWithInviterUser:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onUserConnectionCancelled(inviterUser:)\/fragments"}]}]}