{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/connectionobserver\/onuserconnectiontimeout(userinfo:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/atomicxcore\/connectionobserver\/onuserconnectiontimeout(userinfo:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserConnectionTimeout"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIUserInfo","text":"TUIUserInfo"},{"kind":"text","text":")"}],"platforms":["iOS"]}]}],"metadata":{"symbolKind":"method","role":"symbol","modules":[{"name":"AtomicXCore"}],"externalID":"c:@M@AtomicXCore@objc(pl)ConnectionObserver(im)onUserConnectionTimeoutWithUserInfo:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onUserConnectionTimeout","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUIUserInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIUserInfo"},{"text":")","kind":"text"}],"required":true,"navigatorTitle":[{"text":"onUserConnectionTimeoutWithUserInfo:","kind":"identifier"}],"title":"onUserConnectionTimeout(userInfo:)","platforms":[{"unavailable":false,"deprecated":true,"beta":false}],"roleHeading":"Instance Method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onUserConnectionTimeout(userInfo:)"},"sections":[],"kind":"symbol","references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConnectionObserver/onUserConnectionTimeout(userInfo:)":{"role":"symbol","required":true,"abstract":[],"navigatorTitle":[{"text":"onUserConnectionTimeoutWithUserInfo:","kind":"identifier"}],"deprecated":true,"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onUserConnectionTimeout(userInfo:)","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserConnectionTimeout"},{"text":"(","kind":"text"},{"text":"userInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUIUserInfo","preciseIdentifier":"c:objc(cs)TUIUserInfo","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"onUserConnectionTimeout(userInfo:)","url":"\/documentation\/atomicxcore\/connectionobserver\/onuserconnectiontimeout(userinfo:)"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConnectionObserver":{"deprecated":true,"title":"ConnectionObserver","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver","navigatorTitle":[{"kind":"identifier","text":"ConnectionObserver"}],"abstract":[{"type":"text","text":"************************************** observer ***************************************"}],"url":"\/documentation\/atomicxcore\/connectionobserver","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConnectionObserver"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"abstract":[],"title":"AtomicXCore","type":"topic","kind":"symbol","url":"\/documentation\/atomicxcore","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":[{"deprecated":true,"unavailable":false,"beta":false}],"path":"\/metadata\/platforms","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"onUserConnectionTimeoutWithUserInfo:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onUserConnectionTimeoutWithUserInfo:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"onUserConnectionTimeoutWithUserInfo:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIUserInfo","text":"TUIUserInfo"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"userInfo"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"onUserConnectionTimeoutWithUserInfo:","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onUserConnectionTimeout(userInfo:)\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onUserConnectionTimeoutWithUserInfo:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onUserConnectionTimeout(userInfo:)\/fragments"},{"op":"replace","value":"ConnectionObserver","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ConnectionObserver"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver\/fragments"},{"op":"replace","value":[{"text":"ConnectionObserver","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver\/navigatorTitle"}]}]}