{"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onUserConnectionAccepted(userInfo:)","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserConnectionAccepted"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userInfo"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TUIUserInfo","preciseIdentifier":"c:objc(cs)TUIUserInfo"},{"text":")","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/atomicxcore\/connectionobserver\/onuserconnectionaccepted(userinfo:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/atomicxcore\/connectionobserver\/onuserconnectionaccepted(userinfo:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"AtomicXCore"}],"platforms":[],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onUserConnectionAccepted","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userInfo","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TUIUserInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIUserInfo"},{"text":")","kind":"text"}],"title":"onUserConnectionAccepted(userInfo:)","roleHeading":"Instance Method","navigatorTitle":[{"text":"onUserConnectionAcceptedWithUserInfo:","kind":"identifier"}],"required":true,"symbolKind":"method","externalID":"c:@M@AtomicXCore@objc(pl)ConnectionObserver(im)onUserConnectionAcceptedWithUserInfo:"},"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConnectionObserver":{"type":"topic","kind":"symbol","title":"ConnectionObserver","abstract":[{"text":"************************************** observer ***************************************","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConnectionObserver"}],"deprecated":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConnectionObserver"}],"url":"\/documentation\/atomicxcore\/connectionobserver","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConnectionObserver/onUserConnectionAccepted(userInfo:)":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onUserConnectionAccepted(userInfo:)","required":true,"role":"symbol","navigatorTitle":[{"text":"onUserConnectionAcceptedWithUserInfo:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onUserConnectionAccepted"},{"text":"(","kind":"text"},{"text":"userInfo","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TUIUserInfo","preciseIdentifier":"c:objc(cs)TUIUserInfo","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"kind":"symbol","type":"topic","deprecated":true,"url":"\/documentation\/atomicxcore\/connectionobserver\/onuserconnectionaccepted(userinfo:)","title":"onUserConnectionAccepted(userInfo:)"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","title":"AtomicXCore","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","abstract":[],"url":"\/documentation\/atomicxcore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"onUserConnectionAcceptedWithUserInfo:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onUserConnectionAcceptedWithUserInfo:","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"text":"onUserConnectionAcceptedWithUserInfo:","kind":"identifier"},{"kind":"text","text":"("},{"text":"TUIUserInfo","preciseIdentifier":"c:objc(cs)TUIUserInfo","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"userInfo"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver\/title","op":"replace","value":"ConnectionObserver"},{"value":[{"text":"ConnectionObserver","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver\/fragments"},{"value":[{"text":"ConnectionObserver","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onUserConnectionAccepted(userInfo:)\/title","value":"onUserConnectionAcceptedWithUserInfo:"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onUserConnectionAccepted(userInfo:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onUserConnectionAcceptedWithUserInfo:","kind":"identifier"}],"op":"replace"}]}]}