{"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"battleUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIBattleUser","text":"TUIBattleUser"}],"roleHeading":"Instance Property","platforms":[{"unavailable":false,"deprecated":true,"beta":false}],"role":"symbol","title":"battleUser","externalID":"c:@M@AtomicXCore@objc(cs)BattleUserViewModel(py)battleUser","navigatorTitle":[{"kind":"identifier","text":"battleUser"}],"modules":[{"name":"AtomicXCore"}],"symbolKind":"property"},"variants":[{"paths":["\/documentation\/atomicxcore\/battleuserviewmodel\/battleuser"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/atomicxcore\/battleuserviewmodel\/battleuser"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"battleUser","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)TUIBattleUser","text":"TUIBattleUser","kind":"typeIdentifier"}],"languages":["swift"]}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/BattleUserViewModel\/battleUser"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/BattleUserViewModel"]]},"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/BattleUserViewModel":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BattleUserViewModel"}],"type":"topic","title":"BattleUserViewModel","deprecated":true,"abstract":[],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/BattleUserViewModel","navigatorTitle":[{"kind":"identifier","text":"BattleUserViewModel"}],"kind":"symbol","url":"\/documentation\/atomicxcore\/battleuserviewmodel"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/BattleUserViewModel/battleUser":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/BattleUserViewModel\/battleUser","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"battleUser","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TUIBattleUser","preciseIdentifier":"c:objc(cs)TUIBattleUser","kind":"typeIdentifier"}],"deprecated":true,"url":"\/documentation\/atomicxcore\/battleuserviewmodel\/battleuser","kind":"symbol","navigatorTitle":[{"text":"battleUser","kind":"identifier"}],"abstract":[],"type":"topic","title":"battleUser"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"abstract":[],"title":"AtomicXCore","type":"topic","kind":"symbol","url":"\/documentation\/atomicxcore","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[{"beta":false,"deprecated":true,"unavailable":false}]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"battleUser"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"battleUser","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"TUIBattleUser","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIBattleUser"},{"text":" * ","kind":"text"},{"text":"battleUser","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1BattleUserViewModel\/title","op":"replace","value":"BattleUserViewModel"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1BattleUserViewModel\/fragments","op":"replace","value":[{"kind":"identifier","text":"BattleUserViewModel"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1BattleUserViewModel\/navigatorTitle","op":"replace","value":[{"text":"BattleUserViewModel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1BattleUserViewModel~1battleUser\/title","op":"replace","value":"battleUser"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1BattleUserViewModel~1battleUser\/fragments","op":"replace","value":[{"kind":"identifier","text":"battleUser"}]}]}]}