{"metadata":{"title":"init","role":"symbol","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"init"}],"modules":[{"name":"AtomicXCore"}],"platforms":[{"unavailable":false,"deprecated":true,"beta":false}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"externalID":"c:@M@AtomicXCore@objc(cs)BattleUserViewModel(im)init","roleHeading":"Instance Method"},"variants":[{"paths":["\/documentation\/atomicxcore\/battleuserviewmodel\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/BattleUserViewModel\/init","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/BattleUserViewModel"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"kind":"symbol","references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/BattleUserViewModel/init":{"role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"init"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/BattleUserViewModel\/init","title":"init","url":"\/documentation\/atomicxcore\/battleuserviewmodel\/init","kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"abstract":[],"title":"AtomicXCore","type":"topic","kind":"symbol","url":"\/documentation\/atomicxcore","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","role":"collection"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/BattleUserViewModel":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BattleUserViewModel"}],"type":"topic","title":"BattleUserViewModel","deprecated":true,"abstract":[],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/BattleUserViewModel","navigatorTitle":[{"kind":"identifier","text":"BattleUserViewModel"}],"kind":"symbol","url":"\/documentation\/atomicxcore\/battleuserviewmodel"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1BattleUserViewModel\/title","op":"replace","value":"BattleUserViewModel"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1BattleUserViewModel\/fragments","op":"replace","value":[{"text":"BattleUserViewModel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1BattleUserViewModel\/navigatorTitle","op":"replace","value":[{"text":"BattleUserViewModel","kind":"identifier"}]}]}]}