{"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/BattleObserver"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/battleobserver\/onbattlerequestreject(battleid:inviter:invitee:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/atomicxcore\/battleobserver\/onbattlerequestreject(battleid:inviter:invitee:)"]}],"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/BattleObserver\/onBattleRequestReject(battleId:inviter:invitee:)","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onBattleRequestReject"},{"kind":"text","text":"("},{"kind":"externalParam","text":"battleId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"inviter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIBattleUser","text":"TUIBattleUser"},{"kind":"text","text":", "},{"kind":"externalParam","text":"invitee"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIBattleUser","text":"TUIBattleUser"},{"kind":"text","text":")"}],"modules":[{"name":"AtomicXCore"}],"externalID":"c:@M@AtomicXCore@objc(pl)BattleObserver(im)onBattleRequestRejectWithBattleId:inviter:invitee:","title":"onBattleRequestReject(battleId:inviter:invitee:)","roleHeading":"Instance Method","required":true,"platforms":[{"unavailable":false,"beta":false,"deprecated":true}],"navigatorTitle":[{"kind":"identifier","text":"onBattleRequestRejectWithBattleId:inviter:invitee:"}],"role":"symbol","symbolKind":"method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onBattleRequestReject","kind":"identifier"},{"text":"(","kind":"text"},{"text":"battleId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"inviter","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUIBattleUser","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIBattleUser"},{"text":", ","kind":"text"},{"text":"invitee","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUIBattleUser","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIBattleUser"},{"text":")","kind":"text"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/BattleObserver":{"title":"BattleObserver","kind":"symbol","type":"topic","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BattleObserver","kind":"identifier"}],"navigatorTitle":[{"text":"BattleObserver","kind":"identifier"}],"deprecated":true,"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/BattleObserver","role":"symbol","url":"\/documentation\/atomicxcore\/battleobserver"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"abstract":[],"title":"AtomicXCore","type":"topic","kind":"symbol","url":"\/documentation\/atomicxcore","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","role":"collection"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/BattleObserver/onBattleRequestReject(battleId:inviter:invitee:)":{"required":true,"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onBattleRequestReject","kind":"identifier"},{"text":"(","kind":"text"},{"text":"battleId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"inviter","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUIBattleUser","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIBattleUser"},{"text":", ","kind":"text"},{"text":"invitee","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUIBattleUser","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIBattleUser"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"onBattleRequestRejectWithBattleId:inviter:invitee:"}],"url":"\/documentation\/atomicxcore\/battleobserver\/onbattlerequestreject(battleid:inviter:invitee:)","title":"onBattleRequestReject(battleId:inviter:invitee:)","deprecated":true,"abstract":[],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/BattleObserver\/onBattleRequestReject(battleId:inviter:invitee:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":[{"deprecated":true,"unavailable":false,"beta":false}],"path":"\/metadata\/platforms","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"onBattleRequestRejectWithBattleId:inviter:invitee:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"onBattleRequestRejectWithBattleId:inviter:invitee:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"onBattleRequestRejectWithBattleId:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"battleId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"inviter:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)TUIBattleUser","text":"TUIBattleUser","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"inviter","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"invitee:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)TUIBattleUser","text":"TUIBattleUser","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"invitee","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1BattleObserver\/title","value":"BattleObserver"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1BattleObserver\/fragments","op":"replace","value":[{"text":"BattleObserver","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1BattleObserver\/navigatorTitle","op":"replace","value":[{"text":"BattleObserver","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1BattleObserver~1onBattleRequestReject(battleId:inviter:invitee:)\/title","op":"replace","value":"onBattleRequestRejectWithBattleId:inviter:invitee:"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1BattleObserver~1onBattleRequestReject(battleId:inviter:invitee:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onBattleRequestRejectWithBattleId:inviter:invitee:"}]}]}]}