{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/battleobserver\/onbattlerequestaccept(battleid:inviter:invitee:)"]},{"paths":["\/documentation\/atomicxcore\/battleobserver\/onbattlerequestaccept(battleid:inviter:invitee:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"method","platforms":[],"externalID":"c:@M@AtomicXCore@objc(pl)BattleObserver(im)onBattleRequestAcceptWithBattleId:inviter:invitee:","required":true,"modules":[{"name":"AtomicXCore"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"onBattleRequestAcceptWithBattleId:inviter:invitee:"}],"roleHeading":"Instance Method","title":"onBattleRequestAccept(battleId:inviter:invitee:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onBattleRequestAccept","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"battleId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"inviter","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIBattleUser","text":"TUIBattleUser"},{"text":", ","kind":"text"},{"text":"invitee","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TUIBattleUser","preciseIdentifier":"c:objc(cs)TUIBattleUser"},{"text":")","kind":"text"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onBattleRequestAccept"},{"text":"(","kind":"text"},{"text":"battleId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"inviter","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUIBattleUser","preciseIdentifier":"c:objc(cs)TUIBattleUser","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"invitee"},{"text":": ","kind":"text"},{"text":"TUIBattleUser","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIBattleUser"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/BattleObserver\/onBattleRequestAccept(battleId:inviter:invitee:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/BattleObserver"]]},"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","title":"AtomicXCore","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","abstract":[],"url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/BattleObserver":{"title":"BattleObserver","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"BattleObserver","kind":"identifier"}],"deprecated":true,"kind":"symbol","abstract":[],"url":"\/documentation\/atomicxcore\/battleobserver","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/BattleObserver","navigatorTitle":[{"kind":"identifier","text":"BattleObserver"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/BattleObserver/onBattleRequestAccept(battleId:inviter:invitee:)":{"type":"topic","title":"onBattleRequestAccept(battleId:inviter:invitee:)","required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onBattleRequestAccept","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"battleId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"inviter"},{"text":": ","kind":"text"},{"text":"TUIBattleUser","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIBattleUser"},{"text":", ","kind":"text"},{"text":"invitee","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIBattleUser","text":"TUIBattleUser"},{"kind":"text","text":")"}],"kind":"symbol","deprecated":true,"abstract":[],"url":"\/documentation\/atomicxcore\/battleobserver\/onbattlerequestaccept(battleid:inviter:invitee:)","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/BattleObserver\/onBattleRequestAccept(battleId:inviter:invitee:)","navigatorTitle":[{"text":"onBattleRequestAcceptWithBattleId:inviter:invitee:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"onBattleRequestAcceptWithBattleId:inviter:invitee:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onBattleRequestAcceptWithBattleId:inviter:invitee:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"onBattleRequestAcceptWithBattleId:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"battleId","kind":"internalParam"},{"kind":"text","text":" "},{"text":"inviter:","kind":"identifier"},{"kind":"text","text":"("},{"text":"TUIBattleUser","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIBattleUser"},{"text":" *) ","kind":"text"},{"text":"inviter","kind":"internalParam"},{"kind":"text","text":" "},{"text":"invitee:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"TUIBattleUser","preciseIdentifier":"c:objc(cs)TUIBattleUser"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"invitee"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1BattleObserver\/title","value":"BattleObserver"},{"value":[{"kind":"identifier","text":"BattleObserver"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1BattleObserver\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"BattleObserver"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1BattleObserver\/navigatorTitle"},{"value":"onBattleRequestAcceptWithBattleId:inviter:invitee:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1BattleObserver~1onBattleRequestAccept(battleId:inviter:invitee:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1BattleObserver~1onBattleRequestAccept(battleId:inviter:invitee:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onBattleRequestAcceptWithBattleId:inviter:invitee:"}]}]}]}