{"variants":[{"paths":["\/documentation\/atomicxcore\/battleobserver\/onbattleended(battleinfo:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/atomicxcore\/battleobserver\/onbattleended(battleinfo:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/BattleObserver"]]},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"title":"onBattleEnded(battleInfo:)","modules":[{"name":"AtomicXCore"}],"platforms":[{"unavailable":false,"beta":false,"deprecated":true}],"role":"symbol","externalID":"c:@M@AtomicXCore@objc(pl)BattleObserver(im)onBattleEndedWithBattleInfo:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onBattleEnded"},{"kind":"text","text":"("},{"kind":"externalParam","text":"battleInfo"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)TUIBattleInfo","kind":"typeIdentifier","text":"TUIBattleInfo"},{"kind":"text","text":")"}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"onBattleEndedWithBattleInfo:"}],"roleHeading":"Instance Method","symbolKind":"method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onBattleEnded","kind":"identifier"},{"text":"(","kind":"text"},{"text":"battleInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)TUIBattleInfo","text":"TUIBattleInfo","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/BattleObserver\/onBattleEnded(battleInfo:)","interfaceLanguage":"swift"},"sections":[],"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/BattleObserver/onBattleEnded(battleInfo:)":{"abstract":[],"kind":"symbol","deprecated":true,"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onBattleEnded","kind":"identifier"},{"text":"(","kind":"text"},{"text":"battleInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)TUIBattleInfo","text":"TUIBattleInfo","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/BattleObserver\/onBattleEnded(battleInfo:)","url":"\/documentation\/atomicxcore\/battleobserver\/onbattleended(battleinfo:)","navigatorTitle":[{"kind":"identifier","text":"onBattleEndedWithBattleInfo:"}],"required":true,"role":"symbol","title":"onBattleEnded(battleInfo:)"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/BattleObserver":{"url":"\/documentation\/atomicxcore\/battleobserver","kind":"symbol","navigatorTitle":[{"text":"BattleObserver","kind":"identifier"}],"deprecated":true,"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/BattleObserver","title":"BattleObserver","type":"topic","abstract":[],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BattleObserver","kind":"identifier"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"kind":"symbol","abstract":[],"type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","url":"\/documentation\/atomicxcore"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":[{"deprecated":true,"beta":false,"unavailable":false}],"op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"onBattleEndedWithBattleInfo:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onBattleEndedWithBattleInfo:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"onBattleEndedWithBattleInfo:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIBattleInfo","text":"TUIBattleInfo"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"battleInfo"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1BattleObserver~1onBattleEnded(battleInfo:)\/title","value":"onBattleEndedWithBattleInfo:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1BattleObserver~1onBattleEnded(battleInfo:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onBattleEndedWithBattleInfo:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1BattleObserver\/title","value":"BattleObserver","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1BattleObserver\/fragments","value":[{"text":"BattleObserver","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1BattleObserver\/navigatorTitle","value":[{"text":"BattleObserver","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}