{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/BattleObserver\/onBattleScoreChanged(battleId:battleUserList:)"},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onBattleScoreChanged","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"battleId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"battleUserList","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)TUIBattleUser","kind":"typeIdentifier","text":"TUIBattleUser"},{"text":"])","kind":"text"}],"title":"onBattleScoreChanged(battleId:battleUserList:)","required":true,"roleHeading":"Instance Method","navigatorTitle":[{"text":"onBattleScoreChangedWithBattleId:battleUserList:","kind":"identifier"}],"externalID":"c:@M@AtomicXCore@objc(pl)BattleObserver(im)onBattleScoreChangedWithBattleId:battleUserList:","symbolKind":"method","platforms":[],"modules":[{"name":"AtomicXCore"}],"role":"symbol"},"sections":[],"variants":[{"paths":["\/documentation\/atomicxcore\/battleobserver\/onbattlescorechanged(battleid:battleuserlist:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/atomicxcore\/battleobserver\/onbattlescorechanged(battleid:battleuserlist:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onBattleScoreChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"battleId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"battleUserList"},{"kind":"text","text":": ["},{"text":"TUIBattleUser","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIBattleUser"},{"text":"])","kind":"text"}],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/BattleObserver"]]},"kind":"symbol","references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","title":"AtomicXCore","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","abstract":[],"url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/BattleObserver/onBattleScoreChanged(battleId:battleUserList:)":{"kind":"symbol","url":"\/documentation\/atomicxcore\/battleobserver\/onbattlescorechanged(battleid:battleuserlist:)","abstract":[],"type":"topic","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onBattleScoreChanged"},{"text":"(","kind":"text"},{"text":"battleId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"battleUserList","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIBattleUser","text":"TUIBattleUser"},{"text":"])","kind":"text"}],"deprecated":true,"role":"symbol","title":"onBattleScoreChanged(battleId:battleUserList:)","navigatorTitle":[{"kind":"identifier","text":"onBattleScoreChangedWithBattleId:battleUserList:"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/BattleObserver\/onBattleScoreChanged(battleId:battleUserList:)"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/BattleObserver":{"title":"BattleObserver","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"BattleObserver","kind":"identifier"}],"deprecated":true,"kind":"symbol","abstract":[],"url":"\/documentation\/atomicxcore\/battleobserver","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/BattleObserver","navigatorTitle":[{"kind":"identifier","text":"BattleObserver"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"onBattleScoreChangedWithBattleId:battleUserList:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"onBattleScoreChangedWithBattleId:battleUserList:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"onBattleScoreChangedWithBattleId:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"text":"battleId","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"battleUserList:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<TUIBattleUser *>"},{"kind":"text","text":" *) "},{"text":"battleUserList","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1BattleObserver~1onBattleScoreChanged(battleId:battleUserList:)\/title","value":"onBattleScoreChangedWithBattleId:battleUserList:"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1BattleObserver~1onBattleScoreChanged(battleId:battleUserList:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onBattleScoreChangedWithBattleId:battleUserList:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1BattleObserver\/title","value":"BattleObserver"},{"op":"replace","value":[{"text":"BattleObserver","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1BattleObserver\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1BattleObserver\/navigatorTitle","value":[{"kind":"identifier","text":"BattleObserver"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}