{"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/BattleObserver\/onUserJoinBattle(battleId:battleUser:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/BattleObserver"]]},"variants":[{"paths":["\/documentation\/atomicxcore\/battleobserver\/onuserjoinbattle(battleid:battleuser:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/atomicxcore\/battleobserver\/onuserjoinbattle(battleid:battleuser:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onUserJoinBattle","kind":"identifier"},{"text":"(","kind":"text"},{"text":"battleId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"battleUser"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)TUIBattleUser","text":"TUIBattleUser","kind":"typeIdentifier"},{"kind":"text","text":")"}]}]}],"metadata":{"navigatorTitle":[{"text":"onUserJoinBattleWithBattleId:battleUser:","kind":"identifier"}],"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onUserJoinBattle","kind":"identifier"},{"text":"(","kind":"text"},{"text":"battleId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"battleUser","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)TUIBattleUser","kind":"typeIdentifier","text":"TUIBattleUser"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","externalID":"c:@M@AtomicXCore@objc(pl)BattleObserver(im)onUserJoinBattleWithBattleId:battleUser:","required":true,"modules":[{"name":"AtomicXCore"}],"platforms":[],"role":"symbol","title":"onUserJoinBattle(battleId:battleUser:)"},"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","title":"AtomicXCore","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","abstract":[],"url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/BattleObserver/onUserJoinBattle(battleId:battleUser:)":{"type":"topic","title":"onUserJoinBattle(battleId:battleUser:)","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onUserJoinBattle"},{"kind":"text","text":"("},{"text":"battleId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"battleUser","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TUIBattleUser","preciseIdentifier":"c:objc(cs)TUIBattleUser"},{"kind":"text","text":")"}],"kind":"symbol","deprecated":true,"abstract":[],"url":"\/documentation\/atomicxcore\/battleobserver\/onuserjoinbattle(battleid:battleuser:)","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/BattleObserver\/onUserJoinBattle(battleId:battleUser:)","navigatorTitle":[{"kind":"identifier","text":"onUserJoinBattleWithBattleId:battleUser:"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/BattleObserver":{"title":"BattleObserver","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"BattleObserver","kind":"identifier"}],"deprecated":true,"kind":"symbol","abstract":[],"url":"\/documentation\/atomicxcore\/battleobserver","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/BattleObserver","navigatorTitle":[{"kind":"identifier","text":"BattleObserver"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"onUserJoinBattleWithBattleId:battleUser:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"onUserJoinBattleWithBattleId:battleUser:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"onUserJoinBattleWithBattleId:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"battleId"},{"kind":"text","text":" "},{"text":"battleUser:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)TUIBattleUser","text":"TUIBattleUser","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"battleUser","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1BattleObserver~1onUserJoinBattle(battleId:battleUser:)\/title","value":"onUserJoinBattleWithBattleId:battleUser:"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1BattleObserver~1onUserJoinBattle(battleId:battleUser:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onUserJoinBattleWithBattleId:battleUser:"}]},{"value":"BattleObserver","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1BattleObserver\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1BattleObserver\/fragments","value":[{"text":"BattleObserver","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1BattleObserver\/navigatorTitle","value":[{"text":"BattleObserver","kind":"identifier"}]}]}]}