{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/C2CSettingStore"]]},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addToBlacklist","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CompletionClosure","kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea"},{"text":"?)","kind":"text"}],"roleHeading":"Instance Method","role":"symbol","modules":[{"name":"AtomicXCore"}],"symbolKind":"method","title":"addToBlacklist(completion:)","externalID":"s:11AtomicXCore15C2CSettingStoreC14addToBlacklist10completionyys6ResultOyytAA9ErrorInfoVGcSg_tF"},"variants":[{"paths":["\/documentation\/atomicxcore\/c2csettingstore\/addtoblacklist(completion:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/C2CSettingStore\/addToBlacklist(completion:)"},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addToBlacklist"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CompletionClosure","kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","text":"CompletionClosure"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/C2CSettingStore":{"type":"topic","title":"C2CSettingStore","abstract":[],"url":"\/documentation\/atomicxcore\/c2csettingstore","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"C2CSettingStore","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/C2CSettingStore","navigatorTitle":[{"text":"C2CSettingStore","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/C2CSettingStore/addToBlacklist(completion:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/C2CSettingStore\/addToBlacklist(completion:)","url":"\/documentation\/atomicxcore\/c2csettingstore\/addtoblacklist(completion:)","title":"addToBlacklist(completion:)","abstract":[],"type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addToBlacklist","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CompletionClosure","kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea"},{"text":"?)","kind":"text"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"abstract":[],"title":"AtomicXCore","type":"topic","kind":"symbol","url":"\/documentation\/atomicxcore","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","role":"collection"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CompletionClosure":{"url":"\/documentation\/atomicxcore\/completionclosure","type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CompletionClosure","kind":"symbol","navigatorTitle":[{"text":"CompletionClosure","kind":"identifier"}],"abstract":[{"text":"完成回调闭包类型","type":"text"},{"text":" ","type":"text"},{"text":"用于异步操作的结果回调，成功返回 Void，失败返回 ErrorInfo","type":"text"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CompletionClosure","kind":"identifier"}],"role":"symbol","title":"CompletionClosure"}},"variantOverrides":[{"patch":[{"op":"replace","value":"C2CSettingStore","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1C2CSettingStore\/title"},{"op":"replace","value":[{"kind":"identifier","text":"C2CSettingStore"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1C2CSettingStore\/fragments"},{"op":"replace","value":[{"text":"C2CSettingStore","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1C2CSettingStore\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}