{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/C2CSettingStore"]]},"metadata":{"modules":[{"name":"AtomicXCore"}],"title":"create(userID:)","symbolKind":"method","roleHeading":"Type Method","externalID":"s:11AtomicXCore15C2CSettingStoreC6create6userIDACSS_tFZ","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userID","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"C2CSettingStore","preciseIdentifier":"c:@M@AtomicXCore@objc(cs)C2CSettingStore","kind":"typeIdentifier"}],"role":"symbol"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userID","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/C2CSettingStore","text":"C2CSettingStore","kind":"typeIdentifier","preciseIdentifier":"c:@M@AtomicXCore@objc(cs)C2CSettingStore"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/atomicxcore\/c2csettingstore\/create(userid:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/C2CSettingStore\/create(userID:)","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/C2CSettingStore":{"type":"topic","title":"C2CSettingStore","abstract":[],"url":"\/documentation\/atomicxcore\/c2csettingstore","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"C2CSettingStore","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/C2CSettingStore","navigatorTitle":[{"text":"C2CSettingStore","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/C2CSettingStore/create(userID:)":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/C2CSettingStore\/create(userID:)","title":"create(userID:)","role":"symbol","kind":"symbol","abstract":[],"url":"\/documentation\/atomicxcore\/c2csettingstore\/create(userid:)","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userID","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"text":"C2CSettingStore","kind":"typeIdentifier","preciseIdentifier":"c:@M@AtomicXCore@objc(cs)C2CSettingStore"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"abstract":[],"title":"AtomicXCore","type":"topic","kind":"symbol","url":"\/documentation\/atomicxcore","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1C2CSettingStore\/title","op":"replace","value":"C2CSettingStore"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1C2CSettingStore\/fragments","op":"replace","value":[{"kind":"identifier","text":"C2CSettingStore"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1C2CSettingStore\/navigatorTitle","op":"replace","value":[{"text":"C2CSettingStore","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}