{"metadata":{"title":"fetchUserInfo(completion:)","externalID":"s:11AtomicXCore15C2CSettingStoreC13fetchUserInfo10completionyys6ResultOyytAA05ErrorH0VGcSg_tF","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchUserInfo"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","kind":"typeIdentifier","text":"CompletionClosure"},{"kind":"text","text":"?)"}],"symbolKind":"method","role":"symbol","modules":[{"name":"AtomicXCore"}]},"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/C2CSettingStore\/fetchUserInfo(completion:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/C2CSettingStore"]]},"variants":[{"paths":["\/documentation\/atomicxcore\/c2csettingstore\/fetchuserinfo(completion:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fetchUserInfo","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CompletionClosure","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CompletionClosure"},{"text":"?)","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/C2CSettingStore":{"type":"topic","url":"\/documentation\/atomicxcore\/c2csettingstore","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"C2CSettingStore","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"C2CSettingStore","kind":"identifier"}],"abstract":[],"title":"C2CSettingStore","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/C2CSettingStore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"url":"\/documentation\/atomicxcore","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","type":"topic","kind":"symbol","abstract":[],"role":"collection"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CompletionClosure":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"CompletionClosure"}],"abstract":[{"type":"text","text":"完成回调闭包类型"},{"type":"text","text":" "},{"type":"text","text":"用于异步操作的结果回调，成功返回 Void，失败返回 ErrorInfo"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CompletionClosure"}],"title":"CompletionClosure","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CompletionClosure","url":"\/documentation\/atomicxcore\/completionclosure"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/C2CSettingStore/fetchUserInfo(completion:)":{"role":"symbol","title":"fetchUserInfo(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchUserInfo"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","kind":"typeIdentifier","text":"CompletionClosure"},{"kind":"text","text":"?)"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/C2CSettingStore\/fetchUserInfo(completion:)","url":"\/documentation\/atomicxcore\/c2csettingstore\/fetchuserinfo(completion:)","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1C2CSettingStore\/title","value":"C2CSettingStore"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1C2CSettingStore\/fragments","value":[{"text":"C2CSettingStore","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1C2CSettingStore\/navigatorTitle","value":[{"text":"C2CSettingStore","kind":"identifier"}]}]}]}