{"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerConnectionObserver"},{"kind":"text","text":"("},{"kind":"externalParam","text":"observer"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver","kind":"typeIdentifier","preciseIdentifier":"c:@M@AtomicXCore@objc(pl)ConnectionObserver","text":"ConnectionObserver"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"metadata":{"role":"symbol","roleHeading":"Instance Method","extendedModule":"AtomicXCore","modules":[{"name":"AtomicXCore"}],"platforms":[{"unavailable":false,"deprecated":true,"beta":false}],"title":"registerConnectionObserver(observer:)","externalID":"s:11AtomicXCore12LiveCoreViewC26registerConnectionObserver8observeryAA0gH0_p_tF","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"registerConnectionObserver","kind":"identifier"},{"text":"(","kind":"text"},{"text":"observer","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@AtomicXCore@objc(pl)ConnectionObserver","text":"ConnectionObserver","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/registerConnectionObserver(observer:)"},"variants":[{"paths":["\/documentation\/atomicxcore\/livecoreview\/registerconnectionobserver(observer:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView/registerConnectionObserver(observer:)":{"role":"symbol","deprecated":true,"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/registerConnectionObserver(observer:)","url":"\/documentation\/atomicxcore\/livecoreview\/registerconnectionobserver(observer:)","title":"registerConnectionObserver(observer:)","abstract":[],"type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"registerConnectionObserver","kind":"identifier"},{"text":"(","kind":"text"},{"text":"observer","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ConnectionObserver","preciseIdentifier":"c:@M@AtomicXCore@objc(pl)ConnectionObserver","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LiveCoreView","kind":"identifier"}],"role":"symbol","type":"topic","title":"LiveCoreView","navigatorTitle":[{"text":"LiveCoreView","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView","url":"\/documentation\/atomicxcore\/livecoreview"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"abstract":[],"title":"AtomicXCore","type":"topic","kind":"symbol","url":"\/documentation\/atomicxcore","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","role":"collection"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConnectionObserver":{"deprecated":true,"title":"ConnectionObserver","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver","navigatorTitle":[{"kind":"identifier","text":"ConnectionObserver"}],"abstract":[{"type":"text","text":"************************************** observer ***************************************"}],"url":"\/documentation\/atomicxcore\/connectionobserver","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConnectionObserver"}]}},"variantOverrides":[{"patch":[{"value":"LiveCoreView","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LiveCoreView\/title","op":"replace"},{"value":[{"text":"LiveCoreView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LiveCoreView\/fragments","op":"replace"},{"value":[{"text":"LiveCoreView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LiveCoreView\/navigatorTitle","op":"replace"},{"value":"ConnectionObserver","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ConnectionObserver"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"ConnectionObserver"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}