{"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/requestCrossRoomConnection(roomId:timeOut:onSuccess:onError:)","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/livecoreview\/requestcrossroomconnection(roomid:timeout:onsuccess:onerror:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView"]]},"metadata":{"symbolKind":"method","modules":[{"name":"AtomicXCore"}],"title":"requestCrossRoomConnection(roomId:timeOut:onSuccess:onError:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestCrossRoomConnection"},{"kind":"text","text":"("},{"kind":"externalParam","text":"roomId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timeOut"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onSuccess"},{"kind":"text","text":": (("},{"preciseIdentifier":"c:@E@TUIConnectionCode","kind":"typeIdentifier","text":"TUIConnectionCode"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":"), "},{"kind":"externalParam","text":"onError"},{"kind":"text","text":": "},{"preciseIdentifier":"c:TUICommonDefine.h@T@TUIErrorBlock","kind":"typeIdentifier","text":"TUIErrorBlock"},{"kind":"text","text":")"}],"externalID":"s:11AtomicXCore12LiveCoreViewC26requestCrossRoomConnection6roomId7timeOut9onSuccess0N5ErrorySS_SiySo17TUIConnectionCodeVSgcySo8TUIErrorV_SStctF","role":"symbol","platforms":[{"unavailable":false,"beta":false,"deprecated":true}],"extendedModule":"AtomicXCore"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestCrossRoomConnection","kind":"identifier"},{"text":"(","kind":"text"},{"text":"roomId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"timeOut"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onSuccess"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" (("},{"preciseIdentifier":"c:@E@TUIConnectionCode","kind":"typeIdentifier","text":"TUIConnectionCode"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":"), "},{"kind":"externalParam","text":"onError"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:TUICommonDefine.h@T@TUIErrorBlock","text":"TUIErrorBlock"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LiveCoreView"}],"url":"\/documentation\/atomicxcore\/livecoreview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LiveCoreView"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView","abstract":[],"role":"symbol","title":"LiveCoreView"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView/requestCrossRoomConnection(roomId:timeOut:onSuccess:onError:)":{"deprecated":true,"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/requestCrossRoomConnection(roomId:timeOut:onSuccess:onError:)","role":"symbol","title":"requestCrossRoomConnection(roomId:timeOut:onSuccess:onError:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestCrossRoomConnection"},{"kind":"text","text":"("},{"kind":"externalParam","text":"roomId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timeOut"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"onSuccess","kind":"externalParam"},{"text":": ((","kind":"text"},{"preciseIdentifier":"c:@E@TUIConnectionCode","text":"TUIConnectionCode","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":"), ","kind":"text"},{"text":"onError","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:TUICommonDefine.h@T@TUIErrorBlock","text":"TUIErrorBlock","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"kind":"symbol","url":"\/documentation\/atomicxcore\/livecoreview\/requestcrossroomconnection(roomid:timeout:onsuccess:onerror:)"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"kind":"symbol","abstract":[],"type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","url":"\/documentation\/atomicxcore"}},"variantOverrides":[{"patch":[{"value":"LiveCoreView","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LiveCoreView\/title"},{"value":[{"kind":"identifier","text":"LiveCoreView"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LiveCoreView\/fragments"},{"value":[{"kind":"identifier","text":"LiveCoreView"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LiveCoreView\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}