{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"requestBattle","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)TUIBattleConfig","text":"TUIBattleConfig","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userIdList"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"timeout","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onSuccess"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/TUIBattleRequestBlock","preciseIdentifier":"s:11AtomicXCore21TUIBattleRequestBlocka","text":"TUIBattleRequestBlock"},{"text":", ","kind":"text"},{"text":"onError","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" "},{"text":"TUIErrorBlock","kind":"typeIdentifier","preciseIdentifier":"c:TUICommonDefine.h@T@TUIErrorBlock"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"platforms":[],"roleHeading":"Instance Method","externalID":"s:11AtomicXCore12LiveCoreViewC13requestBattle6config10userIdList7timeout9onSuccess0M5ErrorySo15TUIBattleConfigC_SaySSGSdySS_SaySo0P4UserCGtcySo8TUIErrorV_SStctF","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"requestBattle","kind":"identifier"},{"text":"(","kind":"text"},{"text":"config","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUIBattleConfig","preciseIdentifier":"c:objc(cs)TUIBattleConfig","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"userIdList"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"timeout"},{"kind":"text","text":": "},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"onSuccess","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TUIBattleRequestBlock","preciseIdentifier":"s:11AtomicXCore21TUIBattleRequestBlocka"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"onError"},{"text":": ","kind":"text"},{"text":"TUIErrorBlock","preciseIdentifier":"c:TUICommonDefine.h@T@TUIErrorBlock","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","modules":[{"name":"AtomicXCore"}],"title":"requestBattle(config:userIdList:timeout:onSuccess:onError:)","extendedModule":"AtomicXCore"},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/requestBattle(config:userIdList:timeout:onSuccess:onError:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/livecoreview\/requestbattle(config:useridlist:timeout:onsuccess:onerror:)"]}],"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView/requestBattle(config:userIdList:timeout:onSuccess:onError:)":{"role":"symbol","deprecated":true,"abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestBattle"},{"kind":"text","text":"("},{"text":"config","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUIBattleConfig","preciseIdentifier":"c:objc(cs)TUIBattleConfig","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"userIdList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"], ","kind":"text"},{"text":"timeout","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onSuccess"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11AtomicXCore21TUIBattleRequestBlocka","text":"TUIBattleRequestBlock","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"onError","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:TUICommonDefine.h@T@TUIErrorBlock","text":"TUIErrorBlock"},{"kind":"text","text":")"}],"url":"\/documentation\/atomicxcore\/livecoreview\/requestbattle(config:useridlist:timeout:onsuccess:onerror:)","title":"requestBattle(config:userIdList:timeout:onSuccess:onError:)","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/requestBattle(config:userIdList:timeout:onSuccess:onError:)","kind":"symbol","type":"topic"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"LiveCoreView","kind":"identifier"}],"role":"symbol","url":"\/documentation\/atomicxcore\/livecoreview","type":"topic","navigatorTitle":[{"text":"LiveCoreView","kind":"identifier"}],"abstract":[],"title":"LiveCoreView","kind":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","title":"AtomicXCore","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","abstract":[],"url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/TUIBattleRequestBlock":{"type":"topic","title":"TUIBattleRequestBlock","url":"\/documentation\/atomicxcore\/tuibattlerequestblock","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"TUIBattleRequestBlock","kind":"identifier"}],"kind":"symbol","deprecated":true,"role":"symbol","abstract":[],"navigatorTitle":[{"text":"TUIBattleRequestBlock","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/TUIBattleRequestBlock"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LiveCoreView\/title","op":"replace","value":"LiveCoreView"},{"value":[{"kind":"identifier","text":"LiveCoreView"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LiveCoreView\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LiveCoreView\/navigatorTitle","op":"replace","value":[{"text":"LiveCoreView","kind":"identifier"}]}]}]}