{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView"]]},"metadata":{"platforms":[{"unavailable":false,"beta":false,"deprecated":true}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startLiveStream","kind":"identifier"},{"text":"(","kind":"text"},{"text":"roomInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUIRoomInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIRoomInfo"},{"text":", ","kind":"text"},{"text":"onSuccess","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUIRoomInfoBlock","kind":"typeIdentifier","preciseIdentifier":"c:TUIRoomDefine.h@T@TUIRoomInfoBlock"},{"text":", ","kind":"text"},{"text":"onError","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUIErrorBlock","kind":"typeIdentifier","preciseIdentifier":"c:TUICommonDefine.h@T@TUIErrorBlock"},{"text":")","kind":"text"}],"role":"symbol","title":"startLiveStream(roomInfo:onSuccess:onError:)","roleHeading":"Instance Method","extendedModule":"AtomicXCore","symbolKind":"method","modules":[{"name":"AtomicXCore"}],"externalID":"s:11AtomicXCore12LiveCoreViewC05startC6Stream8roomInfo9onSuccess0J5ErrorySo07TUIRoomI0C_yAISgcySo8TUIErrorV_SStctF"},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startLiveStream","kind":"identifier"},{"text":"(","kind":"text"},{"text":"roomInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)TUIRoomInfo","text":"TUIRoomInfo","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"onSuccess","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:TUIRoomDefine.h@T@TUIRoomInfoBlock","text":"TUIRoomInfoBlock","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"onError","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:TUICommonDefine.h@T@TUIErrorBlock","text":"TUIErrorBlock","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/atomicxcore\/livecoreview\/startlivestream(roominfo:onsuccess:onerror:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/startLiveStream(roomInfo:onSuccess:onError:)","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView/startLiveStream(roomInfo:onSuccess:onError:)":{"url":"\/documentation\/atomicxcore\/livecoreview\/startlivestream(roominfo:onsuccess:onerror:)","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/startLiveStream(roomInfo:onSuccess:onError:)","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startLiveStream","kind":"identifier"},{"text":"(","kind":"text"},{"text":"roomInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUIRoomInfo","preciseIdentifier":"c:objc(cs)TUIRoomInfo","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"onSuccess","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUIRoomInfoBlock","preciseIdentifier":"c:TUIRoomDefine.h@T@TUIRoomInfoBlock","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"onError","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUIErrorBlock","preciseIdentifier":"c:TUICommonDefine.h@T@TUIErrorBlock","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","deprecated":true,"title":"startLiveStream(roomInfo:onSuccess:onError:)"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LiveCoreView","kind":"identifier"}],"role":"symbol","type":"topic","title":"LiveCoreView","navigatorTitle":[{"text":"LiveCoreView","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView","url":"\/documentation\/atomicxcore\/livecoreview"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"abstract":[],"title":"AtomicXCore","type":"topic","kind":"symbol","url":"\/documentation\/atomicxcore","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"LiveCoreView","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LiveCoreView\/title"},{"op":"replace","value":[{"text":"LiveCoreView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LiveCoreView\/fragments"},{"op":"replace","value":[{"text":"LiveCoreView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LiveCoreView\/navigatorTitle"}]}]}