{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView"]]},"variants":[{"paths":["\/documentation\/atomicxcore\/livecoreview\/stoppreviewlivestream(roomid:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stopPreviewLiveStream"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"roomId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"sections":[],"kind":"symbol","metadata":{"roleHeading":"Instance Method","modules":[{"name":"AtomicXCore"}],"symbolKind":"method","extendedModule":"AtomicXCore","title":"stopPreviewLiveStream(roomId:)","externalID":"s:11AtomicXCore12LiveCoreViewC011stopPreviewC6Stream6roomIdySS_tF","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stopPreviewLiveStream"},{"text":"(","kind":"text"},{"text":"roomId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/stopPreviewLiveStream(roomId:)"},"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"LiveCoreView","kind":"identifier"}],"role":"symbol","url":"\/documentation\/atomicxcore\/livecoreview","type":"topic","navigatorTitle":[{"text":"LiveCoreView","kind":"identifier"}],"abstract":[],"title":"LiveCoreView","kind":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","title":"AtomicXCore","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","abstract":[],"url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView/stopPreviewLiveStream(roomId:)":{"type":"topic","role":"symbol","url":"\/documentation\/atomicxcore\/livecoreview\/stoppreviewlivestream(roomid:)","title":"stopPreviewLiveStream(roomId:)","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/stopPreviewLiveStream(roomId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"stopPreviewLiveStream","kind":"identifier"},{"text":"(","kind":"text"},{"text":"roomId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LiveCoreView\/title","value":"LiveCoreView"},{"value":[{"text":"LiveCoreView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LiveCoreView\/fragments"},{"value":[{"text":"LiveCoreView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LiveCoreView\/navigatorTitle"}]}]}