{"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Set widget view adapter"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/livecoreview\/videoviewdelegate"]}],"metadata":{"symbolKind":"property","role":"symbol","externalID":"s:11AtomicXCore12LiveCoreViewC05videoE8DelegateAA05VideoeG0_pSgvp","modules":[{"name":"AtomicXCore"}],"title":"videoViewDelegate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoViewDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@AtomicXCore@objc(pl)VideoViewDelegate","text":"VideoViewDelegate","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoViewDelegate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@AtomicXCore@objc(pl)VideoViewDelegate","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/VideoViewDelegate","text":"VideoViewDelegate"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/videoViewDelegate","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView"]]},"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView/videoViewDelegate":{"abstract":[{"text":"Set widget view adapter","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoViewDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@AtomicXCore@objc(pl)VideoViewDelegate","text":"VideoViewDelegate","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/atomicxcore\/livecoreview\/videoviewdelegate","title":"videoViewDelegate","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/videoViewDelegate"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LiveCoreView","kind":"identifier"}],"role":"symbol","type":"topic","title":"LiveCoreView","navigatorTitle":[{"text":"LiveCoreView","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView","url":"\/documentation\/atomicxcore\/livecoreview"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/VideoViewDelegate":{"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/VideoViewDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoViewDelegate"}],"abstract":[{"type":"text","text":"Video view adapter protocol"}],"title":"VideoViewDelegate","url":"\/documentation\/atomicxcore\/videoviewdelegate","navigatorTitle":[{"kind":"identifier","text":"VideoViewDelegate"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"abstract":[],"title":"AtomicXCore","type":"topic","kind":"symbol","url":"\/documentation\/atomicxcore","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"LiveCoreView","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LiveCoreView\/title"},{"op":"replace","value":[{"kind":"identifier","text":"LiveCoreView"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LiveCoreView\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"LiveCoreView"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LiveCoreView\/navigatorTitle"},{"op":"replace","value":"VideoViewDelegate","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1VideoViewDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"VideoViewDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1VideoViewDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"VideoViewDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1VideoViewDelegate\/navigatorTitle"}]}]}