{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createCoHostView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"seatInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TUISeatFullInfo","preciseIdentifier":"c:objc(cs)TUISeatFullInfo"},{"kind":"text","text":", "},{"kind":"externalParam","text":"viewLayer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ViewLayer","text":"ViewLayer","preciseIdentifier":"c:@M@AtomicXCore@E@ViewLayer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"Cross-room co-host user information.","type":"text"}],"type":"paragraph"}],"name":"seatInfo"},{"content":[{"type":"paragraph","inlineContent":[{"text":"View layer.","type":"text"}]}],"name":"viewLayer"}],"kind":"parameters"},{"content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"inlineContent":[{"type":"text","text":"Cross-room co-host view."}],"type":"paragraph"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/videoviewdelegate\/createcohostview(seatinfo:viewlayer:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/atomicxcore\/videoviewdelegate\/createcohostview(seatinfo:viewlayer:)"]}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/VideoViewDelegate\/createCoHostView(seatInfo:viewLayer:)","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@AtomicXCore@objc(pl)VideoViewDelegate(im)createCoHostViewWithSeatInfo:viewLayer:","role":"symbol","modules":[{"name":"AtomicXCore"}],"navigatorTitle":[{"kind":"identifier","text":"createCoHostViewWithSeatInfo:viewLayer:"}],"symbolKind":"method","roleHeading":"Instance Method","title":"createCoHostView(seatInfo:viewLayer:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createCoHostView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"seatInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)TUISeatFullInfo","text":"TUISeatFullInfo","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"viewLayer","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@AtomicXCore@E@ViewLayer","text":"ViewLayer","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Create cross-room co-host view.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/VideoViewDelegate"]]},"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"kind":"symbol","abstract":[],"type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/VideoViewDelegate/createCoHostView(seatInfo:viewLayer:)":{"navigatorTitle":[{"text":"createCoHostViewWithSeatInfo:viewLayer:","kind":"identifier"}],"title":"createCoHostView(seatInfo:viewLayer:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/VideoViewDelegate\/createCoHostView(seatInfo:viewLayer:)","type":"topic","url":"\/documentation\/atomicxcore\/videoviewdelegate\/createcohostview(seatinfo:viewlayer:)","required":true,"abstract":[{"text":"Create cross-room co-host view.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createCoHostView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"seatInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TUISeatFullInfo","preciseIdentifier":"c:objc(cs)TUISeatFullInfo"},{"kind":"text","text":", "},{"kind":"externalParam","text":"viewLayer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ViewLayer","preciseIdentifier":"c:@M@AtomicXCore@E@ViewLayer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/VideoViewDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoViewDelegate"}],"abstract":[{"text":"Video view adapter protocol","type":"text"}],"url":"\/documentation\/atomicxcore\/videoviewdelegate","kind":"symbol","title":"VideoViewDelegate","navigatorTitle":[{"kind":"identifier","text":"VideoViewDelegate"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/VideoViewDelegate","type":"topic","role":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ViewLayer":{"url":"\/documentation\/atomicxcore\/viewlayer","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ViewLayer"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ViewLayer","title":"ViewLayer","abstract":[{"type":"text","text":"View layer."}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ViewLayer"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"createCoHostViewWithSeatInfo:viewLayer:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"createCoHostViewWithSeatInfo:viewLayer:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":" *) ","kind":"text"},{"text":"createCoHostViewWithSeatInfo:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"TUISeatFullInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUISeatFullInfo"},{"text":" *) ","kind":"text"},{"text":"seatInfo","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"viewLayer:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ViewLayer","kind":"typeIdentifier","preciseIdentifier":"c:@M@AtomicXCore@E@ViewLayer","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ViewLayer"},{"text":") ","kind":"text"},{"text":"viewLayer","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Cross-room co-host user information.","type":"text"}]}],"name":"seatInfo"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"View layer."}]}],"name":"viewLayer"}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"value":{"kind":"content","content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Cross-room co-host view."}]}]},"path":"\/primaryContentSections\/2","op":"replace"},{"value":"createCoHostViewWithSeatInfo:viewLayer:","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1VideoViewDelegate~1createCoHostView(seatInfo:viewLayer:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createCoHostViewWithSeatInfo:viewLayer:"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1VideoViewDelegate~1createCoHostView(seatInfo:viewLayer:)\/fragments","op":"replace"},{"value":"VideoViewDelegate","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1VideoViewDelegate\/title","op":"replace"},{"value":[{"text":"VideoViewDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1VideoViewDelegate\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"VideoViewDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1VideoViewDelegate\/navigatorTitle","op":"replace"},{"value":"ViewLayer","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ViewLayer\/title","op":"replace"},{"value":[{"text":"ViewLayer","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ViewLayer\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"ViewLayer"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ViewLayer\/navigatorTitle","op":"replace"}]}]}