{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createCoGuestView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"seatInfo"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)TUISeatFullInfo","kind":"typeIdentifier","text":"TUISeatFullInfo"},{"kind":"text","text":", "},{"kind":"externalParam","text":"viewLayer"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@AtomicXCore@E@ViewLayer","kind":"typeIdentifier","text":"ViewLayer","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ViewLayer"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"seatInfo","content":[{"inlineContent":[{"type":"text","text":"User information."}],"type":"paragraph"}]},{"name":"viewLayer","content":[{"inlineContent":[{"text":"View layer. {@link ViewLayer}","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Co-guest view."}]}],"kind":"content"}],"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"text":"createCoGuestViewWithSeatInfo:viewLayer:","kind":"identifier"}],"role":"symbol","externalID":"c:@M@AtomicXCore@objc(pl)VideoViewDelegate(im)createCoGuestViewWithSeatInfo:viewLayer:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createCoGuestView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"seatInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUISeatFullInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUISeatFullInfo"},{"text":", ","kind":"text"},{"text":"viewLayer","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ViewLayer","kind":"typeIdentifier","preciseIdentifier":"c:@M@AtomicXCore@E@ViewLayer"},{"text":") -> ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":"?","kind":"text"}],"symbolKind":"method","modules":[{"name":"AtomicXCore"}],"title":"createCoGuestView(seatInfo:viewLayer:)","required":true},"abstract":[{"type":"text","text":"Create co-guest view."}],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/VideoViewDelegate\/createCoGuestView(seatInfo:viewLayer:)","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/VideoViewDelegate"]]},"variants":[{"paths":["\/documentation\/atomicxcore\/videoviewdelegate\/createcoguestview(seatinfo:viewlayer:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/atomicxcore\/videoviewdelegate\/createcoguestview(seatinfo:viewlayer:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"abstract":[],"title":"AtomicXCore","type":"topic","kind":"symbol","url":"\/documentation\/atomicxcore","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","role":"collection"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/VideoViewDelegate/createCoGuestView(seatInfo:viewLayer:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createCoGuestView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"seatInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUISeatFullInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUISeatFullInfo"},{"text":", ","kind":"text"},{"text":"viewLayer","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ViewLayer","kind":"typeIdentifier","preciseIdentifier":"c:@M@AtomicXCore@E@ViewLayer"},{"text":") -> ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Create co-guest view."}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/VideoViewDelegate\/createCoGuestView(seatInfo:viewLayer:)","required":true,"navigatorTitle":[{"kind":"identifier","text":"createCoGuestViewWithSeatInfo:viewLayer:"}],"url":"\/documentation\/atomicxcore\/videoviewdelegate\/createcoguestview(seatinfo:viewlayer:)","type":"topic","kind":"symbol","role":"symbol","title":"createCoGuestView(seatInfo:viewLayer:)"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/VideoViewDelegate":{"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/VideoViewDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoViewDelegate"}],"abstract":[{"type":"text","text":"Video view adapter protocol"}],"title":"VideoViewDelegate","url":"\/documentation\/atomicxcore\/videoviewdelegate","navigatorTitle":[{"kind":"identifier","text":"VideoViewDelegate"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ViewLayer":{"abstract":[{"type":"text","text":"View layer."}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ViewLayer","kind":"symbol","url":"\/documentation\/atomicxcore\/viewlayer","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ViewLayer","kind":"identifier"}],"title":"ViewLayer","navigatorTitle":[{"text":"ViewLayer","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"createCoGuestViewWithSeatInfo:viewLayer:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"createCoGuestViewWithSeatInfo:viewLayer:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createCoGuestViewWithSeatInfo:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TUISeatFullInfo","preciseIdentifier":"c:objc(cs)TUISeatFullInfo"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"seatInfo"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewLayer:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ViewLayer","text":"ViewLayer","preciseIdentifier":"c:@M@AtomicXCore@E@ViewLayer"},{"kind":"text","text":") "},{"kind":"internalParam","text":"viewLayer"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"seatInfo","content":[{"type":"paragraph","inlineContent":[{"text":"User information.","type":"text"}]}]},{"name":"viewLayer","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"View layer. {@link ViewLayer}"}]}]}],"kind":"parameters"},"op":"replace"},{"path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"Co-guest view.","type":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1VideoViewDelegate~1createCoGuestView(seatInfo:viewLayer:)\/title","value":"createCoGuestViewWithSeatInfo:viewLayer:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1VideoViewDelegate~1createCoGuestView(seatInfo:viewLayer:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"createCoGuestViewWithSeatInfo:viewLayer:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1VideoViewDelegate\/title","value":"VideoViewDelegate","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1VideoViewDelegate\/fragments","value":[{"kind":"identifier","text":"VideoViewDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1VideoViewDelegate\/navigatorTitle","value":[{"text":"VideoViewDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ViewLayer\/title","value":"ViewLayer","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ViewLayer\/fragments","value":[{"text":"ViewLayer","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ViewLayer\/navigatorTitle","value":[{"kind":"identifier","text":"ViewLayer"}],"op":"replace"}]}]}