{"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/VideoViewDelegate"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/videoviewdelegate\/createbattleview(battleuser:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/atomicxcore\/videoviewdelegate\/createbattleview(battleuser:)"]}],"kind":"symbol","metadata":{"symbolKind":"method","modules":[{"name":"AtomicXCore"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"createBattleView","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"battleUser"},{"text":": ","kind":"text"},{"text":"TUIBattleUser","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIBattleUser"},{"kind":"text","text":") -> "},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?"}],"required":true,"title":"createBattleView(battleUser:)","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"createBattleViewWithBattleUser:"}],"externalID":"c:@M@AtomicXCore@objc(pl)VideoViewDelegate(im)createBattleViewWithBattleUser:","role":"symbol"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"createBattleView","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"battleUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIBattleUser","text":"TUIBattleUser"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/VideoViewDelegate\/createBattleView(battleUser:)","interfaceLanguage":"swift"},"sections":[],"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","title":"AtomicXCore","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","abstract":[],"url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/VideoViewDelegate/createBattleView(battleUser:)":{"navigatorTitle":[{"kind":"identifier","text":"createBattleViewWithBattleUser:"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/VideoViewDelegate\/createBattleView(battleUser:)","role":"symbol","abstract":[],"url":"\/documentation\/atomicxcore\/videoviewdelegate\/createbattleview(battleuser:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"createBattleView","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"battleUser"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIBattleUser","text":"TUIBattleUser"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"},{"kind":"text","text":"?"}],"title":"createBattleView(battleUser:)","required":true,"type":"topic"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/VideoViewDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoViewDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"VideoViewDelegate"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/VideoViewDelegate","title":"VideoViewDelegate","kind":"symbol","type":"topic","url":"\/documentation\/atomicxcore\/videoviewdelegate","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"createBattleViewWithBattleUser:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createBattleViewWithBattleUser:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":" *) "},{"text":"createBattleViewWithBattleUser:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TUIBattleUser","preciseIdentifier":"c:objc(cs)TUIBattleUser"},{"text":" *) ","kind":"text"},{"text":"battleUser","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1VideoViewDelegate~1createBattleView(battleUser:)\/title","op":"replace","value":"createBattleViewWithBattleUser:"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1VideoViewDelegate~1createBattleView(battleUser:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"createBattleViewWithBattleUser:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1VideoViewDelegate\/title","value":"VideoViewDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1VideoViewDelegate\/fragments","value":[{"kind":"identifier","text":"VideoViewDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1VideoViewDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"VideoViewDelegate"}]}]}]}