platform :ios, '14.0'

target 'ChatDemo' do
  use_frameworks! :linkage => :static
  
  pod 'AtomicXCore', :path => '../../../../../tuikit_engine/atomicx/swift/AtomicXCore'
  pod 'AtomicX/Chat', :path => '../../atomic-x/AtomicX.podspec'
  pod 'ChatUIKit', :path => '../uikit/ChatUIKit.podspec'
  pod 'RTCRoomEngine', :path => '../../../../../tuikit_engine/RTCRoomEngine.podspec'
#  pod 'MessageList', :path => '../../atomic-x/Sources/MessageList'
#  pod 'MessageInput', :path => '../../atomic-x/Sources/MessageInput'
#  pod 'ConversationList', :path => '../../atomic-x/Sources/ConversationList'
#  pod 'ContactList', :path => '../../atomic-x/Sources/ContactList'
#  pod 'ChatSetting', :path => '../../atomic-x/Sources/ChatSetting'
#  pod 'Search', :path => '../../atomic-x/Sources/Search'
#  pod 'BaseComponent', :path => '../../atomic-x/Sources/BaseComponent'
#  pod 'AudioPlayer', :path => '../../atomic-x/Sources/AudioPlayer'
#  pod 'VideoPlayer', :path => '../../atomic-x/Sources/VideoPlayer'
#  pod 'ImageViewer', :path => '../../atomic-x/Sources/ImageViewer'
#  pod 'VideoPicker', :path => '../../atomic-x/Sources/VideoPicker'
#  pod 'ImagePicker', :path => '../../atomic-x/Sources/ImagePicker'
#  pod 'FilePicker', :path => '../../atomic-x/Sources/FilePicker'
#  pod 'EmojiPicker', :path => '../../atomic-x/Sources/EmojiPicker'
#  pod 'AudioRecorder', :path => '../../atomic-x/Sources/AudioRecorder'
#  pod 'VideoRecorder', :path => '../../atomic-x/Sources/VideoRecorder'

#测试
#pod 'TXLiteAVSDK_Professional', :path => '/Users/lzmlsfe/Desktop/project/eddardliu/TXLiteAVSDK_Professional_IMUGC'

#  # 添加TXIMSDK_Plus_Swift_iOS_XCFramework依赖
#  pod 'TXIMSDK_Plus_Swift_iOS_XCFramework'
end 

#Pods config
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          
            config.build_settings['SWIFT_VERSION'] = '5.0'
          
            #Do not strip Swift symbols
            config.build_settings['STRIP_SWIFT_SYMBOLS'] = 'NO'
            config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf-with-dsym'
          
            #Fix Xcode14 Bundle target error
            config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
            config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
            config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
            config.build_settings['ENABLE_BITCODE'] = "NO"
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = "14.0"
            
        end
    end
end

