platform :ios, '15.0'

target 'ChatDemo' do
  use_frameworks! :linkage => :static
  
  #pod 'AtomicXCore', :path => '../../../../../tuikit_engine/atomicx/swift/AtomicXCore'
  pod 'ChatUIKit', :path => '../uikit/ChatUIKit.podspec'
  pod 'TUICallKit_Swift', :path => '../../call/TUICallKit_Swift.podspec'
  #pod 'RTCRoomEngine', :path => '../../../../../tuikit_engine/RTCRoomEngine.podspec'
  pod 'TXIMSDK_Plus_iOS_XCFramework', '9.0.7661'

end

#Pods config
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          
            config.build_settings['SWIFT_VERSION'] = '5.0'
          
            #Do not strip Swift symbols
            config.build_settings['STRIP_SWIFT_SYMBOLS'] = 'NO'
            config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf-with-dsym'
          
            #Fix Xcode14 Bundle target error
            config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
            config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
            config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
            config.build_settings['ENABLE_BITCODE'] = "NO"
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = "15.0"
            
        end
    end
    
end

