{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/BattleUserViewModel"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BattleUserViewModel"}],"languages":["swift"]}]}],"metadata":{"modules":[{"name":"AtomicXCore"}],"symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BattleUserViewModel"}],"navigatorTitle":[{"kind":"identifier","text":"BattleUserViewModel"}],"externalID":"c:@M@AtomicXCore@objc(cs)BattleUserViewModel","role":"symbol","platforms":[{"deprecated":true,"unavailable":false,"beta":false}],"roleHeading":"Class","title":"BattleUserViewModel"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/battleuserviewmodel"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/atomicxcore\/battleuserviewmodel"]}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)NSObject","doc:\/\/org.cocoapods.AtomicXCore\/s7CVarArgP","doc:\/\/org.cocoapods.AtomicXCore\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.AtomicXCore\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.AtomicXCore\/SQ","doc:\/\/org.cocoapods.AtomicXCore\/SH"],"title":"Conforms To","type":"conformsTo"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/BattleUserViewModel\/battleUser","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/BattleUserViewModel\/rect"],"anchor":"Instance-Properties","title":"Instance Properties"}],"references":{"doc://org.cocoapods.AtomicXCore/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/BattleUserViewModel/rect":{"url":"\/documentation\/atomicxcore\/battleuserviewmodel\/rect","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/BattleUserViewModel\/rect","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rect"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"}],"navigatorTitle":[{"text":"rect","kind":"identifier"}],"type":"topic","role":"symbol","deprecated":true,"title":"rect"},"doc://org.cocoapods.AtomicXCore/SQ":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://org.cocoapods.AtomicXCore/SH":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://org.cocoapods.AtomicXCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/BattleUserViewModel":{"url":"\/documentation\/atomicxcore\/battleuserviewmodel","deprecated":true,"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/BattleUserViewModel","title":"BattleUserViewModel","type":"topic","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"BattleUserViewModel","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BattleUserViewModel","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.AtomicXCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/BattleUserViewModel/battleUser":{"url":"\/documentation\/atomicxcore\/battleuserviewmodel\/battleuser","deprecated":true,"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/BattleUserViewModel\/battleUser","title":"battleUser","type":"topic","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"battleUser","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"battleUser","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)TUIBattleUser","text":"TUIBattleUser","kind":"typeIdentifier"}],"role":"symbol"},"doc://org.cocoapods.AtomicXCore/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.AtomicXCore/objc(cs)NSObject":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"kind":"symbol","abstract":[],"type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/BattleUserViewModel/init":{"url":"\/documentation\/atomicxcore\/battleuserviewmodel\/init","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/BattleUserViewModel\/init","title":"init","type":"topic","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":[{"deprecated":true,"unavailable":false,"beta":false}],"path":"\/metadata\/platforms"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"BattleUserViewModel","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"BattleUserViewModel","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"BattleUserViewModel","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/BattleUserViewModel\/battleUser","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/BattleUserViewModel\/rect"],"title":"Instance Properties","anchor":"Instance-Properties"},{"generated":true,"identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/BattleUserViewModel\/init"],"title":"Instance Methods","anchor":"Instance-Methods"}],"path":"\/topicSections"},{"op":"replace","value":[{"title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BattleUserViewModel","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1BattleUserViewModel~1rect\/title","value":"rect","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1BattleUserViewModel~1rect\/fragments","value":[{"kind":"identifier","text":"rect"}],"op":"replace"},{"value":"BattleUserViewModel","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1BattleUserViewModel\/title","op":"replace"},{"value":[{"kind":"identifier","text":"BattleUserViewModel"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1BattleUserViewModel\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"BattleUserViewModel"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1BattleUserViewModel\/navigatorTitle","op":"replace"},{"value":"battleUser","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1BattleUserViewModel~1battleUser\/title","op":"replace"},{"value":[{"kind":"identifier","text":"battleUser"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1BattleUserViewModel~1battleUser\/fragments","op":"replace"}]}]}