{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"role":"symbol","externalID":"c:@M@AtomicXCore@objc(cs)CallListStoreImpl","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallListStoreImpl","kind":"identifier"}],"roleHeading":"Class","title":"CallListStoreImpl","navigatorTitle":[{"text":"CallListStoreImpl","kind":"identifier"}],"symbolKind":"class","modules":[{"name":"AtomicXCore"}]},"sections":[],"topicSections":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl\/accept(completion:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl\/calls(participantIds:callMediaType:params:completion:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl\/deleteRecentCalls(callIdList:completion:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl\/hangup(completion:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl\/invite(participantIds:params:completion:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl\/join(callId:completion:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl\/queryRecentCalls(cursor:count:completion:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl\/reject(completion:)"],"anchor":"Instance-Methods"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl\/TUICallObserver-Implementations"],"anchor":"Default-Implementations"}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStore"],"kind":"relationships"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)NSObject","doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)TUICallObserver","doc:\/\/org.cocoapods.AtomicXCore\/s7CVarArgP","doc:\/\/org.cocoapods.AtomicXCore\/s8CopyableP","doc:\/\/org.cocoapods.AtomicXCore\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.AtomicXCore\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.AtomicXCore\/SQ","doc:\/\/org.cocoapods.AtomicXCore\/SH"],"kind":"relationships"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallListStoreImpl"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/callliststoreimpl"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/atomicxcore\/callliststoreimpl"]}],"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallListStoreImpl/reject(completion:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reject","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CompletionClosure","kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea"},{"text":"?)","kind":"text"}],"abstract":[],"title":"reject(completion:)","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl\/reject(completion:)","kind":"symbol","url":"\/documentation\/atomicxcore\/callliststoreimpl\/reject(completion:)","role":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallListStoreImpl/calls(participantIds:callMediaType:params:completion:)":{"abstract":[],"title":"calls(participantIds:callMediaType:params:completion:)","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl\/calls(participantIds:callMediaType:params:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"calls"},{"kind":"text","text":"("},{"kind":"externalParam","text":"participantIds"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"callMediaType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TUICallMediaType","preciseIdentifier":"c:@E@TUICallMediaType"},{"kind":"text","text":", "},{"text":"params","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUICallParams","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUICallParams"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CompletionClosure","kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea"},{"text":"?)","kind":"text"}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/atomicxcore\/callliststoreimpl\/calls(participantids:callmediatype:params:completion:)"},"doc://org.cocoapods.AtomicXCore/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/s7CVarArgP","type":"unresolvable"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallListStoreImpl":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallListStoreImpl"}],"type":"topic","url":"\/documentation\/atomicxcore\/callliststoreimpl","title":"CallListStoreImpl","navigatorTitle":[{"text":"CallListStoreImpl","kind":"identifier"}],"kind":"symbol","abstract":[],"role":"symbol"},"doc://org.cocoapods.AtomicXCore/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/SQ"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallListStoreImpl/invite(participantIds:params:completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"invite"},{"kind":"text","text":"("},{"kind":"externalParam","text":"participantIds"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)TUICallParams","kind":"typeIdentifier","text":"TUICallParams"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","kind":"typeIdentifier","text":"CompletionClosure"},{"kind":"text","text":"?)"}],"abstract":[],"kind":"symbol","title":"invite(participantIds:params:completion:)","url":"\/documentation\/atomicxcore\/callliststoreimpl\/invite(participantids:params:completion:)","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl\/invite(participantIds:params:completion:)","type":"topic","role":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"abstract":[],"title":"AtomicXCore","type":"topic","kind":"symbol","url":"\/documentation\/atomicxcore","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","role":"collection"},"doc://org.cocoapods.AtomicXCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallListStore":{"kind":"symbol","url":"\/documentation\/atomicxcore\/callliststore","title":"CallListStore","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallListStore","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"CallListStore","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallListStoreImpl/deleteRecentCalls(callIdList:completion:)":{"abstract":[],"title":"deleteRecentCalls(callIdList:completion:)","url":"\/documentation\/atomicxcore\/callliststoreimpl\/deleterecentcalls(callidlist:completion:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deleteRecentCalls","kind":"identifier"},{"text":"(","kind":"text"},{"text":"callIdList","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"], ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CompletionClosure","kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea"},{"text":"?)","kind":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl\/deleteRecentCalls(callIdList:completion:)"},"doc://org.cocoapods.AtomicXCore/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/SH"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallListStoreImpl/queryRecentCalls(cursor:count:completion:)":{"title":"queryRecentCalls(cursor:count:completion:)","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl\/queryRecentCalls(cursor:count:completion:)","kind":"symbol","abstract":[],"role":"symbol","type":"topic","url":"\/documentation\/atomicxcore\/callliststoreimpl\/queryrecentcalls(cursor:count:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"queryRecentCalls","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"cursor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"count"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CompletionClosure","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea"},{"kind":"text","text":"?)"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallListStoreImpl/hangup(completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hangup","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","text":"CompletionClosure","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"abstract":[],"kind":"symbol","role":"symbol","url":"\/documentation\/atomicxcore\/callliststoreimpl\/hangup(completion:)","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl\/hangup(completion:)","title":"hangup(completion:)","type":"topic"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallListStoreImpl/TUICallObserver-Implementations":{"url":"\/documentation\/atomicxcore\/callliststoreimpl\/tuicallobserver-implementations","kind":"article","role":"collectionGroup","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl\/TUICallObserver-Implementations","title":"TUICallObserver Implementations"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallListStoreImpl/accept(completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accept","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","text":"CompletionClosure","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"url":"\/documentation\/atomicxcore\/callliststoreimpl\/accept(completion:)","kind":"symbol","role":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl\/accept(completion:)","title":"accept(completion:)"},"doc://org.cocoapods.AtomicXCore/s8CopyableP":{"title":"Swift.Copyable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/s8CopyableP","type":"unresolvable"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallListStoreImpl/join(callId:completion:)":{"kind":"symbol","role":"symbol","abstract":[],"title":"join(callId:completion:)","url":"\/documentation\/atomicxcore\/callliststoreimpl\/join(callid:completion:)","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl\/join(callId:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"join","kind":"identifier"},{"text":"(","kind":"text"},{"text":"callId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","text":"CompletionClosure","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"type":"topic"},"doc://org.cocoapods.AtomicXCore/objc(pl)TUICallObserver":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)TUICallObserver","title":"TUICallObserver","type":"unresolvable"},"doc://org.cocoapods.AtomicXCore/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://org.cocoapods.AtomicXCore/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"CallListStoreImpl","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"CallListStoreImpl"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"CallListStoreImpl"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl\/TUICallObserver-Implementations"],"title":"Default Implementations","generated":true,"anchor":"Default-Implementations"}],"path":"\/topicSections","op":"replace"},{"value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStore"]},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)TUICallObserver"]}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallListStoreImpl"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@AtomicXCore@objc(cs)CallListStore","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStore","text":"CallListStore"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"CallListStoreImpl","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStoreImpl\/title","op":"replace"},{"value":[{"kind":"identifier","text":"CallListStoreImpl"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStoreImpl\/fragments","op":"replace"},{"value":[{"text":"CallListStoreImpl","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStoreImpl\/navigatorTitle","op":"replace"},{"value":"CallListStore","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStore\/title","op":"replace"},{"value":[{"kind":"identifier","text":"CallListStore"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStore\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStore\/navigatorTitle","value":[{"text":"CallListStore","kind":"identifier"}]}]}]}