{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallParticipantStoreImpl"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallParticipantStoreImpl","kind":"identifier"}]}]}],"sections":[],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallParticipantStoreImpl\/TUICallObserver-Implementations"],"generated":true,"anchor":"Default-Implementations","title":"Default Implementations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/callparticipantstoreimpl"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/atomicxcore\/callparticipantstoreimpl"]}],"metadata":{"roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallParticipantStoreImpl"}],"role":"symbol","externalID":"c:@M@AtomicXCore@objc(cs)CallParticipantStoreImpl","navigatorTitle":[{"kind":"identifier","text":"CallParticipantStoreImpl"}],"symbolKind":"class","title":"CallParticipantStoreImpl","modules":[{"name":"AtomicXCore"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore"]]},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallParticipantStore"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)NSObject","doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)TUICallObserver","doc:\/\/org.cocoapods.AtomicXCore\/s7CVarArgP","doc:\/\/org.cocoapods.AtomicXCore\/s8CopyableP","doc:\/\/org.cocoapods.AtomicXCore\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.AtomicXCore\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.AtomicXCore\/SQ","doc:\/\/org.cocoapods.AtomicXCore\/SH"],"type":"conformsTo","title":"Conforms To"}],"references":{"doc://org.cocoapods.AtomicXCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallParticipantStoreImpl":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallParticipantStoreImpl"}],"navigatorTitle":[{"kind":"identifier","text":"CallParticipantStoreImpl"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallParticipantStoreImpl","url":"\/documentation\/atomicxcore\/callparticipantstoreimpl","title":"CallParticipantStoreImpl","role":"symbol","type":"topic","kind":"symbol"},"doc://org.cocoapods.AtomicXCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)NSObject","type":"unresolvable"},"doc://org.cocoapods.AtomicXCore/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/s23CustomStringConvertibleP"},"doc://org.cocoapods.AtomicXCore/s8CopyableP":{"title":"Swift.Copyable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/s8CopyableP","type":"unresolvable"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallParticipantStore":{"title":"CallParticipantStore","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallParticipantStore","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"CallParticipantStore","kind":"identifier"}],"url":"\/documentation\/atomicxcore\/callparticipantstore","abstract":[],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallParticipantStore","role":"symbol","type":"topic"},"doc://org.cocoapods.AtomicXCore/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/s7CVarArgP"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"abstract":[],"title":"AtomicXCore","type":"topic","kind":"symbol","url":"\/documentation\/atomicxcore","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","role":"collection"},"doc://org.cocoapods.AtomicXCore/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/SQ","type":"unresolvable"},"doc://org.cocoapods.AtomicXCore/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/SH"},"doc://org.cocoapods.AtomicXCore/objc(pl)TUICallObserver":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)TUICallObserver","title":"TUICallObserver"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallParticipantStoreImpl/TUICallObserver-Implementations":{"role":"collectionGroup","type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallParticipantStoreImpl\/TUICallObserver-Implementations","abstract":[],"kind":"article","title":"TUICallObserver Implementations","url":"\/documentation\/atomicxcore\/callparticipantstoreimpl\/tuicallobserver-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"CallParticipantStoreImpl"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"CallParticipantStoreImpl","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"CallParticipantStoreImpl","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallParticipantStoreImpl\/TUICallObserver-Implementations"],"title":"Default Implementations","generated":true,"anchor":"Default-Implementations"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallParticipantStore"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)TUICallObserver"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallParticipantStoreImpl","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@M@AtomicXCore@objc(cs)CallParticipantStore","text":"CallParticipantStore","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallParticipantStore","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallParticipantStoreImpl\/title","value":"CallParticipantStoreImpl","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallParticipantStoreImpl\/fragments","value":[{"text":"CallParticipantStoreImpl","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallParticipantStoreImpl\/navigatorTitle","value":[{"text":"CallParticipantStoreImpl","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallParticipantStore\/title","value":"CallParticipantStore","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallParticipantStore\/fragments","value":[{"text":"CallParticipantStore","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallParticipantStore\/navigatorTitle","value":[{"text":"CallParticipantStore","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}