{"sections":[],"abstract":[{"type":"text","text":"************************************** observer ***************************************"}],"topicSections":[{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onConnectedRoomsUpdated(hostUserList:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onConnectedUsersUpdated(userList:joinList:leaveList:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onCrossRoomConnectionAccepted(hostUser:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onCrossRoomConnectionCancelled(hostUser:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onCrossRoomConnectionExited(hostUser:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onCrossRoomConnectionRejected(hostUser:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onCrossRoomConnectionRequest(hostUser:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onCrossRoomConnectionTimeout(inviter:invitee:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onRoomDismissed(roomId:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onUserConnectionAccepted(userInfo:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onUserConnectionCancelled(inviterUser:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onUserConnectionExited(userInfo:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onUserConnectionRejected(userInfo:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onUserConnectionRequest(inviterUser:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onUserConnectionTerminated()","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onUserConnectionTimeout(userInfo:)"],"title":"Instance Methods"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConnectionObserver","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@AtomicXCore@objc(pl)ConnectionObserver","navigatorTitle":[{"kind":"identifier","text":"ConnectionObserver"}],"modules":[{"name":"AtomicXCore"}],"role":"symbol","symbolKind":"protocol","platforms":[{"deprecated":true,"unavailable":false,"beta":false}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConnectionObserver"}],"title":"ConnectionObserver","roleHeading":"Protocol"},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/atomicxcore\/connectionobserver"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/atomicxcore\/connectionobserver"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore"]]},"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConnectionObserver/onCrossRoomConnectionExited(hostUser:)":{"navigatorTitle":[{"kind":"identifier","text":"onCrossRoomConnectionExitedWithHostUser:"}],"abstract":[],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onCrossRoomConnectionExited"},{"kind":"text","text":"("},{"kind":"externalParam","text":"hostUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TUIConnectionUser","preciseIdentifier":"c:objc(cs)TUIConnectionUser"},{"kind":"text","text":")"}],"title":"onCrossRoomConnectionExited(hostUser:)","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onCrossRoomConnectionExited(hostUser:)","deprecated":true,"required":true,"kind":"symbol","url":"\/documentation\/atomicxcore\/connectionobserver\/oncrossroomconnectionexited(hostuser:)"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConnectionObserver/onConnectedRoomsUpdated(hostUserList:)":{"deprecated":true,"kind":"symbol","type":"topic","title":"onConnectedRoomsUpdated(hostUserList:)","required":true,"abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onConnectedRoomsUpdated"},{"kind":"text","text":"("},{"kind":"externalParam","text":"hostUserList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"TUIConnectionUser","preciseIdentifier":"c:objc(cs)TUIConnectionUser"},{"kind":"text","text":"])"}],"url":"\/documentation\/atomicxcore\/connectionobserver\/onconnectedroomsupdated(hostuserlist:)","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onConnectedRoomsUpdated(hostUserList:)","navigatorTitle":[{"kind":"identifier","text":"onConnectedRoomsUpdatedWithHostUserList:"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConnectionObserver":{"kind":"symbol","title":"ConnectionObserver","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConnectionObserver","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver","navigatorTitle":[{"kind":"identifier","text":"ConnectionObserver"}],"deprecated":true,"url":"\/documentation\/atomicxcore\/connectionobserver","abstract":[{"text":"************************************** observer ***************************************","type":"text"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConnectionObserver/onUserConnectionRequest(inviterUser:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onUserConnectionRequest","kind":"identifier"},{"text":"(","kind":"text"},{"text":"inviterUser","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)TUIUserInfo","text":"TUIUserInfo","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"onUserConnectionRequestWithInviterUser:"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onUserConnectionRequest(inviterUser:)","kind":"symbol","abstract":[],"deprecated":true,"url":"\/documentation\/atomicxcore\/connectionobserver\/onuserconnectionrequest(inviteruser:)","title":"onUserConnectionRequest(inviterUser:)","required":true,"role":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConnectionObserver/onCrossRoomConnectionRequest(hostUser:)":{"deprecated":true,"url":"\/documentation\/atomicxcore\/connectionobserver\/oncrossroomconnectionrequest(hostuser:)","role":"symbol","title":"onCrossRoomConnectionRequest(hostUser:)","kind":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onCrossRoomConnectionRequest","kind":"identifier"},{"text":"(","kind":"text"},{"text":"hostUser","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)TUIConnectionUser","text":"TUIConnectionUser","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onCrossRoomConnectionRequest(hostUser:)","type":"topic","navigatorTitle":[{"text":"onCrossRoomConnectionRequestWithHostUser:","kind":"identifier"}],"required":true},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConnectionObserver/onUserConnectionExited(userInfo:)":{"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserConnectionExited"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TUIUserInfo","preciseIdentifier":"c:objc(cs)TUIUserInfo"},{"kind":"text","text":")"}],"title":"onUserConnectionExited(userInfo:)","abstract":[],"required":true,"url":"\/documentation\/atomicxcore\/connectionobserver\/onuserconnectionexited(userinfo:)","navigatorTitle":[{"kind":"identifier","text":"onUserConnectionExitedWithUserInfo:"}],"deprecated":true,"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onUserConnectionExited(userInfo:)"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConnectionObserver/onCrossRoomConnectionTimeout(inviter:invitee:)":{"type":"topic","title":"onCrossRoomConnectionTimeout(inviter:invitee:)","required":true,"deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"onCrossRoomConnectionTimeoutWithInviter:invitee:"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onCrossRoomConnectionTimeout(inviter:invitee:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onCrossRoomConnectionTimeout","kind":"identifier"},{"text":"(","kind":"text"},{"text":"inviter","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUIConnectionUser","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIConnectionUser"},{"text":", ","kind":"text"},{"text":"invitee","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUIConnectionUser","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIConnectionUser"},{"text":")","kind":"text"}],"abstract":[],"url":"\/documentation\/atomicxcore\/connectionobserver\/oncrossroomconnectiontimeout(inviter:invitee:)"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConnectionObserver/onUserConnectionCancelled(inviterUser:)":{"deprecated":true,"url":"\/documentation\/atomicxcore\/connectionobserver\/onuserconnectioncancelled(inviteruser:)","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onUserConnectionCancelled(inviterUser:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserConnectionCancelled"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inviterUser"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)TUIUserInfo","kind":"typeIdentifier","text":"TUIUserInfo"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"onUserConnectionCancelledWithInviterUser:"}],"abstract":[],"kind":"symbol","type":"topic","title":"onUserConnectionCancelled(inviterUser:)","required":true,"role":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConnectionObserver/onRoomDismissed(roomId:)":{"type":"topic","url":"\/documentation\/atomicxcore\/connectionobserver\/onroomdismissed(roomid:)","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onRoomDismissed(roomId:)","required":true,"role":"symbol","deprecated":true,"title":"onRoomDismissed(roomId:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onRoomDismissed","kind":"identifier"},{"text":"(","kind":"text"},{"text":"roomId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"abstract":[],"navigatorTitle":[{"text":"onRoomDismissedWithRoomId:","kind":"identifier"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"url":"\/documentation\/atomicxcore","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","type":"topic","kind":"symbol","abstract":[],"role":"collection"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConnectionObserver/onCrossRoomConnectionRejected(hostUser:)":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onCrossRoomConnectionRejected(hostUser:)","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"onCrossRoomConnectionRejectedWithHostUser:"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onCrossRoomConnectionRejected"},{"kind":"text","text":"("},{"kind":"externalParam","text":"hostUser"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)TUIConnectionUser","kind":"typeIdentifier","text":"TUIConnectionUser"},{"kind":"text","text":")"}],"deprecated":true,"abstract":[],"required":true,"title":"onCrossRoomConnectionRejected(hostUser:)","url":"\/documentation\/atomicxcore\/connectionobserver\/oncrossroomconnectionrejected(hostuser:)"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConnectionObserver/onUserConnectionAccepted(userInfo:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserConnectionAccepted"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userInfo"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)TUIUserInfo","kind":"typeIdentifier","text":"TUIUserInfo"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"onUserConnectionAcceptedWithUserInfo:"}],"kind":"symbol","role":"symbol","deprecated":true,"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onUserConnectionAccepted(userInfo:)","title":"onUserConnectionAccepted(userInfo:)","abstract":[],"url":"\/documentation\/atomicxcore\/connectionobserver\/onuserconnectionaccepted(userinfo:)","type":"topic","required":true},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConnectionObserver/onUserConnectionTerminated()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserConnectionTerminated"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"onUserConnectionTerminated"}],"role":"symbol","deprecated":true,"kind":"symbol","required":true,"url":"\/documentation\/atomicxcore\/connectionobserver\/onuserconnectionterminated()","abstract":[],"title":"onUserConnectionTerminated()","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onUserConnectionTerminated()","type":"topic"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConnectionObserver/onUserConnectionRejected(userInfo:)":{"navigatorTitle":[{"kind":"identifier","text":"onUserConnectionRejectedWithUserInfo:"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserConnectionRejected"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TUIUserInfo","preciseIdentifier":"c:objc(cs)TUIUserInfo"},{"kind":"text","text":")"}],"url":"\/documentation\/atomicxcore\/connectionobserver\/onuserconnectionrejected(userinfo:)","required":true,"role":"symbol","deprecated":true,"title":"onUserConnectionRejected(userInfo:)","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onUserConnectionRejected(userInfo:)"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConnectionObserver/onCrossRoomConnectionAccepted(hostUser:)":{"kind":"symbol","type":"topic","abstract":[],"title":"onCrossRoomConnectionAccepted(hostUser:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onCrossRoomConnectionAccepted"},{"kind":"text","text":"("},{"kind":"externalParam","text":"hostUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TUIConnectionUser","preciseIdentifier":"c:objc(cs)TUIConnectionUser"},{"kind":"text","text":")"}],"deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"onCrossRoomConnectionAcceptedWithHostUser:"}],"required":true,"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onCrossRoomConnectionAccepted(hostUser:)","url":"\/documentation\/atomicxcore\/connectionobserver\/oncrossroomconnectionaccepted(hostuser:)"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConnectionObserver/onConnectedUsersUpdated(userList:joinList:leaveList:)":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onConnectedUsersUpdated(userList:joinList:leaveList:)","required":true,"title":"onConnectedUsersUpdated(userList:joinList:leaveList:)","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onConnectedUsersUpdated"},{"kind":"text","text":"("},{"text":"userList","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"TUIUserInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIUserInfo"},{"text":"], ","kind":"text"},{"text":"joinList","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"TUIUserInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIUserInfo"},{"text":"], ","kind":"text"},{"text":"leaveList","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"TUIUserInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIUserInfo"},{"text":"])","kind":"text"}],"url":"\/documentation\/atomicxcore\/connectionobserver\/onconnectedusersupdated(userlist:joinlist:leavelist:)","navigatorTitle":[{"text":"onConnectedUsersUpdatedWithUserList:joinList:leaveList:","kind":"identifier"}],"kind":"symbol","type":"topic","deprecated":true},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConnectionObserver/onCrossRoomConnectionCancelled(hostUser:)":{"deprecated":true,"title":"onCrossRoomConnectionCancelled(hostUser:)","url":"\/documentation\/atomicxcore\/connectionobserver\/oncrossroomconnectioncancelled(hostuser:)","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onCrossRoomConnectionCancelled(hostUser:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onCrossRoomConnectionCancelled"},{"kind":"text","text":"("},{"kind":"externalParam","text":"hostUser"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)TUIConnectionUser","kind":"typeIdentifier","text":"TUIConnectionUser"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"onCrossRoomConnectionCancelledWithHostUser:"}],"type":"topic","kind":"symbol","abstract":[],"role":"symbol","required":true},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConnectionObserver/onUserConnectionTimeout(userInfo:)":{"kind":"symbol","abstract":[],"deprecated":true,"title":"onUserConnectionTimeout(userInfo:)","required":true,"role":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onUserConnectionTimeout(userInfo:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onUserConnectionTimeout","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUIUserInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIUserInfo"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"onUserConnectionTimeoutWithUserInfo:","kind":"identifier"}],"url":"\/documentation\/atomicxcore\/connectionobserver\/onuserconnectiontimeout(userinfo:)","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":[{"deprecated":true,"unavailable":false,"beta":false}],"path":"\/metadata\/platforms"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"op":"replace","value":"ConnectionObserver","path":"\/metadata\/title"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"ConnectionObserver","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"ConnectionObserver","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onConnectedRoomsUpdated(hostUserList:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onConnectedUsersUpdated(userList:joinList:leaveList:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onCrossRoomConnectionAccepted(hostUser:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onCrossRoomConnectionCancelled(hostUser:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onCrossRoomConnectionExited(hostUser:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onCrossRoomConnectionRejected(hostUser:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onCrossRoomConnectionRequest(hostUser:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onCrossRoomConnectionTimeout(inviter:invitee:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onRoomDismissed(roomId:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onUserConnectionAccepted(userInfo:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onUserConnectionCancelled(inviterUser:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onUserConnectionExited(userInfo:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onUserConnectionRejected(userInfo:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onUserConnectionRequest(inviterUser:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onUserConnectionTerminated()","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onUserConnectionTimeout(userInfo:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConnectionObserver","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"onCrossRoomConnectionExitedWithHostUser:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onCrossRoomConnectionExited(hostUser:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"onCrossRoomConnectionExitedWithHostUser:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onCrossRoomConnectionExited(hostUser:)\/fragments"},{"value":"onConnectedRoomsUpdatedWithHostUserList:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onConnectedRoomsUpdated(hostUserList:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onConnectedRoomsUpdatedWithHostUserList:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onConnectedRoomsUpdated(hostUserList:)\/fragments"},{"value":"ConnectionObserver","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver\/title"},{"value":[{"kind":"identifier","text":"ConnectionObserver"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver\/fragments"},{"value":[{"kind":"identifier","text":"ConnectionObserver"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver\/navigatorTitle"},{"value":"onUserConnectionRequestWithInviterUser:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onUserConnectionRequest(inviterUser:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"onUserConnectionRequestWithInviterUser:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onUserConnectionRequest(inviterUser:)\/fragments"},{"value":"onCrossRoomConnectionRequestWithHostUser:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onCrossRoomConnectionRequest(hostUser:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onCrossRoomConnectionRequestWithHostUser:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onCrossRoomConnectionRequest(hostUser:)\/fragments"},{"op":"replace","value":"onUserConnectionExitedWithUserInfo:","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onUserConnectionExited(userInfo:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onUserConnectionExitedWithUserInfo:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onUserConnectionExited(userInfo:)\/fragments"},{"op":"replace","value":"onCrossRoomConnectionTimeoutWithInviter:invitee:","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onCrossRoomConnectionTimeout(inviter:invitee:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onCrossRoomConnectionTimeoutWithInviter:invitee:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onCrossRoomConnectionTimeout(inviter:invitee:)\/fragments"},{"op":"replace","value":"onUserConnectionCancelledWithInviterUser:","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onUserConnectionCancelled(inviterUser:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onUserConnectionCancelledWithInviterUser:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onUserConnectionCancelled(inviterUser:)\/fragments"},{"op":"replace","value":"onRoomDismissedWithRoomId:","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onRoomDismissed(roomId:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onRoomDismissedWithRoomId:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onRoomDismissed(roomId:)\/fragments"},{"op":"replace","value":"onCrossRoomConnectionRejectedWithHostUser:","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onCrossRoomConnectionRejected(hostUser:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onCrossRoomConnectionRejectedWithHostUser:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onCrossRoomConnectionRejected(hostUser:)\/fragments"},{"op":"replace","value":"onUserConnectionAcceptedWithUserInfo:","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onUserConnectionAccepted(userInfo:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onUserConnectionAcceptedWithUserInfo:"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onUserConnectionAccepted(userInfo:)\/fragments"},{"op":"replace","value":"onUserConnectionTerminated","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onUserConnectionTerminated()\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onUserConnectionTerminated"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onUserConnectionTerminated()\/fragments"},{"op":"replace","value":"onUserConnectionRejectedWithUserInfo:","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onUserConnectionRejected(userInfo:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onUserConnectionRejectedWithUserInfo:"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onUserConnectionRejected(userInfo:)\/fragments"},{"op":"replace","value":"onCrossRoomConnectionAcceptedWithHostUser:","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onCrossRoomConnectionAccepted(hostUser:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onCrossRoomConnectionAcceptedWithHostUser:"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onCrossRoomConnectionAccepted(hostUser:)\/fragments"},{"op":"replace","value":"onConnectedUsersUpdatedWithUserList:joinList:leaveList:","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onConnectedUsersUpdated(userList:joinList:leaveList:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onConnectedUsersUpdatedWithUserList:joinList:leaveList:"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onConnectedUsersUpdated(userList:joinList:leaveList:)\/fragments"},{"op":"replace","value":"onCrossRoomConnectionCancelledWithHostUser:","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onCrossRoomConnectionCancelled(hostUser:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onCrossRoomConnectionCancelledWithHostUser:"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onCrossRoomConnectionCancelled(hostUser:)\/fragments"},{"op":"replace","value":"onUserConnectionTimeoutWithUserInfo:","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onUserConnectionTimeout(userInfo:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onUserConnectionTimeoutWithUserInfo:"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onUserConnectionTimeout(userInfo:)\/fragments"}]}]}