{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/conversationliststore"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/atomicxcore\/conversationliststore"]}],"sections":[],"metadata":{"modules":[{"name":"AtomicXCore"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationListStore"}],"symbolKind":"class","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConversationListStore"}],"roleHeading":"Class","externalID":"c:@M@AtomicXCore@objc(cs)ConversationListStore","title":"ConversationListStore"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStore"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationListStore","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStore\/state"],"anchor":"Instance-Properties","generated":true},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStore\/clearConversationMessages(_:completion:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStore\/clearConversationUnreadCount(_:completion:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStore\/deleteConversation(_:completion:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStore\/fetchConversationInfo(_:completion:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStore\/fetchConversationList(_:completion:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStore\/fetchMoreConversationList(completion:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStore\/getConversationTotalUnreadCount(completion:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStore\/markConversationUnread(_:unread:completion:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStore\/muteConversation(_:mute:completion:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStore\/pinConversation(_:pin:completion:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStore\/setConversationDraft(_:draft:completion:)"],"anchor":"Instance-Methods","generated":true},{"identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStore\/create()"],"title":"Type Methods","generated":true,"anchor":"Type-Methods"}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"},{"type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)NSObject","doc:\/\/org.cocoapods.AtomicXCore\/s7CVarArgP","doc:\/\/org.cocoapods.AtomicXCore\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.AtomicXCore\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.AtomicXCore\/SQ","doc:\/\/org.cocoapods.AtomicXCore\/SH"],"title":"Conforms To","kind":"relationships"}],"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConversationListStore/setConversationDraft(_:draft:completion:)":{"type":"topic","title":"setConversationDraft(_:draft:completion:)","abstract":[],"role":"symbol","url":"\/documentation\/atomicxcore\/conversationliststore\/setconversationdraft(_:draft:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setConversationDraft"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"draft"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"text":"CompletionClosure","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStore\/setConversationDraft(_:draft:completion:)"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConversationListStore/deleteConversation(_:completion:)":{"url":"\/documentation\/atomicxcore\/conversationliststore\/deleteconversation(_:completion:)","title":"deleteConversation(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteConversation"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","text":"CompletionClosure"},{"kind":"text","text":"?)"}],"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStore\/deleteConversation(_:completion:)","kind":"symbol","abstract":[]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConversationListStore/fetchConversationList(_:completion:)":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStore\/fetchConversationList(_:completion:)","url":"\/documentation\/atomicxcore\/conversationliststore\/fetchconversationlist(_:completion:)","abstract":[],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fetchConversationList","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ConversationFetchOption","preciseIdentifier":"s:11AtomicXCore23ConversationFetchOptionV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CompletionClosure","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"kind":"symbol","title":"fetchConversationList(_:completion:)","role":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConversationListStore/fetchMoreConversationList(completion:)":{"title":"fetchMoreConversationList(completion:)","type":"topic","abstract":[],"role":"symbol","url":"\/documentation\/atomicxcore\/conversationliststore\/fetchmoreconversationlist(completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fetchMoreConversationList","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CompletionClosure","kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea"},{"text":"?)","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStore\/fetchMoreConversationList(completion:)"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConversationListStore":{"navigatorTitle":[{"kind":"identifier","text":"ConversationListStore"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationListStore"}],"abstract":[],"url":"\/documentation\/atomicxcore\/conversationliststore","role":"symbol","type":"topic","title":"ConversationListStore","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConversationListStore/create()":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@M@AtomicXCore@objc(cs)ConversationListStore","kind":"typeIdentifier","text":"ConversationListStore"}],"abstract":[],"url":"\/documentation\/atomicxcore\/conversationliststore\/create()","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStore\/create()","title":"create()","kind":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConversationListStore/fetchConversationInfo(_:completion:)":{"title":"fetchConversationInfo(_:completion:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStore\/fetchConversationInfo(_:completion:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fetchConversationInfo","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","text":"CompletionClosure","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"url":"\/documentation\/atomicxcore\/conversationliststore\/fetchconversationinfo(_:completion:)","abstract":[]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConversationListStore/pinConversation(_:pin:completion:)":{"title":"pinConversation(_:pin:completion:)","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStore\/pinConversation(_:pin:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pinConversation"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CompletionClosure","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea"},{"kind":"text","text":"?)"}],"role":"symbol","url":"\/documentation\/atomicxcore\/conversationliststore\/pinconversation(_:pin:completion:)","kind":"symbol"},"doc://org.cocoapods.AtomicXCore/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(cs)NSObject"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConversationListStore/getConversationTotalUnreadCount(completion:)":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStore\/getConversationTotalUnreadCount(completion:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getConversationTotalUnreadCount"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CompletionClosure","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea"},{"kind":"text","text":"?)"}],"url":"\/documentation\/atomicxcore\/conversationliststore\/getconversationtotalunreadcount(completion:)","role":"symbol","title":"getConversationTotalUnreadCount(completion:)","abstract":[]},"doc://org.cocoapods.AtomicXCore/SH":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://org.cocoapods.AtomicXCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)NSObject","type":"unresolvable"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConversationListStore/state":{"title":"state","abstract":[],"role":"symbol","url":"\/documentation\/atomicxcore\/conversationliststore\/state","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"state"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11AtomicXCore14StatePublisherC","kind":"typeIdentifier","text":"StatePublisher"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:11AtomicXCore21ConversationListStateC","kind":"typeIdentifier","text":"ConversationListState"},{"kind":"text","text":">"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStore\/state","kind":"symbol"},"doc://org.cocoapods.AtomicXCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://org.cocoapods.AtomicXCore/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://org.cocoapods.AtomicXCore/SQ":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConversationListStore/markConversationUnread(_:unread:completion:)":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStore\/markConversationUnread(_:unread:completion:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"markConversationUnread","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"unread","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CompletionClosure","kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea"},{"text":"?)","kind":"text"}],"title":"markConversationUnread(_:unread:completion:)","abstract":[],"type":"topic","url":"\/documentation\/atomicxcore\/conversationliststore\/markconversationunread(_:unread:completion:)","role":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConversationListStore/muteConversation(_:mute:completion:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"muteConversation"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mute"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CompletionClosure","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea"},{"kind":"text","text":"?)"}],"url":"\/documentation\/atomicxcore\/conversationliststore\/muteconversation(_:mute:completion:)","title":"muteConversation(_:mute:completion:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStore\/muteConversation(_:mute:completion:)","type":"topic","abstract":[]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"abstract":[],"title":"AtomicXCore","type":"topic","kind":"symbol","url":"\/documentation\/atomicxcore","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","role":"collection"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConversationListStore/clearConversationMessages(_:completion:)":{"kind":"symbol","abstract":[],"url":"\/documentation\/atomicxcore\/conversationliststore\/clearconversationmessages(_:completion:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStore\/clearConversationMessages(_:completion:)","title":"clearConversationMessages(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearConversationMessages"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","text":"CompletionClosure"},{"kind":"text","text":"?)"}],"type":"topic"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConversationListStore/clearConversationUnreadCount(_:completion:)":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStore\/clearConversationUnreadCount(_:completion:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clearConversationUnreadCount","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CompletionClosure","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"title":"clearConversationUnreadCount(_:completion:)","abstract":[],"type":"topic","url":"\/documentation\/atomicxcore\/conversationliststore\/clearconversationunreadcount(_:completion:)","role":"symbol"},"doc://org.cocoapods.AtomicXCore/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/s7CVarArgP","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"ConversationListStore"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"ConversationListStore","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"ConversationListStore","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":null},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/objc(cs)NSObject"],"title":"Inherits From"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationListStore","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConversationListStore\/title","op":"replace","value":"ConversationListStore"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConversationListStore\/fragments","op":"replace","value":[{"kind":"identifier","text":"ConversationListStore"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConversationListStore\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ConversationListStore"}]}]}]}