{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore"]]},"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/groupsettingstore"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/atomicxcore\/groupsettingstore"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","metadata":{"roleHeading":"Class","modules":[{"name":"AtomicXCore"}],"symbolKind":"class","title":"GroupSettingStore","navigatorTitle":[{"kind":"identifier","text":"GroupSettingStore"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupSettingStore"}],"role":"symbol","externalID":"c:@M@AtomicXCore@objc(cs)GroupSettingStore"},"sections":[],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)NSObject","doc:\/\/org.cocoapods.AtomicXCore\/s7CVarArgP","doc:\/\/org.cocoapods.AtomicXCore\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.AtomicXCore\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.AtomicXCore\/SQ","doc:\/\/org.cocoapods.AtomicXCore\/SH"],"type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GroupSettingStore","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore\/groupID","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore\/state"],"anchor":"Instance-Properties","generated":true},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore\/addGroupMember(userIDList:completion:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore\/changeGroupOwner(newOwnerID:completion:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore\/deleteGroupMember(members:completion:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore\/dismissGroup(completion:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore\/fetchGroupInfo(completion:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore\/fetchGroupMemberList(role:completion:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore\/fetchMoreGroupMemberList(completion:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore\/fetchSelfMemberInfo(completion:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore\/quitGroup(completion:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore\/setGroupInviteOption(option:completion:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore\/setGroupJoinOption(option:completion:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore\/setGroupMemberMuteTime(userID:time:completion:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore\/setGroupMemberRole(userID:role:completion:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore\/setMuteAllMembers(value:completion:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore\/setSelfGroupNameCard(nameCard:completion:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore\/updateGroupProfile(name:notice:avatar:completion:)"],"anchor":"Instance-Methods","generated":true},{"title":"Type Methods","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore\/create(groupID:)"],"anchor":"Type-Methods","generated":true}],"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/GroupSettingStore/setGroupMemberRole(userID:role:completion:)":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore\/setGroupMemberRole(userID:role:completion:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setGroupMemberRole"},{"kind":"text","text":"("},{"text":"userID","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"role","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GroupMemberRole","preciseIdentifier":"s:11AtomicXCore15GroupMemberRoleO","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CompletionClosure","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"type":"topic","url":"\/documentation\/atomicxcore\/groupsettingstore\/setgroupmemberrole(userid:role:completion:)","title":"setGroupMemberRole(userID:role:completion:)"},"doc://org.cocoapods.AtomicXCore/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/s7CVarArgP"},"doc://org.cocoapods.AtomicXCore/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/SH"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/GroupSettingStore/create(groupID:)":{"kind":"symbol","title":"create(groupID:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"groupID"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@AtomicXCore@objc(cs)GroupSettingStore","kind":"typeIdentifier","text":"GroupSettingStore"}],"type":"topic","url":"\/documentation\/atomicxcore\/groupsettingstore\/create(groupid:)","role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore\/create(groupID:)"},"doc://org.cocoapods.AtomicXCore/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/GroupSettingStore":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupSettingStore"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupSettingStore"}],"title":"GroupSettingStore","abstract":[],"role":"symbol","url":"\/documentation\/atomicxcore\/groupsettingstore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/GroupSettingStore/quitGroup(completion:)":{"url":"\/documentation\/atomicxcore\/groupsettingstore\/quitgroup(completion:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"quitGroup"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","text":"CompletionClosure"},{"kind":"text","text":"?)"}],"title":"quitGroup(completion:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore\/quitGroup(completion:)","abstract":[],"type":"topic"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/GroupSettingStore/fetchSelfMemberInfo(completion:)":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore\/fetchSelfMemberInfo(completion:)","title":"fetchSelfMemberInfo(completion:)","role":"symbol","url":"\/documentation\/atomicxcore\/groupsettingstore\/fetchselfmemberinfo(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchSelfMemberInfo"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","text":"CompletionClosure"},{"kind":"text","text":"?)"}],"type":"topic","abstract":[]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/GroupSettingStore/setMuteAllMembers(value:completion:)":{"role":"symbol","type":"topic","kind":"symbol","title":"setMuteAllMembers(value:completion:)","abstract":[],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore\/setMuteAllMembers(value:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setMuteAllMembers","kind":"identifier"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","text":"CompletionClosure","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"url":"\/documentation\/atomicxcore\/groupsettingstore\/setmuteallmembers(value:completion:)"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/GroupSettingStore/dismissGroup(completion:)":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore\/dismissGroup(completion:)","type":"topic","title":"dismissGroup(completion:)","abstract":[],"url":"\/documentation\/atomicxcore\/groupsettingstore\/dismissgroup(completion:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dismissGroup","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","text":"CompletionClosure","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/GroupSettingStore/fetchMoreGroupMemberList(completion:)":{"url":"\/documentation\/atomicxcore\/groupsettingstore\/fetchmoregroupmemberlist(completion:)","type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore\/fetchMoreGroupMemberList(completion:)","title":"fetchMoreGroupMemberList(completion:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchMoreGroupMemberList"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","kind":"typeIdentifier","text":"CompletionClosure"},{"kind":"text","text":"?)"}],"abstract":[]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/GroupSettingStore/setGroupJoinOption(option:completion:)":{"url":"\/documentation\/atomicxcore\/groupsettingstore\/setgroupjoinoption(option:completion:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setGroupJoinOption"},{"kind":"text","text":"("},{"kind":"externalParam","text":"option"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore15GroupJoinOptionO","text":"GroupJoinOption"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","text":"CompletionClosure"},{"kind":"text","text":"?)"}],"title":"setGroupJoinOption(option:completion:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore\/setGroupJoinOption(option:completion:)","abstract":[],"type":"topic"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/GroupSettingStore/fetchGroupMemberList(role:completion:)":{"title":"fetchGroupMemberList(role:completion:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fetchGroupMemberList","kind":"identifier"},{"text":"(","kind":"text"},{"text":"role","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GroupMemberRole","kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore15GroupMemberRoleO"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CompletionClosure","kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore\/fetchGroupMemberList(role:completion:)","type":"topic","url":"\/documentation\/atomicxcore\/groupsettingstore\/fetchgroupmemberlist(role:completion:)","abstract":[]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"abstract":[],"title":"AtomicXCore","type":"topic","kind":"symbol","url":"\/documentation\/atomicxcore","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","role":"collection"},"doc://org.cocoapods.AtomicXCore/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(cs)NSObject"},"doc://org.cocoapods.AtomicXCore/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/SQ"},"doc://org.cocoapods.AtomicXCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/s23CustomStringConvertibleP"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/GroupSettingStore/deleteGroupMember(members:completion:)":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore\/deleteGroupMember(members:completion:)","kind":"symbol","type":"topic","title":"deleteGroupMember(members:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deleteGroupMember","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"members"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GroupMember","preciseIdentifier":"s:11AtomicXCore11GroupMemberV"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"text":"CompletionClosure","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"url":"\/documentation\/atomicxcore\/groupsettingstore\/deletegroupmember(members:completion:)","role":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/GroupSettingStore/groupID":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore\/groupID","url":"\/documentation\/atomicxcore\/groupsettingstore\/groupid","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"groupID","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"type":"topic","title":"groupID"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/GroupSettingStore/changeGroupOwner(newOwnerID:completion:)":{"type":"topic","abstract":[],"title":"changeGroupOwner(newOwnerID:completion:)","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore\/changeGroupOwner(newOwnerID:completion:)","url":"\/documentation\/atomicxcore\/groupsettingstore\/changegroupowner(newownerid:completion:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"changeGroupOwner","kind":"identifier"},{"text":"(","kind":"text"},{"text":"newOwnerID","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","text":"CompletionClosure","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"role":"symbol"},"doc://org.cocoapods.AtomicXCore/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)NSObject"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/GroupSettingStore/setGroupMemberMuteTime(userID:time:completion:)":{"title":"setGroupMemberMuteTime(userID:time:completion:)","role":"symbol","abstract":[],"kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setGroupMemberMuteTime","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userID","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"time","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","text":"CompletionClosure","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"url":"\/documentation\/atomicxcore\/groupsettingstore\/setgroupmembermutetime(userid:time:completion:)","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore\/setGroupMemberMuteTime(userID:time:completion:)"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/GroupSettingStore/state":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore\/state","title":"state","url":"\/documentation\/atomicxcore\/groupsettingstore\/state","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"state","kind":"identifier"},{"text":": ","kind":"text"},{"text":"StatePublisher","kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore14StatePublisherC"},{"text":"<","kind":"text"},{"text":"GroupSettingState","kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore17GroupSettingStateV"},{"text":">","kind":"text"}],"kind":"symbol","type":"topic","abstract":[],"role":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/GroupSettingStore/fetchGroupInfo(completion:)":{"type":"topic","title":"fetchGroupInfo(completion:)","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore\/fetchGroupInfo(completion:)","url":"\/documentation\/atomicxcore\/groupsettingstore\/fetchgroupinfo(completion:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fetchGroupInfo","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CompletionClosure","kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea"},{"text":"?)","kind":"text"}],"abstract":[],"role":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/GroupSettingStore/addGroupMember(userIDList:completion:)":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore\/addGroupMember(userIDList:completion:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addGroupMember"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userIDList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","text":"CompletionClosure"},{"kind":"text","text":"?)"}],"title":"addGroupMember(userIDList:completion:)","abstract":[],"role":"symbol","url":"\/documentation\/atomicxcore\/groupsettingstore\/addgroupmember(useridlist:completion:)"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/GroupSettingStore/setGroupInviteOption(option:completion:)":{"url":"\/documentation\/atomicxcore\/groupsettingstore\/setgroupinviteoption(option:completion:)","title":"setGroupInviteOption(option:completion:)","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore\/setGroupInviteOption(option:completion:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setGroupInviteOption","kind":"identifier"},{"text":"(","kind":"text"},{"text":"option","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GroupJoinOption","preciseIdentifier":"s:11AtomicXCore15GroupJoinOptionO","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CompletionClosure","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"type":"topic"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/GroupSettingStore/setSelfGroupNameCard(nameCard:completion:)":{"title":"setSelfGroupNameCard(nameCard:completion:)","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore\/setSelfGroupNameCard(nameCard:completion:)","abstract":[],"url":"\/documentation\/atomicxcore\/groupsettingstore\/setselfgroupnamecard(namecard:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setSelfGroupNameCard"},{"kind":"text","text":"("},{"kind":"externalParam","text":"nameCard"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","text":"CompletionClosure"},{"kind":"text","text":"?)"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/GroupSettingStore/updateGroupProfile(name:notice:avatar:completion:)":{"abstract":[],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateGroupProfile"},{"kind":"text","text":"("},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"notice"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"avatar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","text":"CompletionClosure"},{"kind":"text","text":"?)"}],"url":"\/documentation\/atomicxcore\/groupsettingstore\/updategroupprofile(name:notice:avatar:completion:)","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupSettingStore\/updateGroupProfile(name:notice:avatar:completion:)","type":"topic","title":"updateGroupProfile(name:notice:avatar:completion:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"GroupSettingStore","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"GroupSettingStore","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GroupSettingStore"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"replace"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}],"op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GroupSettingStore","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1GroupSettingStore\/title","op":"replace","value":"GroupSettingStore"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1GroupSettingStore\/fragments","op":"replace","value":[{"text":"GroupSettingStore","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1GroupSettingStore\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GroupSettingStore"}]}]}]}