{"sections":[],"relationshipsSections":[{"type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/SQ","doc:\/\/org.cocoapods.AtomicXCore\/SH","doc:\/\/org.cocoapods.AtomicXCore\/SY"],"title":"Conforms To","kind":"relationships"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/layoutmode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/atomicxcore\/layoutmode"]}],"metadata":{"platforms":[{"beta":false,"unavailable":false,"deprecated":true}],"modules":[{"name":"AtomicXCore"}],"symbolKind":"enum","role":"symbol","roleHeading":"Enumeration","navigatorTitle":[{"kind":"identifier","text":"LayoutMode"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LayoutMode"}],"title":"LayoutMode","externalID":"c:@M@AtomicXCore@E@LayoutMode"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LayoutMode","kind":"identifier"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore"]]},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LayoutMode\/floatLayout","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LayoutMode\/freeLayout","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LayoutMode\/gridLayout"],"title":"Enumeration Cases","anchor":"Enumeration-Cases","generated":true},{"identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LayoutMode\/init(rawValue:)"],"title":"Initializers","anchor":"Initializers","generated":true},{"identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LayoutMode\/Equatable-Implementations","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LayoutMode\/RawRepresentable-Implementations"],"title":"Default Implementations","anchor":"Default-Implementations","generated":true}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LayoutMode"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.AtomicXCore/SY":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://org.cocoapods.AtomicXCore/SQ":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LayoutMode/Equatable-Implementations":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LayoutMode\/Equatable-Implementations","title":"Equatable Implementations","url":"\/documentation\/atomicxcore\/layoutmode\/equatable-implementations","role":"collectionGroup","type":"topic","kind":"article"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LayoutMode/RawRepresentable-Implementations":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LayoutMode\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","url":"\/documentation\/atomicxcore\/layoutmode\/rawrepresentable-implementations","role":"collectionGroup","type":"topic","kind":"article"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LayoutMode/init(rawValue:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LayoutMode\/init(rawValue:)","deprecated":true,"title":"init(rawValue:)","url":"\/documentation\/atomicxcore\/layoutmode\/init(rawvalue:)","role":"symbol","type":"topic","kind":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LayoutMode/freeLayout":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LayoutMode\/freeLayout","role":"symbol","type":"topic","kind":"symbol","title":"LayoutMode.freeLayout","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"freeLayout"}],"navigatorTitle":[{"text":"LayoutModeFreeLayout","kind":"identifier"}],"abstract":[],"url":"\/documentation\/atomicxcore\/layoutmode\/freelayout","deprecated":true},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LayoutMode":{"abstract":[],"kind":"symbol","url":"\/documentation\/atomicxcore\/layoutmode","title":"LayoutMode","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LayoutMode","kind":"identifier"}],"navigatorTitle":[{"text":"LayoutMode","kind":"identifier"}],"deprecated":true,"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LayoutMode"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"kind":"symbol","abstract":[],"type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/SH":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LayoutMode/gridLayout":{"url":"\/documentation\/atomicxcore\/layoutmode\/gridlayout","navigatorTitle":[{"text":"LayoutModeGridLayout","kind":"identifier"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gridLayout","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LayoutMode\/gridLayout","title":"LayoutMode.gridLayout","kind":"symbol","deprecated":true,"abstract":[]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LayoutMode/floatLayout":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"floatLayout","kind":"identifier"}],"type":"topic","abstract":[],"title":"LayoutMode.floatLayout","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LayoutMode\/floatLayout","deprecated":true,"role":"symbol","url":"\/documentation\/atomicxcore\/layoutmode\/floatlayout","navigatorTitle":[{"text":"LayoutModeFloatLayout","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","value":"LayoutMode","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"LayoutMode","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"LayoutMode"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LayoutMode\/floatLayout","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LayoutMode\/freeLayout","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LayoutMode\/gridLayout"],"generated":true,"anchor":"Enumeration-Cases"}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LayoutMode","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/deprecationSummary","value":[],"op":"add"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LayoutMode~1freeLayout\/title","value":"LayoutModeFreeLayout","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LayoutMode~1freeLayout\/fragments","value":[{"kind":"identifier","text":"LayoutModeFreeLayout"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LayoutMode\/title","value":"LayoutMode","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LayoutMode\/fragments","value":[{"text":"LayoutMode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LayoutMode\/navigatorTitle","value":[{"text":"LayoutMode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LayoutMode~1gridLayout\/title","value":"LayoutModeGridLayout","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LayoutMode~1gridLayout\/fragments","value":[{"text":"LayoutModeGridLayout","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LayoutMode~1floatLayout\/title","value":"LayoutModeFloatLayout","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LayoutMode~1floatLayout\/fragments","value":[{"kind":"identifier","text":"LayoutModeFloatLayout"}],"op":"replace"}]}]}