{"variants":[{"paths":["\/documentation\/atomicxcore\/livecoreview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/atomicxcore\/livecoreview"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView","interfaceLanguage":"swift"},"metadata":{"title":"LiveCoreView","roleHeading":"Class","externalID":"c:@M@AtomicXCore@objc(cs)LiveCoreView","navigatorTitle":[{"text":"LiveCoreView","kind":"identifier"}],"role":"symbol","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LiveCoreView","kind":"identifier"}],"modules":[{"name":"AtomicXCore"}]},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/objc(cs)UIView"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)NSCoding","doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)NSObject","doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.AtomicXCore\/s7CVarArgP","doc:\/\/org.cocoapods.AtomicXCore\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.AtomicXCore\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.AtomicXCore\/SQ","doc:\/\/org.cocoapods.AtomicXCore\/SH","doc:\/\/org.cocoapods.AtomicXCore\/s8SendableP","doc:\/\/org.cocoapods.AtomicXCore\/s16SendableMetatypeP","doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.AtomicXCore\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UIUserActivityRestoring","doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UICoordinateSpace"],"title":"Conforms To","type":"conformsTo"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"title":"Initializers","generated":true,"anchor":"Initializers","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/init(viewType:frame:)"]},{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/videoViewDelegate"]},{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/cancelBattle(battleId:userIdList:onSuccess:onError:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/cancelCrossRoomConnection(roomId:onSuccess:onError:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/cancelIntraRoomConnection(userId:onSuccess:onError:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/didMoveToWindow()","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/disconnectUser(userId:onSuccess:onError:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/enableMirror(enable:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/getState()","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/joinLiveStream(roomId:onSuccess:onError:)-3zkry","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/joinLiveStream(roomId:onSuccess:onError:)-rcay","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/leaveLiveStream(onSuccess:onError:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/muteMicrophone()","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/registerBattleObserver(observer:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/registerConnectionObserver(observer:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/requestBattle(config:userIdList:timeout:onSuccess:onError:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/requestCrossRoomConnection(roomId:timeOut:onSuccess:onError:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/requestIntraRoomConnection(userId:timeOut:openCamera:seatIndex:onSuccess:onError:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/respondIntraRoomConnection(userId:isAccepted:onSuccess:onError:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/respondToBattle(battleId:isAccepted:onSuccess:onError:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/respondToCrossRoomConnection(roomId:isAccepted:onSuccess:onError:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/setLiveID(_:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/setLocalVideoMuteImage(bigImage:smallImage:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/startCamera(useFrontCamera:onSuccess:onError:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/startLiveStream(liveInfo:onSuccess:onError:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/startLiveStream(roomInfo:onSuccess:onError:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/startMicrophone(onSuccess:onError:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/startPreviewLiveStream(roomId:isMuteAudio:onPlaying:onLoading:onError:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/stopCamera()","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/stopLiveStream(onSuccess:onError:)-4c4j7","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/stopLiveStream(onSuccess:onError:)-6ibtq","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/stopMicrophone()","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/stopPreviewLiveStream(roomId:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/subscribeState(_:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/switchCamera(isFront:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/terminateBattle(battleId:onSuccess:onError:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/terminateCrossRoomConnection()","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/terminateIntraRoomConnection()","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/unmuteMicrophone(onSuccess:onError:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/unregisterBattleObserver(observer:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/unregisterConnectionObserver(observer:)"]},{"title":"Type Methods","generated":true,"anchor":"Type-Methods","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/callExperimentalAPI(_:)"]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LiveCoreView","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://org.cocoapods.AtomicXCore/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView/respondToBattle(battleId:isAccepted:onSuccess:onError:)":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/respondToBattle(battleId:isAccepted:onSuccess:onError:)","url":"\/documentation\/atomicxcore\/livecoreview\/respondtobattle(battleid:isaccepted:onsuccess:onerror:)","type":"topic","role":"symbol","abstract":[],"title":"respondToBattle(battleId:isAccepted:onSuccess:onError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"respondToBattle"},{"kind":"text","text":"("},{"text":"battleId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"isAccepted","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"onSuccess","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUISuccessBlock","kind":"typeIdentifier","preciseIdentifier":"c:TUICommonDefine.h@T@TUISuccessBlock"},{"text":", ","kind":"text"},{"text":"onError","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUIErrorBlock","kind":"typeIdentifier","preciseIdentifier":"c:TUICommonDefine.h@T@TUIErrorBlock"},{"text":")","kind":"text"}],"deprecated":true},"doc://org.cocoapods.AtomicXCore/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView/stopPreviewLiveStream(roomId:)":{"abstract":[{"type":"text","text":"Stop preview outside room"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopPreviewLiveStream"},{"kind":"text","text":"("},{"kind":"externalParam","text":"roomId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/stopPreviewLiveStream(roomId:)","kind":"symbol","title":"stopPreviewLiveStream(roomId:)","url":"\/documentation\/atomicxcore\/livecoreview\/stoppreviewlivestream(roomid:)","type":"topic","role":"symbol"},"doc://org.cocoapods.AtomicXCore/objc(pl)UIAppearance":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UIAppearance","type":"unresolvable","title":"UIKit.UIAppearance"},"doc://org.cocoapods.AtomicXCore/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UIAccessibilityIdentification","title":"UIKit.UIAccessibilityIdentification"},"doc://org.cocoapods.AtomicXCore/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://org.cocoapods.AtomicXCore/objc(pl)UIFocusEnvironment":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView/leaveLiveStream(onSuccess:onError:)":{"title":"leaveLiveStream(onSuccess:onError:)","deprecated":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"leaveLiveStream","kind":"identifier"},{"text":"(","kind":"text"},{"text":"onSuccess","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUISuccessBlock","preciseIdentifier":"c:TUICommonDefine.h@T@TUISuccessBlock","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"onError","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUIErrorBlock","preciseIdentifier":"c:TUICommonDefine.h@T@TUIErrorBlock","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/atomicxcore\/livecoreview\/leavelivestream(onsuccess:onerror:)","abstract":[],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/leaveLiveStream(onSuccess:onError:)"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView/terminateBattle(battleId:onSuccess:onError:)":{"title":"terminateBattle(battleId:onSuccess:onError:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"terminateBattle"},{"kind":"text","text":"("},{"kind":"externalParam","text":"battleId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onSuccess"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TUISuccessBlock","preciseIdentifier":"c:TUICommonDefine.h@T@TUISuccessBlock"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TUIErrorBlock","preciseIdentifier":"c:TUICommonDefine.h@T@TUIErrorBlock"},{"kind":"text","text":")"}],"deprecated":true,"type":"topic","url":"\/documentation\/atomicxcore\/livecoreview\/terminatebattle(battleid:onsuccess:onerror:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/terminateBattle(battleId:onSuccess:onError:)"},"doc://org.cocoapods.AtomicXCore/objc(pl)CALayerDelegate":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)CALayerDelegate","title":"QuartzCore.CALayerDelegate"},"doc://org.cocoapods.AtomicXCore/s8SendableP":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView/startCamera(useFrontCamera:onSuccess:onError:)":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/startCamera(useFrontCamera:onSuccess:onError:)","deprecated":true,"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startCamera","kind":"identifier"},{"text":"(","kind":"text"},{"text":"useFrontCamera","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"onSuccess","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:TUICommonDefine.h@T@TUISuccessBlock","text":"TUISuccessBlock","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"onError","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:TUICommonDefine.h@T@TUIErrorBlock","text":"TUIErrorBlock","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/atomicxcore\/livecoreview\/startcamera(usefrontcamera:onsuccess:onerror:)","title":"startCamera(useFrontCamera:onSuccess:onError:)","role":"symbol","kind":"symbol","abstract":[]},"doc://org.cocoapods.AtomicXCore/objc(pl)UIDynamicItem":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UIDynamicItem","title":"UIKit.UIDynamicItem","type":"unresolvable"},"doc://org.cocoapods.AtomicXCore/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring"},"doc://org.cocoapods.AtomicXCore/objc(pl)UIFocusItem":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UIFocusItem","title":"UIKit.UIFocusItem","type":"unresolvable"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView/terminateIntraRoomConnection()":{"deprecated":true,"abstract":[],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/atomicxcore\/livecoreview\/terminateintraroomconnection()","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/terminateIntraRoomConnection()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"terminateIntraRoomConnection","kind":"identifier"},{"text":"()","kind":"text"}],"title":"terminateIntraRoomConnection()"},"doc://org.cocoapods.AtomicXCore/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UITraitEnvironment","type":"unresolvable","title":"UIKit.UITraitEnvironment"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView/switchCamera(isFront:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"switchCamera","kind":"identifier"},{"text":"(","kind":"text"},{"text":"isFront","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"title":"switchCamera(isFront:)","role":"symbol","url":"\/documentation\/atomicxcore\/livecoreview\/switchcamera(isfront:)","type":"topic","kind":"symbol","deprecated":true,"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/switchCamera(isFront:)","abstract":[]},"doc://org.cocoapods.AtomicXCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView/respondIntraRoomConnection(userId:isAccepted:onSuccess:onError:)":{"title":"respondIntraRoomConnection(userId:isAccepted:onSuccess:onError:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"respondIntraRoomConnection"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isAccepted"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onSuccess"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TUISuccessBlock","preciseIdentifier":"c:TUICommonDefine.h@T@TUISuccessBlock"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TUIErrorBlock","preciseIdentifier":"c:TUICommonDefine.h@T@TUIErrorBlock"},{"kind":"text","text":")"}],"deprecated":true,"type":"topic","url":"\/documentation\/atomicxcore\/livecoreview\/respondintraroomconnection(userid:isaccepted:onsuccess:onerror:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/respondIntraRoomConnection(userId:isAccepted:onSuccess:onError:)"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView/joinLiveStream(roomId:onSuccess:onError:)-3zkry":{"abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"joinLiveStream"},{"kind":"text","text":"("},{"kind":"externalParam","text":"roomId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onSuccess"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TUIRoomInfoBlock","preciseIdentifier":"c:TUIRoomDefine.h@T@TUIRoomInfoBlock"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TUIErrorBlock","preciseIdentifier":"c:TUICommonDefine.h@T@TUIErrorBlock"},{"kind":"text","text":")"}],"url":"\/documentation\/atomicxcore\/livecoreview\/joinlivestream(roomid:onsuccess:onerror:)-3zkry","kind":"symbol","type":"topic","role":"symbol","deprecated":true,"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/joinLiveStream(roomId:onSuccess:onError:)-3zkry","title":"joinLiveStream(roomId:onSuccess:onError:)"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView/cancelBattle(battleId:userIdList:onSuccess:onError:)":{"abstract":[],"kind":"symbol","role":"symbol","title":"cancelBattle(battleId:userIdList:onSuccess:onError:)","url":"\/documentation\/atomicxcore\/livecoreview\/cancelbattle(battleid:useridlist:onsuccess:onerror:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancelBattle","kind":"identifier"},{"text":"(","kind":"text"},{"text":"battleId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"userIdList","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"onSuccess","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUISuccessBlock","preciseIdentifier":"c:TUICommonDefine.h@T@TUISuccessBlock","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"onError","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUIErrorBlock","preciseIdentifier":"c:TUICommonDefine.h@T@TUIErrorBlock","kind":"typeIdentifier"},{"text":")","kind":"text"}],"deprecated":true,"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/cancelBattle(battleId:userIdList:onSuccess:onError:)"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView/startLiveStream(liveInfo:onSuccess:onError:)":{"deprecated":true,"title":"startLiveStream(liveInfo:onSuccess:onError:)","role":"symbol","abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/startLiveStream(liveInfo:onSuccess:onError:)","url":"\/documentation\/atomicxcore\/livecoreview\/startlivestream(liveinfo:onsuccess:onerror:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"startLiveStream","kind":"identifier"},{"text":"(","kind":"text"},{"text":"liveInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUILiveInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUILiveInfo"},{"text":", ","kind":"text"},{"text":"onSuccess","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUILiveInfoBlock","kind":"typeIdentifier","preciseIdentifier":"c:TUILiveListManager.h@T@TUILiveInfoBlock"},{"text":", ","kind":"text"},{"text":"onError","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUIErrorBlock","kind":"typeIdentifier","preciseIdentifier":"c:TUICommonDefine.h@T@TUIErrorBlock"},{"text":")","kind":"text"}]},"doc://org.cocoapods.AtomicXCore/objc(pl)UILargeContentViewerItem":{"title":"UIKit.UILargeContentViewerItem","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UILargeContentViewerItem"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView/stopMicrophone()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopMicrophone","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","abstract":[],"kind":"symbol","url":"\/documentation\/atomicxcore\/livecoreview\/stopmicrophone()","deprecated":true,"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/stopMicrophone()","title":"stopMicrophone()","type":"topic"},"doc://org.cocoapods.AtomicXCore/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/SH"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView/stopLiveStream(onSuccess:onError:)-4c4j7":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopLiveStream","kind":"identifier"},{"text":"(","kind":"text"},{"text":"onSuccess","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUIStopLiveBlock","kind":"typeIdentifier","preciseIdentifier":"c:TUILiveListManager.h@T@TUIStopLiveBlock"},{"text":", ","kind":"text"},{"text":"onError","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUIErrorBlock","kind":"typeIdentifier","preciseIdentifier":"c:TUICommonDefine.h@T@TUIErrorBlock"},{"text":")","kind":"text"}],"role":"symbol","abstract":[],"kind":"symbol","url":"\/documentation\/atomicxcore\/livecoreview\/stoplivestream(onsuccess:onerror:)-4c4j7","deprecated":true,"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/stopLiveStream(onSuccess:onError:)-4c4j7","title":"stopLiveStream(onSuccess:onError:)","type":"topic"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView/startPreviewLiveStream(roomId:isMuteAudio:onPlaying:onLoading:onError:)":{"kind":"symbol","type":"topic","title":"startPreviewLiveStream(roomId:isMuteAudio:onPlaying:onLoading:onError:)","url":"\/documentation\/atomicxcore\/livecoreview\/startpreviewlivestream(roomid:ismuteaudio:onplaying:onloading:onerror:)","role":"symbol","abstract":[{"type":"text","text":"Preview outside room"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/startPreviewLiveStream(roomId:isMuteAudio:onPlaying:onLoading:onError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startPreviewLiveStream"},{"kind":"text","text":"("},{"kind":"externalParam","text":"roomId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"isMuteAudio","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"onPlaying","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUIPlayOnPlayingBlock","kind":"typeIdentifier","preciseIdentifier":"c:TUIRoomDefine.h@T@TUIPlayOnPlayingBlock"},{"text":"?, ","kind":"text"},{"text":"onLoading","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUIPlayOnLoadingBlock","kind":"typeIdentifier","preciseIdentifier":"c:TUIRoomDefine.h@T@TUIPlayOnLoadingBlock"},{"text":"?, ","kind":"text"},{"text":"onError","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUIPlayOnErrorBlock","kind":"typeIdentifier","preciseIdentifier":"c:TUIRoomDefine.h@T@TUIPlayOnErrorBlock"},{"text":"?)","kind":"text"}]},"doc://org.cocoapods.AtomicXCore/objc(cs)UIView":{"title":"UIView","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(cs)UIView"},"doc://org.cocoapods.AtomicXCore/objc(pl)NSCoding":{"title":"Foundation.NSCoding","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)NSCoding"},"doc://org.cocoapods.AtomicXCore/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/5UIKit23UITraitChangeObservableP"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView/muteMicrophone()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"muteMicrophone"},{"kind":"text","text":"()"}],"role":"symbol","abstract":[],"kind":"symbol","url":"\/documentation\/atomicxcore\/livecoreview\/mutemicrophone()","deprecated":true,"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/muteMicrophone()","title":"muteMicrophone()","type":"topic"},"doc://org.cocoapods.AtomicXCore/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UIAppearanceContainer"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView/startMicrophone(onSuccess:onError:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startMicrophone"},{"kind":"text","text":"("},{"kind":"externalParam","text":"onSuccess"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:TUICommonDefine.h@T@TUISuccessBlock","text":"TUISuccessBlock"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:TUICommonDefine.h@T@TUIErrorBlock","text":"TUIErrorBlock"},{"kind":"text","text":")"}],"role":"symbol","abstract":[],"kind":"symbol","url":"\/documentation\/atomicxcore\/livecoreview\/startmicrophone(onsuccess:onerror:)","deprecated":true,"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/startMicrophone(onSuccess:onError:)","title":"startMicrophone(onSuccess:onError:)","type":"topic"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView/registerConnectionObserver(observer:)":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/registerConnectionObserver(observer:)","title":"registerConnectionObserver(observer:)","type":"topic","role":"symbol","url":"\/documentation\/atomicxcore\/livecoreview\/registerconnectionobserver(observer:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"registerConnectionObserver","kind":"identifier"},{"text":"(","kind":"text"},{"text":"observer","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ConnectionObserver","preciseIdentifier":"c:@M@AtomicXCore@objc(pl)ConnectionObserver","kind":"typeIdentifier"},{"text":")","kind":"text"}],"deprecated":true,"kind":"symbol","abstract":[]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView/didMoveToWindow()":{"title":"didMoveToWindow()","url":"\/documentation\/atomicxcore\/livecoreview\/didmovetowindow()","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/didMoveToWindow()","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didMoveToWindow","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"didMoveToWindow","kind":"identifier"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView/unregisterConnectionObserver(observer:)":{"type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unregisterConnectionObserver","kind":"identifier"},{"text":"(","kind":"text"},{"text":"observer","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ConnectionObserver","kind":"typeIdentifier","preciseIdentifier":"c:@M@AtomicXCore@objc(pl)ConnectionObserver"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/atomicxcore\/livecoreview\/unregisterconnectionobserver(observer:)","title":"unregisterConnectionObserver(observer:)","deprecated":true,"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/unregisterConnectionObserver(observer:)","abstract":[]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView/setLiveID(_:)":{"url":"\/documentation\/atomicxcore\/livecoreview\/setliveid(_:)","role":"symbol","title":"setLiveID(_:)","type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/setLiveID(_:)","abstract":[{"type":"text","text":"Set live ID"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setLiveID","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol"},"doc://org.cocoapods.AtomicXCore/objc(pl)UIPopoverPresentationControllerSourceItem":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UIPopoverPresentationControllerSourceItem","title":"UIKit.UIPopoverPresentationControllerSourceItem","type":"unresolvable"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView/enableMirror(enable:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enableMirror","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enable","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"type":"topic","title":"enableMirror(enable:)","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/enableMirror(enable:)","url":"\/documentation\/atomicxcore\/livecoreview\/enablemirror(enable:)","role":"symbol","abstract":[],"kind":"symbol","deprecated":true},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView/requestBattle(config:userIdList:timeout:onSuccess:onError:)":{"kind":"symbol","url":"\/documentation\/atomicxcore\/livecoreview\/requestbattle(config:useridlist:timeout:onsuccess:onerror:)","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/requestBattle(config:userIdList:timeout:onSuccess:onError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestBattle"},{"kind":"text","text":"("},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIBattleConfig","text":"TUIBattleConfig"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userIdList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"], ","kind":"text"},{"text":"timeout","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"onSuccess","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11AtomicXCore21TUIBattleRequestBlocka","text":"TUIBattleRequestBlock","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"onError","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:TUICommonDefine.h@T@TUIErrorBlock","text":"TUIErrorBlock","kind":"typeIdentifier"},{"text":")","kind":"text"}],"deprecated":true,"abstract":[],"title":"requestBattle(config:userIdList:timeout:onSuccess:onError:)"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView/callExperimentalAPI(_:)":{"title":"callExperimentalAPI(_:)","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/callExperimentalAPI(_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"callExperimentalAPI","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"url":"\/documentation\/atomicxcore\/livecoreview\/callexperimentalapi(_:)","type":"topic","role":"symbol","abstract":[],"kind":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView/getState()":{"kind":"symbol","url":"\/documentation\/atomicxcore\/livecoreview\/getstate()","role":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/getState()","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getState","kind":"identifier"},{"text":"<","kind":"text"},{"text":"T","kind":"genericParameter"},{"text":">() -> ","kind":"text"},{"preciseIdentifier":"s:11AtomicXCore12LiveCoreViewC8getStatexyAA0deG0RzlF1TL_xmfp","text":"T","kind":"typeIdentifier"}],"deprecated":true,"abstract":[],"title":"getState()"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"kind":"symbol","abstract":[],"type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView/cancelCrossRoomConnection(roomId:onSuccess:onError:)":{"kind":"symbol","title":"cancelCrossRoomConnection(roomId:onSuccess:onError:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancelCrossRoomConnection","kind":"identifier"},{"text":"(","kind":"text"},{"text":"roomId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"onSuccess","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUISuccessBlock","preciseIdentifier":"c:TUICommonDefine.h@T@TUISuccessBlock","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TUIErrorBlock","preciseIdentifier":"c:TUICommonDefine.h@T@TUIErrorBlock"},{"kind":"text","text":")"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/cancelCrossRoomConnection(roomId:onSuccess:onError:)","url":"\/documentation\/atomicxcore\/livecoreview\/cancelcrossroomconnection(roomid:onsuccess:onerror:)","type":"topic","deprecated":true},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView/joinLiveStream(roomId:onSuccess:onError:)-rcay":{"kind":"symbol","deprecated":true,"abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"joinLiveStream"},{"kind":"text","text":"("},{"kind":"externalParam","text":"roomId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onSuccess"},{"kind":"text","text":": "},{"preciseIdentifier":"c:TUILiveListManager.h@T@TUILiveInfoBlock","kind":"typeIdentifier","text":"TUILiveInfoBlock"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onError"},{"kind":"text","text":": "},{"preciseIdentifier":"c:TUICommonDefine.h@T@TUIErrorBlock","kind":"typeIdentifier","text":"TUIErrorBlock"},{"kind":"text","text":")"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/joinLiveStream(roomId:onSuccess:onError:)-rcay","title":"joinLiveStream(roomId:onSuccess:onError:)","url":"\/documentation\/atomicxcore\/livecoreview\/joinlivestream(roomid:onsuccess:onerror:)-rcay","type":"topic"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView/requestIntraRoomConnection(userId:timeOut:openCamera:seatIndex:onSuccess:onError:)":{"kind":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestIntraRoomConnection","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"timeOut","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"openCamera","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"seatIndex","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"onSuccess","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUISuccessBlock","preciseIdentifier":"c:TUICommonDefine.h@T@TUISuccessBlock","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"onError","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUIErrorBlock","preciseIdentifier":"c:TUICommonDefine.h@T@TUIErrorBlock","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/atomicxcore\/livecoreview\/requestintraroomconnection(userid:timeout:opencamera:seatindex:onsuccess:onerror:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/requestIntraRoomConnection(userId:timeOut:openCamera:seatIndex:onSuccess:onError:)","deprecated":true,"type":"topic","title":"requestIntraRoomConnection(userId:timeOut:openCamera:seatIndex:onSuccess:onError:)"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView/terminateCrossRoomConnection()":{"abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/terminateCrossRoomConnection()","title":"terminateCrossRoomConnection()","url":"\/documentation\/atomicxcore\/livecoreview\/terminatecrossroomconnection()","deprecated":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"terminateCrossRoomConnection","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView/unmuteMicrophone(onSuccess:onError:)":{"url":"\/documentation\/atomicxcore\/livecoreview\/unmutemicrophone(onsuccess:onerror:)","type":"topic","abstract":[],"title":"unmuteMicrophone(onSuccess:onError:)","deprecated":true,"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/unmuteMicrophone(onSuccess:onError:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"unmuteMicrophone"},{"kind":"text","text":"("},{"kind":"externalParam","text":"onSuccess"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:TUICommonDefine.h@T@TUISuccessBlock","text":"TUISuccessBlock"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:TUICommonDefine.h@T@TUIErrorBlock","text":"TUIErrorBlock"},{"kind":"text","text":")"}]},"doc://org.cocoapods.AtomicXCore/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/SQ","type":"unresolvable"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView/unregisterBattleObserver(observer:)":{"url":"\/documentation\/atomicxcore\/livecoreview\/unregisterbattleobserver(observer:)","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/unregisterBattleObserver(observer:)","type":"topic","deprecated":true,"kind":"symbol","abstract":[],"title":"unregisterBattleObserver(observer:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unregisterBattleObserver"},{"kind":"text","text":"("},{"kind":"externalParam","text":"observer"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@AtomicXCore@objc(pl)BattleObserver","kind":"typeIdentifier","text":"BattleObserver"},{"kind":"text","text":")"}]},"doc://org.cocoapods.AtomicXCore/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UIResponderStandardEditActions","type":"unresolvable"},"doc://org.cocoapods.AtomicXCore/objc(pl)UIPasteConfigurationSupporting":{"title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LiveCoreView"}],"url":"\/documentation\/atomicxcore\/livecoreview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LiveCoreView"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView","abstract":[],"role":"symbol","title":"LiveCoreView"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView/disconnectUser(userId:onSuccess:onError:)":{"deprecated":true,"title":"disconnectUser(userId:onSuccess:onError:)","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/disconnectUser(userId:onSuccess:onError:)","abstract":[],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disconnectUser","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"onSuccess","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUISuccessBlock","kind":"typeIdentifier","preciseIdentifier":"c:TUICommonDefine.h@T@TUISuccessBlock"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:TUICommonDefine.h@T@TUIErrorBlock","text":"TUIErrorBlock"},{"kind":"text","text":")"}],"kind":"symbol","url":"\/documentation\/atomicxcore\/livecoreview\/disconnectuser(userid:onsuccess:onerror:)","role":"symbol"},"doc://org.cocoapods.AtomicXCore/s16SendableMetatypeP":{"title":"Swift.SendableMetatype","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/s16SendableMetatypeP","type":"unresolvable"},"doc://org.cocoapods.AtomicXCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)NSObject","type":"unresolvable"},"doc://org.cocoapods.AtomicXCore/objc(pl)UIFocusItemContainer":{"title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UIFocusItemContainer","type":"unresolvable"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView/setLocalVideoMuteImage(bigImage:smallImage:)":{"url":"\/documentation\/atomicxcore\/livecoreview\/setlocalvideomuteimage(bigimage:smallimage:)","title":"setLocalVideoMuteImage(bigImage:smallImage:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLocalVideoMuteImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bigImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"smallImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?)"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/setLocalVideoMuteImage(bigImage:smallImage:)","deprecated":true,"role":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView/init(viewType:frame:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"viewType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CoreViewType","kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore12CoreViewTypeO"},{"text":", ","kind":"text"},{"text":"frame","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/init(viewType:frame:)","url":"\/documentation\/atomicxcore\/livecoreview\/init(viewtype:frame:)","role":"symbol","title":"init(viewType:frame:)","kind":"symbol","abstract":[{"text":"Constructor of LiveCoreView","type":"text"}],"type":"topic"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView/subscribeState(_:)":{"deprecated":true,"title":"subscribeState(_:)","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/subscribeState(_:)","abstract":[],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"subscribeState","kind":"identifier"},{"text":"<","kind":"text"},{"text":"State","kind":"genericParameter"},{"text":", ","kind":"text"},{"kind":"genericParameter","text":"Value"},{"kind":"text","text":">("},{"preciseIdentifier":"s:11AtomicXCore22StatePublisherSelectorC","text":"StatePublisherSelector","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"s:11AtomicXCore12LiveCoreViewC14subscribeStatey7Combine12AnyPublisherVyq_s5NeverOGAA0gJ8SelectorCyxq_Gr0_lF0G0L_xmfp"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Value","preciseIdentifier":"s:11AtomicXCore12LiveCoreViewC14subscribeStatey7Combine12AnyPublisherVyq_s5NeverOGAA0gJ8SelectorCyxq_Gr0_lF5ValueL_q_mfp"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","text":"AnyPublisher","preciseIdentifier":"s:7Combine12AnyPublisherV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Value","preciseIdentifier":"s:11AtomicXCore12LiveCoreViewC14subscribeStatey7Combine12AnyPublisherVyq_s5NeverOGAA0gJ8SelectorCyxq_Gr0_lF5ValueL_q_mfp"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Never","preciseIdentifier":"s:s5NeverO"},{"kind":"text","text":">"}],"kind":"symbol","url":"\/documentation\/atomicxcore\/livecoreview\/subscribestate(_:)","role":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView/startLiveStream(roomInfo:onSuccess:onError:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startLiveStream"},{"kind":"text","text":"("},{"kind":"externalParam","text":"roomInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIRoomInfo","text":"TUIRoomInfo"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onSuccess"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:TUIRoomDefine.h@T@TUIRoomInfoBlock","text":"TUIRoomInfoBlock"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:TUICommonDefine.h@T@TUIErrorBlock","text":"TUIErrorBlock"},{"kind":"text","text":")"}],"role":"symbol","abstract":[],"kind":"symbol","url":"\/documentation\/atomicxcore\/livecoreview\/startlivestream(roominfo:onsuccess:onerror:)","deprecated":true,"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/startLiveStream(roomInfo:onSuccess:onError:)","title":"startLiveStream(roomInfo:onSuccess:onError:)","type":"topic"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView/cancelIntraRoomConnection(userId:onSuccess:onError:)":{"title":"cancelIntraRoomConnection(userId:onSuccess:onError:)","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/cancelIntraRoomConnection(userId:onSuccess:onError:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancelIntraRoomConnection","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"onSuccess","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUISuccessBlock","kind":"typeIdentifier","preciseIdentifier":"c:TUICommonDefine.h@T@TUISuccessBlock"},{"text":", ","kind":"text"},{"text":"onError","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:TUICommonDefine.h@T@TUIErrorBlock","text":"TUIErrorBlock","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","abstract":[],"url":"\/documentation\/atomicxcore\/livecoreview\/cancelintraroomconnection(userid:onsuccess:onerror:)","deprecated":true,"type":"topic"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView/videoViewDelegate":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/videoViewDelegate","url":"\/documentation\/atomicxcore\/livecoreview\/videoviewdelegate","kind":"symbol","title":"videoViewDelegate","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"videoViewDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"VideoViewDelegate","preciseIdentifier":"c:@M@AtomicXCore@objc(pl)VideoViewDelegate","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Set widget view adapter"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.AtomicXCore/objc(pl)UICoordinateSpace":{"title":"UIUtilities.UICoordinateSpace","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UICoordinateSpace"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView/stopLiveStream(onSuccess:onError:)-6ibtq":{"abstract":[],"deprecated":true,"title":"stopLiveStream(onSuccess:onError:)","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/stopLiveStream(onSuccess:onError:)-6ibtq","url":"\/documentation\/atomicxcore\/livecoreview\/stoplivestream(onsuccess:onerror:)-6ibtq","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopLiveStream"},{"kind":"text","text":"("},{"kind":"externalParam","text":"onSuccess"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:TUICommonDefine.h@T@TUISuccessBlock","text":"TUISuccessBlock"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:TUICommonDefine.h@T@TUIErrorBlock","text":"TUIErrorBlock"},{"kind":"text","text":")"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView/respondToCrossRoomConnection(roomId:isAccepted:onSuccess:onError:)":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/respondToCrossRoomConnection(roomId:isAccepted:onSuccess:onError:)","url":"\/documentation\/atomicxcore\/livecoreview\/respondtocrossroomconnection(roomid:isaccepted:onsuccess:onerror:)","kind":"symbol","deprecated":true,"title":"respondToCrossRoomConnection(roomId:isAccepted:onSuccess:onError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"respondToCrossRoomConnection"},{"kind":"text","text":"("},{"kind":"externalParam","text":"roomId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isAccepted"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onSuccess"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TUISuccessBlock","preciseIdentifier":"c:TUICommonDefine.h@T@TUISuccessBlock"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TUIErrorBlock","preciseIdentifier":"c:TUICommonDefine.h@T@TUIErrorBlock"},{"text":")","kind":"text"}],"abstract":[],"type":"topic","role":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView/requestCrossRoomConnection(roomId:timeOut:onSuccess:onError:)":{"deprecated":true,"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/requestCrossRoomConnection(roomId:timeOut:onSuccess:onError:)","role":"symbol","title":"requestCrossRoomConnection(roomId:timeOut:onSuccess:onError:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestCrossRoomConnection"},{"kind":"text","text":"("},{"kind":"externalParam","text":"roomId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timeOut"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"onSuccess","kind":"externalParam"},{"text":": ((","kind":"text"},{"preciseIdentifier":"c:@E@TUIConnectionCode","text":"TUIConnectionCode","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":"), ","kind":"text"},{"text":"onError","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:TUICommonDefine.h@T@TUIErrorBlock","text":"TUIErrorBlock","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"kind":"symbol","url":"\/documentation\/atomicxcore\/livecoreview\/requestcrossroomconnection(roomid:timeout:onsuccess:onerror:)"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView/stopCamera()":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/stopCamera()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopCamera","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","abstract":[],"url":"\/documentation\/atomicxcore\/livecoreview\/stopcamera()","deprecated":true,"type":"topic","title":"stopCamera()"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView/registerBattleObserver(observer:)":{"title":"registerBattleObserver(observer:)","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/registerBattleObserver(observer:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerBattleObserver"},{"kind":"text","text":"("},{"kind":"externalParam","text":"observer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@AtomicXCore@objc(pl)BattleObserver","text":"BattleObserver"},{"kind":"text","text":")"}],"url":"\/documentation\/atomicxcore\/livecoreview\/registerbattleobserver(observer:)","role":"symbol","kind":"symbol","deprecated":true,"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"LiveCoreView","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"LiveCoreView","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"LiveCoreView","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/didMoveToWindow()"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/objc(cs)UIView"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"LiveCoreView"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LiveCoreView~1didMoveToWindow()\/title","op":"replace","value":"didMoveToWindow"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LiveCoreView~1didMoveToWindow()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didMoveToWindow"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LiveCoreView\/title","value":"LiveCoreView","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LiveCoreView\/fragments","value":[{"kind":"identifier","text":"LiveCoreView"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LiveCoreView\/navigatorTitle","value":[{"text":"LiveCoreView","kind":"identifier"}],"op":"replace"}]}]}