{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore"]]},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStore\/conversationID","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStore\/state"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStore\/downloadMessageResource(_:resourceType:completion:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStore\/fetchMessageList(with:completion:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStore\/fetchMoreMessageList(direction:completion:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"},{"identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStore\/create(conversationID:messageListType:)"],"title":"Type Methods","generated":true,"anchor":"Type-Methods"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"role":"symbol","symbolKind":"class","title":"MessageListStore","roleHeading":"Class","modules":[{"name":"AtomicXCore"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageListStore","kind":"identifier"}],"navigatorTitle":[{"text":"MessageListStore","kind":"identifier"}],"externalID":"c:@M@AtomicXCore@objc(cs)MessageListStore"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStore"},"kind":"symbol","relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)NSObject","doc:\/\/org.cocoapods.AtomicXCore\/s7CVarArgP","doc:\/\/org.cocoapods.AtomicXCore\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.AtomicXCore\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.AtomicXCore\/SQ","doc:\/\/org.cocoapods.AtomicXCore\/SH"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageListStore"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/atomicxcore\/messageliststore"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/atomicxcore\/messageliststore"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.AtomicXCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.AtomicXCore/objc(cs)NSObject":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/MessageListStore/downloadMessageResource(_:resourceType:completion:)":{"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStore\/downloadMessageResource(_:resourceType:completion:)","title":"downloadMessageResource(_:resourceType:completion:)","role":"symbol","url":"\/documentation\/atomicxcore\/messageliststore\/downloadmessageresource(_:resourcetype:completion:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"downloadMessageResource","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MessageInfo","preciseIdentifier":"s:11AtomicXCore11MessageInfoV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"resourceType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MessageMediaFileType","preciseIdentifier":"s:11AtomicXCore20MessageMediaFileTypeO","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CompletionClosure","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/MessageListStore/fetchMessageList(with:completion:)":{"title":"fetchMessageList(with:completion:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStore\/fetchMessageList(with:completion:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchMessageList"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore18MessageFetchOptionV","text":"MessageFetchOption"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","text":"CompletionClosure"},{"text":"?)","kind":"text"}],"kind":"symbol","abstract":[],"url":"\/documentation\/atomicxcore\/messageliststore\/fetchmessagelist(with:completion:)"},"doc://org.cocoapods.AtomicXCore/SQ":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://org.cocoapods.AtomicXCore/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"abstract":[],"title":"AtomicXCore","type":"topic","kind":"symbol","url":"\/documentation\/atomicxcore","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","role":"collection"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/MessageListStore/conversationID":{"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStore\/conversationID","title":"conversationID","role":"symbol","url":"\/documentation\/atomicxcore\/messageliststore\/conversationid","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationID","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/MessageListStore/state":{"url":"\/documentation\/atomicxcore\/messageliststore\/state","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"state","kind":"identifier"},{"text":": ","kind":"text"},{"text":"StatePublisher","preciseIdentifier":"s:11AtomicXCore14StatePublisherC","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"MessageListState","preciseIdentifier":"s:11AtomicXCore16MessageListStateV","kind":"typeIdentifier"},{"text":">","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStore\/state","abstract":[],"title":"state","kind":"symbol"},"doc://org.cocoapods.AtomicXCore/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/MessageListStore/create(conversationID:messageListType:)":{"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStore\/create(conversationID:messageListType:)","title":"create(conversationID:messageListType:)","role":"symbol","url":"\/documentation\/atomicxcore\/messageliststore\/create(conversationid:messagelisttype:)","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"conversationID","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"messageListType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11AtomicXCore15MessageListTypeO","text":"MessageListType","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@AtomicXCore@objc(cs)MessageListStore","text":"MessageListStore","kind":"typeIdentifier"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/MessageListStore/fetchMoreMessageList(direction:completion:)":{"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStore\/fetchMoreMessageList(direction:completion:)","title":"fetchMoreMessageList(direction:completion:)","role":"symbol","url":"\/documentation\/atomicxcore\/messageliststore\/fetchmoremessagelist(direction:completion:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchMoreMessageList"},{"kind":"text","text":"("},{"kind":"externalParam","text":"direction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore21MessageFetchDirectionV","text":"MessageFetchDirection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","text":"CompletionClosure"},{"kind":"text","text":"?)"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/MessageListStore":{"abstract":[],"title":"MessageListStore","role":"symbol","navigatorTitle":[{"text":"MessageListStore","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStore","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageListStore","kind":"identifier"}],"url":"\/documentation\/atomicxcore\/messageliststore"},"doc://org.cocoapods.AtomicXCore/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://org.cocoapods.AtomicXCore/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"value":"MessageListStore","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"MessageListStore"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"MessageListStore","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":null,"op":"replace","path":"\/topicSections"},{"value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/objc(cs)NSObject"]}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageListStore"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MessageListStore","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStore\/title"},{"value":[{"text":"MessageListStore","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStore\/fragments"},{"value":[{"kind":"identifier","text":"MessageListStore"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStore\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}