{"metadata":{"title":"ParticipantView","externalID":"c:@M@AtomicXCore@objc(cs)ParticipantView","role":"symbol","symbolKind":"class","modules":[{"name":"AtomicXCore"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ParticipantView","kind":"identifier"}],"roleHeading":"Class","navigatorTitle":[{"text":"ParticipantView","kind":"identifier"}]},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ParticipantView","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/atomicxcore\/participantview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/atomicxcore\/participantview"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore"]]},"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ParticipantView","interfaceLanguage":"swift"},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/objc(cs)UIView"]},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)NSCoding","doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)NSObject","doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.AtomicXCore\/s7CVarArgP","doc:\/\/org.cocoapods.AtomicXCore\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.AtomicXCore\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.AtomicXCore\/SQ","doc:\/\/org.cocoapods.AtomicXCore\/SH","doc:\/\/org.cocoapods.AtomicXCore\/s8SendableP","doc:\/\/org.cocoapods.AtomicXCore\/s16SendableMetatypeP","doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.AtomicXCore\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UIUserActivityRestoring","doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UICoordinateSpace"]}],"topicSections":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ParticipantView\/init(participantId:streamType:)"],"title":"Initializers","anchor":"Initializers"},{"generated":true,"identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ParticipantView\/didMoveToWindow()","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ParticipantView\/setRenderParams(params:)"],"title":"Instance Methods","anchor":"Instance-Methods"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.AtomicXCore/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.AtomicXCore/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UILargeContentViewerItem","title":"UIKit.UILargeContentViewerItem"},"doc://org.cocoapods.AtomicXCore/objc(pl)UICoordinateSpace":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UICoordinateSpace","title":"UIUtilities.UICoordinateSpace"},"doc://org.cocoapods.AtomicXCore/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions"},"doc://org.cocoapods.AtomicXCore/objc(pl)UIDynamicItem":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UIDynamicItem","title":"UIKit.UIDynamicItem"},"doc://org.cocoapods.AtomicXCore/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UIPopoverPresentationControllerSourceItem","title":"UIKit.UIPopoverPresentationControllerSourceItem"},"doc://org.cocoapods.AtomicXCore/objc(pl)NSCoding":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)NSCoding","title":"Foundation.NSCoding"},"doc://org.cocoapods.AtomicXCore/objc(pl)UIFocusEnvironment":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment"},"doc://org.cocoapods.AtomicXCore/objc(pl)UIAppearance":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UIAppearance","title":"UIKit.UIAppearance"},"doc://org.cocoapods.AtomicXCore/objc(pl)UIFocusItemContainer":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UIFocusItemContainer","title":"UIKit.UIFocusItemContainer"},"doc://org.cocoapods.AtomicXCore/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UIAccessibilityIdentification","title":"UIKit.UIAccessibilityIdentification"},"doc://org.cocoapods.AtomicXCore/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.AtomicXCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.AtomicXCore/objc(pl)UITraitEnvironment":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment"},"doc://org.cocoapods.AtomicXCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ParticipantView/didMoveToWindow()":{"kind":"symbol","url":"\/documentation\/atomicxcore\/participantview\/didmovetowindow()","type":"topic","title":"didMoveToWindow()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didMoveToWindow","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"didMoveToWindow","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ParticipantView\/didMoveToWindow()","abstract":[],"role":"symbol"},"doc://org.cocoapods.AtomicXCore/objc(pl)CALayerDelegate":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)CALayerDelegate","title":"QuartzCore.CALayerDelegate"},"doc://org.cocoapods.AtomicXCore/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.AtomicXCore/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.AtomicXCore/s16SendableMetatypeP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/s16SendableMetatypeP","title":"Swift.SendableMetatype"},"doc://org.cocoapods.AtomicXCore/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/s8SendableP","title":"Swift.Sendable"},"doc://org.cocoapods.AtomicXCore/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ParticipantView/init(participantId:streamType:)":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ParticipantView\/init(participantId:streamType:)","url":"\/documentation\/atomicxcore\/participantview\/init(participantid:streamtype:)","type":"topic","role":"symbol","title":"init(participantId:streamType:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"participantId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"streamType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@TUIVideoStreamType","text":"TUIVideoStreamType","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ParticipantView/setRenderParams(params:)":{"kind":"symbol","role":"symbol","abstract":[],"title":"setRenderParams(params:)","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ParticipantView\/setRenderParams(params:)","type":"topic","url":"\/documentation\/atomicxcore\/participantview\/setrenderparams(params:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setRenderParams","kind":"identifier"},{"text":"(","kind":"text"},{"text":"params","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUIVideoRenderParams","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIVideoRenderParams"},{"text":")","kind":"text"}]},"doc://org.cocoapods.AtomicXCore/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable"},"doc://org.cocoapods.AtomicXCore/objc(pl)UIAppearanceContainer":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer"},"doc://org.cocoapods.AtomicXCore/objc(pl)UIFocusItem":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UIFocusItem","title":"UIKit.UIFocusItem"},"doc://org.cocoapods.AtomicXCore/objc(cs)UIView":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(cs)UIView","title":"UIView"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"kind":"symbol","abstract":[],"type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ParticipantView":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ParticipantView","type":"topic","url":"\/documentation\/atomicxcore\/participantview","role":"symbol","title":"ParticipantView","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ParticipantView"}],"navigatorTitle":[{"kind":"identifier","text":"ParticipantView"}]},"doc://org.cocoapods.AtomicXCore/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/s7CVarArgP","title":"Swift.CVarArg"},"doc://org.cocoapods.AtomicXCore/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"ParticipantView","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"ParticipantView","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"ParticipantView"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ParticipantView\/didMoveToWindow()"],"title":"Instance Methods","generated":true}],"path":"\/topicSections","op":"replace"},{"value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/objc(cs)UIView"],"type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ParticipantView"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"didMoveToWindow","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ParticipantView~1didMoveToWindow()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"didMoveToWindow","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ParticipantView~1didMoveToWindow()\/fragments","op":"replace"},{"value":"ParticipantView","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ParticipantView\/title","op":"replace"},{"value":[{"text":"ParticipantView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ParticipantView\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"ParticipantView"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ParticipantView\/navigatorTitle","op":"replace"}]}]}