{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore"]]},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/objc(cs)NSObject"],"type":"inheritsFrom"},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)NSObject","doc:\/\/org.cocoapods.AtomicXCore\/s7CVarArgP","doc:\/\/org.cocoapods.AtomicXCore\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.AtomicXCore\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.AtomicXCore\/SQ","doc:\/\/org.cocoapods.AtomicXCore\/s25ExpressibleByArrayLiteralP","doc:\/\/org.cocoapods.AtomicXCore\/SH","doc:\/\/org.cocoapods.AtomicXCore\/s9OptionSetP","doc:\/\/org.cocoapods.AtomicXCore\/SY","doc:\/\/org.cocoapods.AtomicXCore\/s10SetAlgebraP"]}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/init(rawValue:)"],"generated":true,"anchor":"Initializers"},{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/rawValue"],"anchor":"Instance-Properties"},{"generated":true,"title":"Type Properties","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/hasAudioStream","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/hasVideoStream","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/nameCard","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/none","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/userRole"],"anchor":"Type-Properties"},{"title":"Default Implementations","anchor":"Default-Implementations","generated":true,"identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/OptionSet-Implementations","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/SetAlgebra-Implementations"]}],"variants":[{"paths":["\/documentation\/atomicxcore\/userinfomodifyflag"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/atomicxcore\/userinfomodifyflag"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"UserInfoModifyFlag","kind":"identifier"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"title":"UserInfoModifyFlag","platforms":[],"roleHeading":"Class","role":"symbol","modules":[{"name":"AtomicXCore"}],"symbolKind":"class","externalID":"c:@M@AtomicXCore@objc(cs)UserInfoModifyFlag","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UserInfoModifyFlag"}],"navigatorTitle":[{"text":"UserInfoModifyFlag","kind":"identifier"}]},"sections":[],"kind":"symbol","references":{"doc://org.cocoapods.AtomicXCore/SH":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/UserInfoModifyFlag":{"navigatorTitle":[{"text":"UserInfoModifyFlag","kind":"identifier"}],"role":"symbol","deprecated":true,"abstract":[],"type":"topic","title":"UserInfoModifyFlag","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"UserInfoModifyFlag","kind":"identifier"}],"url":"\/documentation\/atomicxcore\/userinfomodifyflag"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/UserInfoModifyFlag/hasVideoStream":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/hasVideoStream","kind":"symbol","role":"symbol","url":"\/documentation\/atomicxcore\/userinfomodifyflag\/hasvideostream","navigatorTitle":[{"text":"hasVideoStream","kind":"identifier"}],"abstract":[],"deprecated":true,"title":"hasVideoStream","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hasVideoStream","kind":"identifier"},{"kind":"text","text":": "},{"text":"UserInfoModifyFlag","kind":"typeIdentifier","preciseIdentifier":"c:@M@AtomicXCore@objc(cs)UserInfoModifyFlag"}],"type":"topic"},"doc://org.cocoapods.AtomicXCore/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(cs)NSObject","type":"unresolvable"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/UserInfoModifyFlag/userRole":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userRole","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@AtomicXCore@objc(cs)UserInfoModifyFlag","text":"UserInfoModifyFlag"}],"url":"\/documentation\/atomicxcore\/userinfomodifyflag\/userrole","kind":"symbol","abstract":[],"title":"userRole","type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/userRole","deprecated":true,"navigatorTitle":[{"text":"userRole","kind":"identifier"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/UserInfoModifyFlag/init(rawValue:)":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/init(rawValue:)","abstract":[],"url":"\/documentation\/atomicxcore\/userinfomodifyflag\/init(rawvalue:)","title":"init(rawValue:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","deprecated":true},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/UserInfoModifyFlag/SetAlgebra-Implementations":{"abstract":[],"kind":"article","url":"\/documentation\/atomicxcore\/userinfomodifyflag\/setalgebra-implementations","title":"SetAlgebra Implementations","role":"collectionGroup","type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/SetAlgebra-Implementations"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/UserInfoModifyFlag/hasAudioStream":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"hasAudioStream","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@AtomicXCore@objc(cs)UserInfoModifyFlag","text":"UserInfoModifyFlag","kind":"typeIdentifier"}],"deprecated":true,"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/hasAudioStream","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"hasAudioStream"}],"title":"hasAudioStream","type":"topic","url":"\/documentation\/atomicxcore\/userinfomodifyflag\/hasaudiostream","role":"symbol"},"doc://org.cocoapods.AtomicXCore/s10SetAlgebraP":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/s10SetAlgebraP","title":"Swift.SetAlgebra","type":"unresolvable"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/UserInfoModifyFlag/rawValue":{"type":"topic","abstract":[],"url":"\/documentation\/atomicxcore\/userinfomodifyflag\/rawvalue","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"rawValue","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"deprecated":true,"title":"rawValue","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/rawValue","role":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/UserInfoModifyFlag/OptionSet-Implementations":{"kind":"article","url":"\/documentation\/atomicxcore\/userinfomodifyflag\/optionset-implementations","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/OptionSet-Implementations","type":"topic","title":"OptionSet Implementations"},"doc://org.cocoapods.AtomicXCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)NSObject"},"doc://org.cocoapods.AtomicXCore/s9OptionSetP":{"title":"Swift.OptionSet","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/s9OptionSetP"},"doc://org.cocoapods.AtomicXCore/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.AtomicXCore/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/SY"},"doc://org.cocoapods.AtomicXCore/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/s7CVarArgP"},"doc://org.cocoapods.AtomicXCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/s23CustomStringConvertibleP"},"doc://org.cocoapods.AtomicXCore/s25ExpressibleByArrayLiteralP":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/s25ExpressibleByArrayLiteralP","title":"Swift.ExpressibleByArrayLiteral","type":"unresolvable"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/UserInfoModifyFlag/nameCard":{"title":"nameCard","type":"topic","url":"\/documentation\/atomicxcore\/userinfomodifyflag\/namecard","deprecated":true,"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nameCard","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UserInfoModifyFlag","kind":"typeIdentifier","preciseIdentifier":"c:@M@AtomicXCore@objc(cs)UserInfoModifyFlag"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/nameCard","abstract":[],"navigatorTitle":[{"text":"nameCard","kind":"identifier"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/UserInfoModifyFlag/none":{"kind":"symbol","role":"symbol","url":"\/documentation\/atomicxcore\/userinfomodifyflag\/none","deprecated":true,"title":"none","abstract":[],"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@AtomicXCore@objc(cs)UserInfoModifyFlag","kind":"typeIdentifier","text":"UserInfoModifyFlag"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/none","navigatorTitle":[{"kind":"identifier","text":"none"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","title":"AtomicXCore","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","abstract":[],"url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/SQ":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/SQ","title":"Swift.Equatable","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":[],"path":"\/metadata\/platforms","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","value":"UserInfoModifyFlag","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","value":[{"text":"UserInfoModifyFlag","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"UserInfoModifyFlag","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"title":"Type Properties","anchor":"Type-Properties","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/hasAudioStream","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/hasVideoStream","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/nameCard","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/none","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/userRole"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/objc(cs)NSObject"],"kind":"relationships"}]},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UserInfoModifyFlag","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1UserInfoModifyFlag\/title","value":"UserInfoModifyFlag","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1UserInfoModifyFlag\/fragments","op":"replace","value":[{"kind":"identifier","text":"UserInfoModifyFlag"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1UserInfoModifyFlag\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UserInfoModifyFlag"}]},{"op":"replace","value":"hasVideoStream","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1UserInfoModifyFlag~1hasVideoStream\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1UserInfoModifyFlag~1hasVideoStream\/fragments","value":[{"kind":"identifier","text":"hasVideoStream"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1UserInfoModifyFlag~1userRole\/title","value":"userRole","op":"replace"},{"value":[{"kind":"identifier","text":"userRole"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1UserInfoModifyFlag~1userRole\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1UserInfoModifyFlag~1hasAudioStream\/title","value":"hasAudioStream"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1UserInfoModifyFlag~1hasAudioStream\/fragments","value":[{"text":"hasAudioStream","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1UserInfoModifyFlag~1nameCard\/title","value":"nameCard","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1UserInfoModifyFlag~1nameCard\/fragments","value":[{"text":"nameCard","kind":"identifier"}],"op":"replace"},{"value":"none","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1UserInfoModifyFlag~1none\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1UserInfoModifyFlag~1none\/fragments","value":[{"kind":"identifier","text":"none"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}