{"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ViewLayer","interfaceLanguage":"swift"},"topicSections":[{"generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ViewLayer\/background","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ViewLayer\/foreground"],"anchor":"Enumeration-Cases"},{"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ViewLayer\/init(rawValue:)"],"generated":true},{"anchor":"Default-Implementations","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ViewLayer\/Equatable-Implementations","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ViewLayer\/RawRepresentable-Implementations"],"title":"Default Implementations","generated":true}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore"]]},"relationshipsSections":[{"type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/SQ","doc:\/\/org.cocoapods.AtomicXCore\/SH","doc:\/\/org.cocoapods.AtomicXCore\/SY"],"kind":"relationships","title":"Conforms To"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ViewLayer","kind":"identifier"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/viewlayer"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/atomicxcore\/viewlayer"]}],"metadata":{"symbolKind":"enum","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ViewLayer"}],"externalID":"c:@M@AtomicXCore@E@ViewLayer","navigatorTitle":[{"kind":"identifier","text":"ViewLayer"}],"modules":[{"name":"AtomicXCore"}],"roleHeading":"Enumeration","role":"symbol","title":"ViewLayer"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ViewLayer/Equatable-Implementations":{"title":"Equatable Implementations","type":"topic","role":"collectionGroup","kind":"article","abstract":[],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ViewLayer\/Equatable-Implementations","url":"\/documentation\/atomicxcore\/viewlayer\/equatable-implementations"},"doc://org.cocoapods.AtomicXCore/SH":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ViewLayer/background":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"background","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ViewLayer\/background","title":"ViewLayer.background","type":"topic","url":"\/documentation\/atomicxcore\/viewlayer\/background","navigatorTitle":[{"text":"ViewLayerBackground","kind":"identifier"}],"kind":"symbol","abstract":[],"role":"symbol"},"doc://org.cocoapods.AtomicXCore/SY":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/SY","title":"Swift.RawRepresentable"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ViewLayer/init(rawValue:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(rawValue:)","abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ViewLayer\/init(rawValue:)","kind":"symbol","url":"\/documentation\/atomicxcore\/viewlayer\/init(rawvalue:)"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ViewLayer":{"abstract":[],"type":"topic","title":"ViewLayer","url":"\/documentation\/atomicxcore\/viewlayer","navigatorTitle":[{"text":"ViewLayer","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ViewLayer","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ViewLayer","role":"symbol","kind":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","title":"AtomicXCore","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","abstract":[],"url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ViewLayer/foreground":{"title":"ViewLayer.foreground","url":"\/documentation\/atomicxcore\/viewlayer\/foreground","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"foreground"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ViewLayerForeground"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ViewLayer\/foreground","abstract":[],"role":"symbol"},"doc://org.cocoapods.AtomicXCore/SQ":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ViewLayer/RawRepresentable-Implementations":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ViewLayer\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","abstract":[],"type":"topic","url":"\/documentation\/atomicxcore\/viewlayer\/rawrepresentable-implementations","role":"collectionGroup","kind":"article"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"ViewLayer"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"value":[{"text":"ViewLayer","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"ViewLayer","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ViewLayer\/background","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ViewLayer\/foreground"],"anchor":"Enumeration-Cases","title":"Enumeration Cases"}]},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ViewLayer","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ViewLayer~1background\/title","value":"ViewLayerBackground"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ViewLayer~1background\/fragments","value":[{"text":"ViewLayerBackground","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ViewLayer\/title","value":"ViewLayer"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ViewLayer\/fragments","value":[{"kind":"identifier","text":"ViewLayer"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ViewLayer\/navigatorTitle","value":[{"kind":"identifier","text":"ViewLayer"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ViewLayer~1foreground\/title","op":"replace","value":"ViewLayerForeground"},{"value":[{"text":"ViewLayerForeground","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ViewLayer~1foreground\/fragments","op":"replace"}]}]}