{"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/SignalVideoView"]]},"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/SignalVideoView\/didMoveToWindow()","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"didMoveToWindow","kind":"identifier"}],"externalID":"c:@M@AtomicXCore@objc(cs)SignalVideoView(im)didMoveToWindow","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"didMoveToWindow","kind":"identifier"},{"text":"()","kind":"text"}],"modules":[{"name":"AtomicXCore"}],"title":"didMoveToWindow()","symbolKind":"method","roleHeading":"Instance Method"},"variants":[{"paths":["\/documentation\/atomicxcore\/signalvideoview\/didmovetowindow()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/atomicxcore\/signalvideoview\/didmovetowindow()"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didMoveToWindow","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"]}]}],"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/SignalVideoView/didMoveToWindow()":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/SignalVideoView\/didMoveToWindow()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didMoveToWindow","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"didMoveToWindow","kind":"identifier"}],"url":"\/documentation\/atomicxcore\/signalvideoview\/didmovetowindow()","role":"symbol","title":"didMoveToWindow()","abstract":[],"type":"topic"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"url":"\/documentation\/atomicxcore","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","type":"topic","kind":"symbol","abstract":[],"role":"collection"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/SignalVideoView":{"role":"symbol","abstract":[],"title":"SignalVideoView","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/SignalVideoView","url":"\/documentation\/atomicxcore\/signalvideoview","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SignalVideoView","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"SignalVideoView","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"didMoveToWindow"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didMoveToWindow"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"didMoveToWindow"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1SignalVideoView~1didMoveToWindow()\/title","value":"didMoveToWindow"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"didMoveToWindow","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1SignalVideoView~1didMoveToWindow()\/fragments"},{"op":"replace","value":"SignalVideoView","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1SignalVideoView\/title"},{"op":"replace","value":[{"text":"SignalVideoView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1SignalVideoView\/fragments"},{"op":"replace","value":[{"text":"SignalVideoView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1SignalVideoView\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}