{"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallParticipantStore\/shared"},"metadata":{"externalID":"s:11AtomicXCore20CallParticipantStoreC6sharedAA0cdE4ImplCvpZ","symbolKind":"property","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CallParticipantStoreImpl","preciseIdentifier":"c:@M@AtomicXCore@objc(cs)CallParticipantStoreImpl","kind":"typeIdentifier"}],"roleHeading":"Type Property","modules":[{"name":"AtomicXCore"}],"title":"shared"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallParticipantStore"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/callparticipantstore\/shared"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CallParticipantStoreImpl","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallParticipantStoreImpl","preciseIdentifier":"c:@M@AtomicXCore@objc(cs)CallParticipantStoreImpl","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"kind":"symbol","references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallParticipantStore/shared":{"title":"shared","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CallParticipantStoreImpl","kind":"typeIdentifier","preciseIdentifier":"c:@M@AtomicXCore@objc(cs)CallParticipantStoreImpl"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallParticipantStore\/shared","url":"\/documentation\/atomicxcore\/callparticipantstore\/shared"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"url":"\/documentation\/atomicxcore","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","type":"topic","kind":"symbol","abstract":[],"role":"collection"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallParticipantStoreImpl":{"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallParticipantStoreImpl","kind":"identifier"}],"type":"topic","title":"CallParticipantStoreImpl","kind":"symbol","url":"\/documentation\/atomicxcore\/callparticipantstoreimpl","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallParticipantStoreImpl","role":"symbol","navigatorTitle":[{"text":"CallParticipantStoreImpl","kind":"identifier"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallParticipantStore":{"navigatorTitle":[{"text":"CallParticipantStore","kind":"identifier"}],"kind":"symbol","title":"CallParticipantStore","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallParticipantStore","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallParticipantStore","abstract":[],"url":"\/documentation\/atomicxcore\/callparticipantstore"}},"variantOverrides":[{"patch":[{"value":"CallParticipantStoreImpl","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallParticipantStoreImpl\/title","op":"replace"},{"value":[{"kind":"identifier","text":"CallParticipantStoreImpl"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallParticipantStoreImpl\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"CallParticipantStoreImpl"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallParticipantStoreImpl\/navigatorTitle","op":"replace"},{"value":"CallParticipantStore","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallParticipantStore\/title","op":"replace"},{"value":[{"kind":"identifier","text":"CallParticipantStore"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallParticipantStore\/fragments","op":"replace"},{"value":[{"text":"CallParticipantStore","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallParticipantStore\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}