{"sections":[],"metadata":{"title":"ViewLayer.background","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"background","kind":"identifier"}],"roleHeading":"Case","externalID":"c:@M@AtomicXCore@E@ViewLayer@ViewLayerBackground","role":"symbol","symbolKind":"case","modules":[{"name":"AtomicXCore"}],"navigatorTitle":[{"text":"ViewLayerBackground","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ViewLayer"]]},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ViewLayer\/background","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"background","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/viewlayer\/background"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/atomicxcore\/viewlayer\/background"]}],"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ViewLayer/background":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"background","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ViewLayer\/background","title":"ViewLayer.background","type":"topic","url":"\/documentation\/atomicxcore\/viewlayer\/background","navigatorTitle":[{"text":"ViewLayerBackground","kind":"identifier"}],"kind":"symbol","abstract":[],"role":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ViewLayer":{"abstract":[],"type":"topic","title":"ViewLayer","url":"\/documentation\/atomicxcore\/viewlayer","navigatorTitle":[{"text":"ViewLayer","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ViewLayer","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ViewLayer","role":"symbol","kind":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","title":"AtomicXCore","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","abstract":[],"url":"\/documentation\/atomicxcore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"ViewLayerBackground"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"ViewLayerBackground","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"ViewLayerBackground","kind":"identifier"}]}]}},{"value":"ViewLayerBackground","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ViewLayer~1background\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ViewLayer~1background\/fragments","value":[{"text":"ViewLayerBackground","kind":"identifier"}]},{"value":"ViewLayer","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ViewLayer\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ViewLayer"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ViewLayer\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ViewLayer\/navigatorTitle","op":"replace","value":[{"text":"ViewLayer","kind":"identifier"}]}]}]}