{"kind":"article","metadata":{"modules":[{"name":"AtomicXCore"}],"role":"collectionGroup","roleHeading":"API Collection","title":"Equatable Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ViewLayer"]]},"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ViewLayer\/Equatable-Implementations","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ViewLayer\/!=(_:_:)"],"anchor":"Operators","generated":true,"title":"Operators"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/viewlayer\/equatable-implementations"]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","title":"AtomicXCore","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","abstract":[],"url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ViewLayer":{"abstract":[],"type":"topic","title":"ViewLayer","url":"\/documentation\/atomicxcore\/viewlayer","navigatorTitle":[{"text":"ViewLayer","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ViewLayer","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ViewLayer","role":"symbol","kind":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ViewLayer/!=(_:_:)":{"type":"topic","abstract":[],"title":"!=(_:_:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ViewLayer\/!=(_:_:)","url":"\/documentation\/atomicxcore\/viewlayer\/!=(_:_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"kind":"text","text":"("},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ViewLayer\/title","value":"ViewLayer"},{"value":[{"text":"ViewLayer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ViewLayer\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ViewLayer\/navigatorTitle","value":[{"text":"ViewLayer","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}