{"metadata":{"modules":[{"name":"AtomicXCore"}],"title":"acceptFriendApplication(info:completion:)","roleHeading":"Instance Method","externalID":"s:11AtomicXCore16ContactListStoreC23acceptFriendApplication4info10completionyAA0gH4InfoV_ys6ResultOyytAA05ErrorK0VGcSgtF","symbolKind":"method","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"acceptFriendApplication"},{"text":"(","kind":"text"},{"text":"info","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FriendApplicationInfo","preciseIdentifier":"s:11AtomicXCore21FriendApplicationInfoV","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"text":"CompletionClosure","kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea"},{"kind":"text","text":"?)"}]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"acceptFriendApplication","kind":"identifier"},{"kind":"text","text":"("},{"text":"info","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11AtomicXCore21FriendApplicationInfoV","text":"FriendApplicationInfo","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/FriendApplicationInfo"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CompletionClosure","kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","text":"CompletionClosure"},{"kind":"text","text":"?)"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStore"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStore\/acceptFriendApplication(info:completion:)"},"variants":[{"paths":["\/documentation\/atomicxcore\/contactliststore\/acceptfriendapplication(info:completion:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ContactListStore/acceptFriendApplication(info:completion:)":{"title":"acceptFriendApplication(info:completion:)","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStore\/acceptFriendApplication(info:completion:)","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"acceptFriendApplication","kind":"identifier"},{"text":"(","kind":"text"},{"text":"info","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FriendApplicationInfo","preciseIdentifier":"s:11AtomicXCore21FriendApplicationInfoV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"text":"CompletionClosure","kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea"},{"kind":"text","text":"?)"}],"url":"\/documentation\/atomicxcore\/contactliststore\/acceptfriendapplication(info:completion:)","type":"topic","kind":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/FriendApplicationInfo":{"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"FriendApplicationInfo","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/FriendApplicationInfo","type":"topic","title":"FriendApplicationInfo","url":"\/documentation\/atomicxcore\/friendapplicationinfo","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FriendApplicationInfo"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ContactListStore":{"kind":"symbol","title":"ContactListStore","type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStore","url":"\/documentation\/atomicxcore\/contactliststore","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ContactListStore"}],"navigatorTitle":[{"text":"ContactListStore","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CompletionClosure":{"url":"\/documentation\/atomicxcore\/completionclosure","kind":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"CompletionClosure"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CompletionClosure","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CompletionClosure","title":"CompletionClosure","role":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","title":"AtomicXCore","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","abstract":[],"url":"\/documentation\/atomicxcore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ContactListStore\/title","value":"ContactListStore"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ContactListStore\/fragments","value":[{"kind":"identifier","text":"ContactListStore"}]},{"op":"replace","value":[{"text":"ContactListStore","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ContactListStore\/navigatorTitle"}]}]}