{"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStore\/create()","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"AtomicXCore"}],"roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"create","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@AtomicXCore@objc(cs)ContactListStore","text":"ContactListStore","kind":"typeIdentifier"}],"role":"symbol","symbolKind":"method","title":"create()","externalID":"s:11AtomicXCore16ContactListStoreC6createACyFZ"},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"create","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStore","preciseIdentifier":"c:@M@AtomicXCore@objc(cs)ContactListStore","text":"ContactListStore"}]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStore"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/contactliststore\/create()"]}],"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ContactListStore/create()":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStore\/create()","role":"symbol","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@AtomicXCore@objc(cs)ContactListStore","text":"ContactListStore"}],"url":"\/documentation\/atomicxcore\/contactliststore\/create()","kind":"symbol","type":"topic","title":"create()"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ContactListStore":{"kind":"symbol","title":"ContactListStore","type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStore","url":"\/documentation\/atomicxcore\/contactliststore","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ContactListStore"}],"navigatorTitle":[{"text":"ContactListStore","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","title":"AtomicXCore","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","abstract":[],"url":"\/documentation\/atomicxcore"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ContactListStore\/title","op":"replace","value":"ContactListStore"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ContactListStore\/fragments","value":[{"text":"ContactListStore","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ContactListStore\/navigatorTitle","value":[{"text":"ContactListStore","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}