{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refuseGroupApplication"},{"kind":"text","text":"("},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore20GroupApplicationInfoV","text":"GroupApplicationInfo","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupApplicationInfo"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","text":"CompletionClosure","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CompletionClosure"},{"kind":"text","text":"?)"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"refuseGroupApplication","kind":"identifier"},{"text":"(","kind":"text"},{"text":"info","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GroupApplicationInfo","kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore20GroupApplicationInfoV"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CompletionClosure","kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea"},{"text":"?)","kind":"text"}],"title":"refuseGroupApplication(info:completion:)","role":"symbol","externalID":"s:11AtomicXCore16ContactListStoreC22refuseGroupApplication4info10completionyAA0gH4InfoV_ys6ResultOyytAA05ErrorK0VGcSgtF","roleHeading":"Instance Method","modules":[{"name":"AtomicXCore"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStore"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/contactliststore\/refusegroupapplication(info:completion:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStore\/refuseGroupApplication(info:completion:)"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ContactListStore/refuseGroupApplication(info:completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refuseGroupApplication"},{"kind":"text","text":"("},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupApplicationInfo","preciseIdentifier":"s:11AtomicXCore20GroupApplicationInfoV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CompletionClosure","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea"},{"kind":"text","text":"?)"}],"abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/atomicxcore\/contactliststore\/refusegroupapplication(info:completion:)","title":"refuseGroupApplication(info:completion:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStore\/refuseGroupApplication(info:completion:)"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ContactListStore":{"kind":"symbol","url":"\/documentation\/atomicxcore\/contactliststore","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStore","title":"ContactListStore","navigatorTitle":[{"kind":"identifier","text":"ContactListStore"}],"abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContactListStore"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/GroupApplicationInfo":{"kind":"symbol","type":"topic","navigatorTitle":[{"text":"GroupApplicationInfo","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/GroupApplicationInfo","url":"\/documentation\/atomicxcore\/groupapplicationinfo","role":"symbol","title":"GroupApplicationInfo","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GroupApplicationInfo","kind":"identifier"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CompletionClosure":{"url":"\/documentation\/atomicxcore\/completionclosure","abstract":[{"type":"text","text":"完成回调闭包类型"},{"type":"text","text":" "},{"type":"text","text":"用于异步操作的结果回调，成功返回 Void，失败返回 ErrorInfo"}],"type":"topic","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CompletionClosure","kind":"identifier"}],"title":"CompletionClosure","role":"symbol","navigatorTitle":[{"text":"CompletionClosure","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CompletionClosure"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"kind":"symbol","abstract":[],"type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","url":"\/documentation\/atomicxcore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ContactListStore\/title","op":"replace","value":"ContactListStore"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ContactListStore\/fragments","op":"replace","value":[{"kind":"identifier","text":"ContactListStore"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ContactListStore\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ContactListStore"}]}]}]}