{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag"]]},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/formIntersection(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"formIntersection","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"other","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"formIntersection"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":")"}],"externalID":"s:s9OptionSetPss17FixedWidthInteger8RawValueRpzrlE16formIntersectionyyxF::SYNTHESIZED::c:@M@AtomicXCore@objc(cs)UserInfoModifyFlag","title":"formIntersection(_:)","roleHeading":"Instance Method","extendedModule":"Swift","conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"constraints":[{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"FixedWidthInteger"},{"text":".","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}]},"modules":[{"name":"AtomicXCore","relatedModules":["Swift"]}],"role":"symbol","symbolKind":"method"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"OptionSet.formIntersection(_:)"},{"type":"text","text":"."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/userinfomodifyflag\/formintersection(_:)"]}],"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/UserInfoModifyFlag/formIntersection(_:)":{"title":"formIntersection(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"formIntersection","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/formIntersection(_:)","type":"topic","abstract":[],"kind":"symbol","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"FixedWidthInteger"},{"type":"text","text":"."}]},"url":"\/documentation\/atomicxcore\/userinfomodifyflag\/formintersection(_:)"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/UserInfoModifyFlag":{"role":"symbol","kind":"symbol","deprecated":true,"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserInfoModifyFlag"}],"navigatorTitle":[{"kind":"identifier","text":"UserInfoModifyFlag"}],"abstract":[],"type":"topic","url":"\/documentation\/atomicxcore\/userinfomodifyflag","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag","title":"UserInfoModifyFlag"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"abstract":[],"title":"AtomicXCore","type":"topic","kind":"symbol","url":"\/documentation\/atomicxcore","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"UserInfoModifyFlag","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1UserInfoModifyFlag\/title"},{"op":"replace","value":[{"text":"UserInfoModifyFlag","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1UserInfoModifyFlag\/fragments"},{"op":"replace","value":[{"text":"UserInfoModifyFlag","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1UserInfoModifyFlag\/navigatorTitle"}]}]}