{"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/hasAudioStream","interfaceLanguage":"swift"},"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"hasAudioStream","kind":"identifier"},{"kind":"text","text":": "},{"text":"UserInfoModifyFlag","preciseIdentifier":"c:@M@AtomicXCore@objc(cs)UserInfoModifyFlag","kind":"typeIdentifier"}],"title":"hasAudioStream","platforms":[],"modules":[{"name":"AtomicXCore"}],"externalID":"c:@M@AtomicXCore@objc(cs)UserInfoModifyFlag(cpy)hasAudioStream","roleHeading":"Type Property","navigatorTitle":[{"text":"hasAudioStream","kind":"identifier"}],"symbolKind":"property","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"hasAudioStream","kind":"identifier"},{"kind":"text","text":": "},{"text":"UserInfoModifyFlag","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag","preciseIdentifier":"c:@M@AtomicXCore@objc(cs)UserInfoModifyFlag","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/userinfomodifyflag\/hasaudiostream"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/atomicxcore\/userinfomodifyflag\/hasaudiostream"]}],"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/UserInfoModifyFlag/hasAudioStream":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"hasAudioStream","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@AtomicXCore@objc(cs)UserInfoModifyFlag","text":"UserInfoModifyFlag","kind":"typeIdentifier"}],"deprecated":true,"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/hasAudioStream","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"hasAudioStream"}],"title":"hasAudioStream","type":"topic","url":"\/documentation\/atomicxcore\/userinfomodifyflag\/hasaudiostream","role":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","title":"AtomicXCore","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","abstract":[],"url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/UserInfoModifyFlag":{"navigatorTitle":[{"text":"UserInfoModifyFlag","kind":"identifier"}],"role":"symbol","deprecated":true,"abstract":[],"type":"topic","title":"UserInfoModifyFlag","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"UserInfoModifyFlag","kind":"identifier"}],"url":"\/documentation\/atomicxcore\/userinfomodifyflag"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"hasAudioStream"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"hasAudioStream","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"class"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"UserInfoModifyFlag","kind":"typeIdentifier","preciseIdentifier":"c:@M@AtomicXCore@objc(cs)UserInfoModifyFlag","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag"},{"kind":"text","text":" * "},{"text":"hasAudioStream","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"hasAudioStream","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1UserInfoModifyFlag~1hasAudioStream\/title"},{"value":[{"kind":"identifier","text":"hasAudioStream"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1UserInfoModifyFlag~1hasAudioStream\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1UserInfoModifyFlag\/title","value":"UserInfoModifyFlag"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1UserInfoModifyFlag\/fragments","value":[{"kind":"identifier","text":"UserInfoModifyFlag"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1UserInfoModifyFlag\/navigatorTitle","value":[{"text":"UserInfoModifyFlag","kind":"identifier"}]}]}]}