{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag"]]},"metadata":{"roleHeading":"Type Property","navigatorTitle":[{"text":"hasVideoStream","kind":"identifier"}],"role":"symbol","symbolKind":"property","platforms":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"hasVideoStream","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@AtomicXCore@objc(cs)UserInfoModifyFlag","text":"UserInfoModifyFlag","kind":"typeIdentifier"}],"title":"hasVideoStream","modules":[{"name":"AtomicXCore"}],"externalID":"c:@M@AtomicXCore@objc(cs)UserInfoModifyFlag(cpy)hasVideoStream"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/userinfomodifyflag\/hasvideostream"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/atomicxcore\/userinfomodifyflag\/hasvideostream"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/hasVideoStream"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hasVideoStream"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@AtomicXCore@objc(cs)UserInfoModifyFlag","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag","text":"UserInfoModifyFlag"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","title":"AtomicXCore","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","abstract":[],"url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/UserInfoModifyFlag/hasVideoStream":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/hasVideoStream","kind":"symbol","role":"symbol","url":"\/documentation\/atomicxcore\/userinfomodifyflag\/hasvideostream","navigatorTitle":[{"text":"hasVideoStream","kind":"identifier"}],"abstract":[],"deprecated":true,"title":"hasVideoStream","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hasVideoStream","kind":"identifier"},{"kind":"text","text":": "},{"text":"UserInfoModifyFlag","kind":"typeIdentifier","preciseIdentifier":"c:@M@AtomicXCore@objc(cs)UserInfoModifyFlag"}],"type":"topic"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/UserInfoModifyFlag":{"navigatorTitle":[{"text":"UserInfoModifyFlag","kind":"identifier"}],"role":"symbol","deprecated":true,"abstract":[],"type":"topic","title":"UserInfoModifyFlag","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"UserInfoModifyFlag","kind":"identifier"}],"url":"\/documentation\/atomicxcore\/userinfomodifyflag"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"hasVideoStream"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"kind":"identifier","text":"hasVideoStream"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@AtomicXCore@objc(cs)UserInfoModifyFlag","kind":"typeIdentifier","text":"UserInfoModifyFlag","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"hasVideoStream"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1UserInfoModifyFlag~1hasVideoStream\/title","value":"hasVideoStream","op":"replace"},{"value":[{"kind":"identifier","text":"hasVideoStream"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1UserInfoModifyFlag~1hasVideoStream\/fragments","op":"replace"},{"value":"UserInfoModifyFlag","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1UserInfoModifyFlag\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1UserInfoModifyFlag\/fragments","value":[{"kind":"identifier","text":"UserInfoModifyFlag"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1UserInfoModifyFlag\/navigatorTitle","value":[{"kind":"identifier","text":"UserInfoModifyFlag"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}