{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isSuperset","kind":"identifier"},{"text":"(","kind":"text"},{"text":"of","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"other","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/isSuperset(of:)"},"sections":[],"variants":[{"paths":["\/documentation\/atomicxcore\/userinfomodifyflag\/issuperset(of:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"SetAlgebra.isSuperset(of:)"},{"type":"text","text":"."}],"metadata":{"modules":[{"name":"AtomicXCore","relatedModules":["Swift"]}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isSuperset","kind":"identifier"},{"text":"(","kind":"text"},{"text":"of","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","externalID":"s:s10SetAlgebraPsE10isSuperset2ofSbx_tF::SYNTHESIZED::c:@M@AtomicXCore@objc(cs)UserInfoModifyFlag","symbolKind":"method","title":"isSuperset(of:)","roleHeading":"Instance Method","extendedModule":"Swift"},"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/UserInfoModifyFlag":{"url":"\/documentation\/atomicxcore\/userinfomodifyflag","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag","abstract":[],"navigatorTitle":[{"text":"UserInfoModifyFlag","kind":"identifier"}],"title":"UserInfoModifyFlag","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UserInfoModifyFlag","kind":"identifier"}],"deprecated":true},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/UserInfoModifyFlag/isSuperset(of:)":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/isSuperset(of:)","kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/atomicxcore\/userinfomodifyflag\/issuperset(of:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSuperset"},{"kind":"text","text":"("},{"kind":"externalParam","text":"of"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"isSuperset(of:)"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"url":"\/documentation\/atomicxcore","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","type":"topic","kind":"symbol","abstract":[],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1UserInfoModifyFlag\/title","op":"replace","value":"UserInfoModifyFlag"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1UserInfoModifyFlag\/fragments","op":"replace","value":[{"kind":"identifier","text":"UserInfoModifyFlag"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1UserInfoModifyFlag\/navigatorTitle","op":"replace","value":[{"text":"UserInfoModifyFlag","kind":"identifier"}]}]}]}