{"metadata":{"modules":[{"name":"AtomicXCore"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UserInfoModifyFlag","preciseIdentifier":"c:@M@AtomicXCore@objc(cs)UserInfoModifyFlag"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"none"}],"roleHeading":"Type Property","title":"none","role":"symbol","externalID":"c:@M@AtomicXCore@objc(cs)UserInfoModifyFlag(cpy)none","platforms":[{"beta":false,"unavailable":false,"deprecated":true}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag","text":"UserInfoModifyFlag","kind":"typeIdentifier","preciseIdentifier":"c:@M@AtomicXCore@objc(cs)UserInfoModifyFlag"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"variants":[{"paths":["\/documentation\/atomicxcore\/userinfomodifyflag\/none"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/atomicxcore\/userinfomodifyflag\/none"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/none","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"url":"\/documentation\/atomicxcore","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","type":"topic","kind":"symbol","abstract":[],"role":"collection"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/UserInfoModifyFlag/none":{"url":"\/documentation\/atomicxcore\/userinfomodifyflag\/none","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/none","deprecated":true,"abstract":[],"title":"none","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UserInfoModifyFlag","kind":"typeIdentifier","preciseIdentifier":"c:@M@AtomicXCore@objc(cs)UserInfoModifyFlag"}],"navigatorTitle":[{"text":"none","kind":"identifier"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/UserInfoModifyFlag":{"url":"\/documentation\/atomicxcore\/userinfomodifyflag","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag","abstract":[],"navigatorTitle":[{"text":"UserInfoModifyFlag","kind":"identifier"}],"title":"UserInfoModifyFlag","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UserInfoModifyFlag","kind":"identifier"}],"deprecated":true}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":[{"deprecated":true,"unavailable":false,"beta":false}],"path":"\/metadata\/platforms"},{"op":"replace","value":"Type Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"none","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"none","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UserInfoModifyFlag","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag","preciseIdentifier":"c:@M@AtomicXCore@objc(cs)UserInfoModifyFlag"},{"kind":"text","text":" * "},{"kind":"identifier","text":"none"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1UserInfoModifyFlag~1none\/title","value":"none"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1UserInfoModifyFlag~1none\/fragments","value":[{"kind":"identifier","text":"none"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1UserInfoModifyFlag\/title","value":"UserInfoModifyFlag"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1UserInfoModifyFlag\/fragments","value":[{"text":"UserInfoModifyFlag","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1UserInfoModifyFlag\/navigatorTitle","value":[{"kind":"identifier","text":"UserInfoModifyFlag"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}