{"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"article","hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag"]]},"topicSections":[{"title":"Initializers","generated":true,"anchor":"Initializers","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/init(_:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/init(arrayLiteral:)"]},{"anchor":"Instance-Properties","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/isEmpty"],"generated":true,"title":"Instance Properties"},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/isDisjoint(with:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/isStrictSubset(of:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/isStrictSuperset(of:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/isSubset(of:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/isSuperset(of:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/subtract(_:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/subtracting(_:)"]}],"metadata":{"modules":[{"name":"AtomicXCore"}],"roleHeading":"API Collection","role":"collectionGroup","title":"SetAlgebra Implementations"},"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/SetAlgebra-Implementations","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/userinfomodifyflag\/setalgebra-implementations"]}],"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/UserInfoModifyFlag/isEmpty":{"abstract":[],"title":"isEmpty","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isEmpty","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/atomicxcore\/userinfomodifyflag\/isempty","role":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/isEmpty","type":"topic"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","title":"AtomicXCore","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","abstract":[],"url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/UserInfoModifyFlag/isSuperset(of:)":{"url":"\/documentation\/atomicxcore\/userinfomodifyflag\/issuperset(of:)","type":"topic","abstract":[],"title":"isSuperset(of:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isSuperset","kind":"identifier"},{"kind":"text","text":"("},{"text":"of","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/isSuperset(of:)","kind":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/UserInfoModifyFlag/isDisjoint(with:)":{"abstract":[],"title":"isDisjoint(with:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isDisjoint","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/atomicxcore\/userinfomodifyflag\/isdisjoint(with:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/isDisjoint(with:)","type":"topic"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/UserInfoModifyFlag/isStrictSuperset(of:)":{"url":"\/documentation\/atomicxcore\/userinfomodifyflag\/isstrictsuperset(of:)","type":"topic","abstract":[],"title":"isStrictSuperset(of:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isStrictSuperset","kind":"identifier"},{"kind":"text","text":"("},{"text":"of","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/isStrictSuperset(of:)","kind":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/UserInfoModifyFlag/subtracting(_:)":{"abstract":[],"title":"subtracting(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"subtracting","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Self","kind":"typeIdentifier"}],"url":"\/documentation\/atomicxcore\/userinfomodifyflag\/subtracting(_:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/subtracting(_:)","type":"topic"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/UserInfoModifyFlag/isStrictSubset(of:)":{"title":"isStrictSubset(of:)","abstract":[],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/isStrictSubset(of:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isStrictSubset"},{"kind":"text","text":"("},{"text":"of","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/atomicxcore\/userinfomodifyflag\/isstrictsubset(of:)"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/UserInfoModifyFlag/init(_:)":{"url":"\/documentation\/atomicxcore\/userinfomodifyflag\/init(_:)","type":"topic","abstract":[],"title":"init(_:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"<"},{"text":"S","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"S","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/init(_:)"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/UserInfoModifyFlag/init(arrayLiteral:)":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/init(arrayLiteral:)","kind":"symbol","title":"init(arrayLiteral:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"arrayLiteral","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":".","kind":"text"},{"text":"Element","preciseIdentifier":"s:s10SetAlgebraP7ElementQa","kind":"typeIdentifier"},{"kind":"text","text":"...)"}],"url":"\/documentation\/atomicxcore\/userinfomodifyflag\/init(arrayliteral:)","conformance":{"constraints":[{"type":"codeVoice","code":"ArrayLiteralElement"},{"type":"text","text":" is "},{"type":"codeVoice","code":"Self.Element"},{"type":"text","text":"."}],"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}]},"role":"symbol","type":"topic","abstract":[]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/UserInfoModifyFlag/subtract(_:)":{"url":"\/documentation\/atomicxcore\/userinfomodifyflag\/subtract(_:)","type":"topic","abstract":[],"title":"subtract(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"subtract","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":")"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/subtract(_:)"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/UserInfoModifyFlag/isSubset(of:)":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/isSubset(of:)","kind":"symbol","title":"isSubset(of:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isSubset","kind":"identifier"},{"text":"(","kind":"text"},{"text":"of","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"url":"\/documentation\/atomicxcore\/userinfomodifyflag\/issubset(of:)","role":"symbol","type":"topic","abstract":[]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/UserInfoModifyFlag":{"navigatorTitle":[{"text":"UserInfoModifyFlag","kind":"identifier"}],"role":"symbol","deprecated":true,"abstract":[],"type":"topic","title":"UserInfoModifyFlag","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"UserInfoModifyFlag","kind":"identifier"}],"url":"\/documentation\/atomicxcore\/userinfomodifyflag"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1UserInfoModifyFlag\/title","op":"replace","value":"UserInfoModifyFlag"},{"op":"replace","value":[{"text":"UserInfoModifyFlag","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1UserInfoModifyFlag\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1UserInfoModifyFlag\/navigatorTitle","value":[{"text":"UserInfoModifyFlag","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}