{"metadata":{"extendedModule":"Swift","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"subtract"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":")"}],"title":"subtract(_:)","role":"symbol","symbolKind":"method","modules":[{"name":"AtomicXCore","relatedModules":["Swift"]}],"externalID":"s:s10SetAlgebraPsE8subtractyyxF::SYNTHESIZED::c:@M@AtomicXCore@objc(cs)UserInfoModifyFlag"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"SetAlgebra.subtract(_:)"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"mutating"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"subtract"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"other"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":")"}],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/subtract(_:)"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/userinfomodifyflag\/subtract(_:)"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"url":"\/documentation\/atomicxcore","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","type":"topic","kind":"symbol","abstract":[],"role":"collection"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/UserInfoModifyFlag":{"url":"\/documentation\/atomicxcore\/userinfomodifyflag","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag","abstract":[],"navigatorTitle":[{"text":"UserInfoModifyFlag","kind":"identifier"}],"title":"UserInfoModifyFlag","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UserInfoModifyFlag","kind":"identifier"}],"deprecated":true},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/UserInfoModifyFlag/subtract(_:)":{"title":"subtract(_:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/subtract(_:)","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"subtract"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":")"}],"type":"topic","url":"\/documentation\/atomicxcore\/userinfomodifyflag\/subtract(_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1UserInfoModifyFlag\/title","op":"replace","value":"UserInfoModifyFlag"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1UserInfoModifyFlag\/fragments","op":"replace","value":[{"kind":"identifier","text":"UserInfoModifyFlag"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1UserInfoModifyFlag\/navigatorTitle","op":"replace","value":[{"text":"UserInfoModifyFlag","kind":"identifier"}]}]}]}