{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"userRole"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UserInfoModifyFlag","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag","preciseIdentifier":"c:@M@AtomicXCore@objc(cs)UserInfoModifyFlag"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"externalID":"c:@M@AtomicXCore@objc(cs)UserInfoModifyFlag(cpy)userRole","role":"symbol","roleHeading":"Type Property","title":"userRole","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"userRole"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@AtomicXCore@objc(cs)UserInfoModifyFlag","text":"UserInfoModifyFlag"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"userRole"}],"modules":[{"name":"AtomicXCore"}],"platforms":[{"unavailable":false,"beta":false,"deprecated":true}]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/userRole"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag"]]},"sections":[],"variants":[{"paths":["\/documentation\/atomicxcore\/userinfomodifyflag\/userrole"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/atomicxcore\/userinfomodifyflag\/userrole"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/UserInfoModifyFlag":{"url":"\/documentation\/atomicxcore\/userinfomodifyflag","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag","abstract":[],"navigatorTitle":[{"text":"UserInfoModifyFlag","kind":"identifier"}],"title":"UserInfoModifyFlag","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UserInfoModifyFlag","kind":"identifier"}],"deprecated":true},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/UserInfoModifyFlag/userRole":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag\/userRole","kind":"symbol","title":"userRole","url":"\/documentation\/atomicxcore\/userinfomodifyflag\/userrole","role":"symbol","navigatorTitle":[{"text":"userRole","kind":"identifier"}],"deprecated":true,"abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userRole","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UserInfoModifyFlag","kind":"typeIdentifier","preciseIdentifier":"c:@M@AtomicXCore@objc(cs)UserInfoModifyFlag"}],"type":"topic"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"url":"\/documentation\/atomicxcore","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","type":"topic","kind":"symbol","abstract":[],"role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[{"deprecated":true,"beta":false,"unavailable":false}]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"userRole"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"userRole"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@AtomicXCore@objc(cs)UserInfoModifyFlag","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/UserInfoModifyFlag","text":"UserInfoModifyFlag"},{"kind":"text","text":" * "},{"kind":"identifier","text":"userRole"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1UserInfoModifyFlag\/title","value":"UserInfoModifyFlag","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1UserInfoModifyFlag\/fragments","value":[{"text":"UserInfoModifyFlag","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1UserInfoModifyFlag\/navigatorTitle","value":[{"text":"UserInfoModifyFlag","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1UserInfoModifyFlag~1userRole\/title","value":"userRole","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1UserInfoModifyFlag~1userRole\/fragments","value":[{"kind":"identifier","text":"userRole"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}